<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Handling Data with the Tidyverse | Welcome!</title>
  <meta name="description" content="Course notes for PSYC 3250" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Handling Data with the Tidyverse | Welcome!" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course notes for PSYC 3250" />
  <meta name="github-repo" content="dstanley4/psyc3250bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Handling Data with the Tidyverse | Welcome!" />
  
  <meta name="twitter:description" content="Course notes for PSYC 3250" />
  

<meta name="author" content="David J. Stanley" />


<meta name="date" content="2022-03-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-1-friday-workshop.html"/>
<link rel="next" href="week-2-friday-workshop.html"/>
<script src="libs/header-attrs/header-attrs.js"></script>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course Notes</a></li>

<li class="divider"></li>
<li><a href="index.html#course">Course:<span></span></a></li>
<li><a href="about-the-author.html#about-the-author">About the Author<span></span></a></li>
<li class="chapter" data-level="1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html"><i class="fa fa-check"></i><b>1</b> Week 1 Friday Workshop<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#a-focus-on-workflow"><i class="fa fa-check"></i><b>1.1</b> A focus on workflow<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#r-works-with-plug-ins"><i class="fa fa-check"></i><b>1.2</b> R works with plug-ins<span></span></a></li>
<li class="chapter" data-level="1.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#software-choice"><i class="fa fa-check"></i><b>1.3</b> Software Choice<span></span></a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#mac"><i class="fa fa-check"></i><b>1.3.1</b> Mac<span></span></a></li>
<li class="chapter" data-level="1.3.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#pc"><i class="fa fa-check"></i><b>1.3.2</b> PC<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-rstudio-not-r"><i class="fa fa-check"></i><b>1.4</b> Run RStudio not R<span></span></a></li>
<li class="chapter" data-level="1.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#rstudio-configuration-first-run-only"><i class="fa fa-check"></i><b>1.5</b> RStudio configuration, First run only<span></span></a></li>
<li class="chapter" data-level="1.6" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#begin-with-an-rstudio-project"><i class="fa fa-check"></i><b>1.6</b> Begin with an RStudio Project<span></span></a></li>
<li class="chapter" data-level="1.7" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#exploring-the-r-studio-interface"><i class="fa fa-check"></i><b>1.7</b> Exploring the R Studio Interface<span></span></a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#console-panel"><i class="fa fa-check"></i><b>1.7.1</b> Console panel<span></span></a></li>
<li class="chapter" data-level="1.7.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#script-panel"><i class="fa fa-check"></i><b>1.7.2</b> Script Panel<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#writing-your-first-script"><i class="fa fa-check"></i><b>1.8</b> Writing your first script<span></span></a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#create-the-script-file"><i class="fa fa-check"></i><b>1.8.1</b> Create the script file<span></span></a></li>
<li class="chapter" data-level="1.8.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#add-a-comment-to-your-script"><i class="fa fa-check"></i><b>1.8.2</b> Add a comment to your script<span></span></a></li>
<li class="chapter" data-level="1.8.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#background-about-the-tidyverse"><i class="fa fa-check"></i><b>1.8.3</b> Background about the tidyverse<span></span></a></li>
<li class="chapter" data-level="1.8.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#add-librarytidyverse-to-your-script"><i class="fa fa-check"></i><b>1.8.4</b> Add library(tidyverse) to your script<span></span></a></li>
<li class="chapter" data-level="1.8.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#activate-tidyverse-auto-complete-for-your-script"><i class="fa fa-check"></i><b>1.8.5</b> Activate tidyverse auto-complete for your script<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#loading-your-data"><i class="fa fa-check"></i><b>1.9</b> Loading your data<span></span></a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#use-read_csv-not-read.csv-to-open-files."><i class="fa fa-check"></i><b>1.9.1</b> Use read_csv (not read.csv) to open files.<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#checking-out-your-data"><i class="fa fa-check"></i><b>1.10</b> Checking out your data<span></span></a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#view-see-a-spreadsheet-view-of-your-data"><i class="fa fa-check"></i><b>1.10.1</b> view(): See a spreadsheet view of your data<span></span></a></li>
<li class="chapter" data-level="1.10.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#print-see-you-data-in-the-console"><i class="fa fa-check"></i><b>1.10.2</b> print(): See you data in the Console<span></span></a></li>
<li class="chapter" data-level="1.10.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#head-check-out-the-first-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.3</b> head(): Check out the first few rows of data<span></span></a></li>
<li class="chapter" data-level="1.10.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#tail-check-out-the-last-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.4</b> tail(): Check out the last few rows of data<span></span></a></li>
<li class="chapter" data-level="1.10.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#summary-quick-summaries"><i class="fa fa-check"></i><b>1.10.5</b> summary(): Quick summaries<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-vs.-source-with-echo-vs.-source"><i class="fa fa-check"></i><b>1.11</b> Run <em>vs.</em> Source with Echo <em>vs.</em> Source<span></span></a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-select-text"><i class="fa fa-check"></i><b>1.11.1</b> Run select text<span></span></a></li>
<li class="chapter" data-level="1.11.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#source-without-echo"><i class="fa fa-check"></i><b>1.11.2</b> Source (without Echo)<span></span></a></li>
<li class="chapter" data-level="1.11.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#source-with-echo"><i class="fa fa-check"></i><b>1.11.3</b> Source with Echo<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#trying-source-with-echo"><i class="fa fa-check"></i><b>1.12</b> Trying Source with Echo<span></span></a></li>
<li class="chapter" data-level="1.13" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#a-few-key-points-about"><i class="fa fa-check"></i><b>1.13</b> A few key points about<span></span></a>
<ul>
<li class="chapter" data-level="1.13.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#lists"><i class="fa fa-check"></i><b>1.13.1</b> Lists<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#revisiting-read_csv"><i class="fa fa-check"></i><b>1.14</b> Revisiting read_csv()<span></span></a></li>
<li class="chapter" data-level="1.15" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#thats-it"><i class="fa fa-check"></i><b>1.15</b> That’s it!<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html"><i class="fa fa-check"></i><b>2</b> Handling Data with the Tidyverse<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>2.1</b> Required<span></span></a></li>
<li class="chapter" data-level="2.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>2.2</b> Objective<span></span></a></li>
<li class="chapter" data-level="2.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-the-console"><i class="fa fa-check"></i><b>2.3</b> Using the Console<span></span></a></li>
<li class="chapter" data-level="2.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tidyverse-help-with-the-introverse"><i class="fa fa-check"></i><b>2.4</b> Tidyverse help with the Introverse<span></span></a></li>
<li class="chapter" data-level="2.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#basic-tidyverse-commands"><i class="fa fa-check"></i><b>2.5</b> Basic tidyverse commands<span></span></a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select"><i class="fa fa-check"></i><b>2.5.1</b> select()<span></span></a></li>
<li class="chapter" data-level="2.5.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise"><i class="fa fa-check"></i><b>2.5.2</b> summarise()<span></span></a></li>
<li class="chapter" data-level="2.5.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#filter"><i class="fa fa-check"></i><b>2.5.3</b> filter()<span></span></a></li>
<li class="chapter" data-level="2.5.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#group_by"><i class="fa fa-check"></i><b>2.5.4</b> group_by()<span></span></a></li>
<li class="chapter" data-level="2.5.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate"><i class="fa fa-check"></i><b>2.5.5</b> mutate()<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#advanced-tidyverse-commands"><i class="fa fa-check"></i><b>2.6</b> Advanced tidyverse commands<span></span></a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select-1"><i class="fa fa-check"></i><b>2.6.1</b> select()<span></span></a></li>
<li class="chapter" data-level="2.6.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise-1"><i class="fa fa-check"></i><b>2.6.2</b> summarise()<span></span></a></li>
<li class="chapter" data-level="2.6.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate-1"><i class="fa fa-check"></i><b>2.6.3</b> mutate()<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-help"><i class="fa fa-check"></i><b>2.7</b> Using help<span></span></a></li>
<li class="chapter" data-level="2.8" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#base-r-vs-tidyverse"><i class="fa fa-check"></i><b>2.8</b> Base R vs tidyverse<span></span></a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tibbles-vs.-data-frames"><i class="fa fa-check"></i><b>2.8.1</b> Tibbles vs. data frames<span></span></a></li>
<li class="chapter" data-level="2.8.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read.csv-and-data-frames"><i class="fa fa-check"></i><b>2.8.2</b> read.csv() and data frames<span></span></a></li>
<li class="chapter" data-level="2.8.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read_csv-and-tibbles"><i class="fa fa-check"></i><b>2.8.3</b> read_csv() and tibbles<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html"><i class="fa fa-check"></i><b>3</b> Week 2 Friday Workshop<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#required-packages"><i class="fa fa-check"></i><b>3.1</b> Required Packages<span></span></a></li>
<li class="chapter" data-level="3.2" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#goals"><i class="fa fa-check"></i><b>3.2</b> Goals<span></span></a></li>
<li class="chapter" data-level="3.3" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#data-and-column-names"><i class="fa fa-check"></i><b>3.3</b> Data and column names<span></span></a></li>
<li class="chapter" data-level="3.4" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#install-packages"><i class="fa fa-check"></i><b>3.4</b> Install packages<span></span></a></li>
<li class="chapter" data-level="3.5" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#rstudio-project"><i class="fa fa-check"></i><b>3.5</b> RStudio Project<span></span></a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#make-a-script"><i class="fa fa-check"></i><b>3.5.1</b> Make a script<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#loading-data"><i class="fa fa-check"></i><b>3.6</b> Loading data<span></span></a></li>
<li class="chapter" data-level="3.7" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#clean-and-screen-the-data"><i class="fa fa-check"></i><b>3.7</b> Clean and screen the data<span></span></a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#numeric-screening"><i class="fa fa-check"></i><b>3.7.1</b> Numeric screening<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#flipping-responses-to-reverse-key-items"><i class="fa fa-check"></i><b>3.8</b> Flipping responses to reverse-key items<span></span></a></li>
<li class="chapter" data-level="3.9" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#making-scale-scores"><i class="fa fa-check"></i><b>3.9</b> Making scale scores<span></span></a></li>
<li class="chapter" data-level="3.10" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#descriptive-statistics-for-scale-scores"><i class="fa fa-check"></i><b>3.10</b> Descriptive statistics for scale scores<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html"><i class="fa fa-check"></i><b>4</b> Week 3 Friday Workshop<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#required-packages-1"><i class="fa fa-check"></i><b>4.1</b> Required Packages<span></span></a></li>
<li class="chapter" data-level="4.2" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#goals-1"><i class="fa fa-check"></i><b>4.2</b> Goals<span></span></a></li>
<li class="chapter" data-level="4.3" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#data-and-column-names-1"><i class="fa fa-check"></i><b>4.3</b> Data and column names<span></span></a></li>
<li class="chapter" data-level="4.4" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#install-packages-1"><i class="fa fa-check"></i><b>4.4</b> Install packages<span></span></a></li>
<li class="chapter" data-level="4.5" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#rstudio-project-1"><i class="fa fa-check"></i><b>4.5</b> RStudio Project<span></span></a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#make-a-script-1"><i class="fa fa-check"></i><b>4.5.1</b> Make a script<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#week-2-catchup"><i class="fa fa-check"></i><b>4.6</b> Week 2 Catchup<span></span></a></li>
<li class="chapter" data-level="4.7" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#creating-compositescale-scores"><i class="fa fa-check"></i><b>4.7</b> Creating composite/scale scores<span></span></a></li>
<li class="chapter" data-level="4.8" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-scale-scores"><i class="fa fa-check"></i><b>4.8</b> Variance of scale scores<span></span></a></li>
<li class="chapter" data-level="4.9" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-items"><i class="fa fa-check"></i><b>4.9</b> Variance of items<span></span></a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#approach-1"><i class="fa fa-check"></i><b>4.9.1</b> Approach 1<span></span></a></li>
<li class="chapter" data-level="4.9.2" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#approach-2"><i class="fa fa-check"></i><b>4.9.2</b> Approach 2<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-affect_sum-column"><i class="fa fa-check"></i><b>4.10</b> Variance of affect_sum column<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html"><i class="fa fa-check"></i><b>5</b> Week 4 Friday Workshop<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#required-packagess"><i class="fa fa-check"></i><b>5.1</b> Required Packagess<span></span></a></li>
<li class="chapter" data-level="5.2" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#goals-2"><i class="fa fa-check"></i><b>5.2</b> Goals<span></span></a></li>
<li class="chapter" data-level="5.3" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#install-packages-2"><i class="fa fa-check"></i><b>5.3</b> Install packages<span></span></a></li>
<li class="chapter" data-level="5.4" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#rstudio-project-2"><i class="fa fa-check"></i><b>5.4</b> RStudio Project<span></span></a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#make-a-script-2"><i class="fa fa-check"></i><b>5.4.1</b> Make a script<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#code-catchup"><i class="fa fa-check"></i><b>5.5</b> Code Catchup<span></span></a></li>
<li class="chapter" data-level="5.6" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#reliability"><i class="fa fa-check"></i><b>5.6</b> Reliability<span></span></a></li>
<li class="chapter" data-level="5.7" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#big-picture-for-today"><i class="fa fa-check"></i><b>5.7</b> Big picture for today<span></span></a></li>
<li class="chapter" data-level="5.8" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#cronbachs-alpha"><i class="fa fa-check"></i><b>5.8</b> Cronbach’s Alpha<span></span></a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#alpha-via-covariance-matrix"><i class="fa fa-check"></i><b>5.8.1</b> Alpha via covariance matrix<span></span></a></li>
<li class="chapter" data-level="5.8.2" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#alpha-via-psych-package"><i class="fa fa-check"></i><b>5.8.2</b> Alpha via psych package<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#standardized-alpha"><i class="fa fa-check"></i><b>5.9</b> Standardized Alpha<span></span></a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#standardized-alpha-via-correlation-matrix"><i class="fa fa-check"></i><b>5.9.1</b> Standardized Alpha via correlation matrix<span></span></a></li>
<li class="chapter" data-level="5.9.2" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#standardized-alpha-via-psych-package"><i class="fa fa-check"></i><b>5.9.2</b> Standardized Alpha via psych package<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#walk-away"><i class="fa fa-check"></i><b>5.10</b> Walk away<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html"><i class="fa fa-check"></i><b>6</b> Week 5 Friday Workshop<span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#required-packagess-1"><i class="fa fa-check"></i><b>6.1</b> Required Packagess<span></span></a></li>
<li class="chapter" data-level="6.2" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#goals-3"><i class="fa fa-check"></i><b>6.2</b> Goals<span></span></a></li>
<li class="chapter" data-level="6.3" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#rstudio-project-3"><i class="fa fa-check"></i><b>6.3</b> RStudio Project<span></span></a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#make-a-script-3"><i class="fa fa-check"></i><b>6.3.1</b> Make a script<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#loading-data-1"><i class="fa fa-check"></i><b>6.4</b> Loading data<span></span></a></li>
<li class="chapter" data-level="6.5" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#true-scores-and-errors"><i class="fa fa-check"></i><b>6.5</b> True scores and errors<span></span></a></li>
<li class="chapter" data-level="6.6" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#observed-scores"><i class="fa fa-check"></i><b>6.6</b> Observed scores<span></span></a></li>
<li class="chapter" data-level="6.7" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#column-variances"><i class="fa fa-check"></i><b>6.7</b> Column variances<span></span></a></li>
<li class="chapter" data-level="6.8" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#observed-score-variance"><i class="fa fa-check"></i><b>6.8</b> Observed score variance<span></span></a></li>
<li class="chapter" data-level="6.9" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#true-score-variance"><i class="fa fa-check"></i><b>6.9</b> True score variance<span></span></a></li>
<li class="chapter" data-level="6.10" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#variance-random-measurement-errors"><i class="fa fa-check"></i><b>6.10</b> Variance random measurement errors<span></span></a></li>
<li class="chapter" data-level="6.11" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#variance-sum-rule"><i class="fa fa-check"></i><b>6.11</b> Variance sum rule<span></span></a></li>
<li class="chapter" data-level="6.12" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#reliability-1"><i class="fa fa-check"></i><b>6.12</b> Reliability<span></span></a>
<ul>
<li class="chapter" data-level="6.12.1" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#approach-1-true-score-variance"><i class="fa fa-check"></i><b>6.12.1</b> Approach 1: True score variance<span></span></a></li>
<li class="chapter" data-level="6.12.2" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#approach-2-error-variance"><i class="fa fa-check"></i><b>6.12.2</b> Approach 2: Error variance<span></span></a></li>
<li class="chapter" data-level="6.12.3" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#approach-3-correlation-trueobserved"><i class="fa fa-check"></i><b>6.12.3</b> Approach 3: Correlation true/observed<span></span></a></li>
<li class="chapter" data-level="6.12.4" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#approach-4-correlation-errorobserved"><i class="fa fa-check"></i><b>6.12.4</b> Approach 4: Correlation error/observed<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.13" data-path="week-5-friday-workshop.html"><a href="week-5-friday-workshop.html#recap"><i class="fa fa-check"></i><b>6.13</b> Recap<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="weeks-67-friday-workshops.html"><a href="weeks-67-friday-workshops.html"><i class="fa fa-check"></i><b>7</b> Weeks 6/7 Friday Workshops<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="weeks-67-friday-workshops.html"><a href="weeks-67-friday-workshops.html#deductive-scale-construction"><i class="fa fa-check"></i><b>7.1</b> Deductive scale construction<span></span></a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="weeks-67-friday-workshops.html"><a href="weeks-67-friday-workshops.html#impulsivity-example"><i class="fa fa-check"></i><b>7.1.1</b> Impulsivity example<span></span></a></li>
<li class="chapter" data-level="7.1.2" data-path="weeks-67-friday-workshops.html"><a href="weeks-67-friday-workshops.html#affective-commitment-example"><i class="fa fa-check"></i><b>7.1.2</b> Affective commitment example<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="weeks-67-friday-workshops.html"><a href="weeks-67-friday-workshops.html#definition-review-of-the-literature"><i class="fa fa-check"></i><b>7.2</b> Definition review of the literature<span></span></a></li>
<li class="chapter" data-level="7.3" data-path="weeks-67-friday-workshops.html"><a href="weeks-67-friday-workshops.html#creating-your-own-definition"><i class="fa fa-check"></i><b>7.3</b> Creating your own definition<span></span></a></li>
<li class="chapter" data-level="7.4" data-path="weeks-67-friday-workshops.html"><a href="weeks-67-friday-workshops.html#writing-items"><i class="fa fa-check"></i><b>7.4</b> Writing items<span></span></a></li>
<li class="chapter" data-level="7.5" data-path="weeks-67-friday-workshops.html"><a href="weeks-67-friday-workshops.html#item-submission"><i class="fa fa-check"></i><b>7.5</b> Item submission<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html"><i class="fa fa-check"></i><b>8</b> Week 9 Friday Workshop<span></span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#required-packages-2"><i class="fa fa-check"></i><b>8.1</b> Required Packages<span></span></a></li>
<li class="chapter" data-level="8.2" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#goals-4"><i class="fa fa-check"></i><b>8.2</b> Goals<span></span></a></li>
<li class="chapter" data-level="8.3" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#create-a-project"><i class="fa fa-check"></i><b>8.3</b> Create a project<span></span></a></li>
<li class="chapter" data-level="8.4" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#activate-the-packages"><i class="fa fa-check"></i><b>8.4</b> Activate the packages<span></span></a></li>
<li class="chapter" data-level="8.5" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#load-your-data-raw-data"><i class="fa fa-check"></i><b>8.5</b> Load your data raw data<span></span></a></li>
<li class="chapter" data-level="8.6" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#make-analytic-data"><i class="fa fa-check"></i><b>8.6</b> Make analytic data<span></span></a></li>
<li class="chapter" data-level="8.7" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#flipping-responses-to-reverse-key-items-1"><i class="fa fa-check"></i><b>8.7</b> Flipping responses to reverse-key items<span></span></a></li>
<li class="chapter" data-level="8.8" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#item-descriptive-statistics-and-correlations"><i class="fa fa-check"></i><b>8.8</b> Item descriptive statistics and correlations<span></span></a></li>
<li class="chapter" data-level="8.9" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#initial-cronbachs-alpha"><i class="fa fa-check"></i><b>8.9</b> Initial Cronbach’s Alpha<span></span></a></li>
<li class="chapter" data-level="8.10" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#create-item-reliablity-index"><i class="fa fa-check"></i><b>8.10</b> Create “Item-Reliablity Index”<span></span></a></li>
<li class="chapter" data-level="8.11" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#sorting-by-item-reliability-index"><i class="fa fa-check"></i><b>8.11</b> Sorting by item-reliability index<span></span></a></li>
<li class="chapter" data-level="8.12" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#creating-the-final-scale"><i class="fa fa-check"></i><b>8.12</b> Creating the final scale<span></span></a>
<ul>
<li class="chapter" data-level="8.12.1" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#calculate-alpha-for-final-scale"><i class="fa fa-check"></i><b>8.12.1</b> Calculate Alpha for final scale<span></span></a></li>
<li class="chapter" data-level="8.12.2" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#obtain-scale-scores"><i class="fa fa-check"></i><b>8.12.2</b> Obtain scale scores<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.13" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#final-scores-range-of-values"><i class="fa fa-check"></i><b>8.13</b> Final scores: Range of values<span></span></a></li>
<li class="chapter" data-level="8.14" data-path="week-9-friday-workshop.html"><a href="week-9-friday-workshop.html#graphing-final-scores"><i class="fa fa-check"></i><b>8.14</b> Graphing final scores<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="notation.html"><a href="notation.html"><i class="fa fa-check"></i><b>9</b> Notation<span></span></a>
<ul>
<li class="chapter" data-level="9.1" data-path="notation.html"><a href="notation.html#measurement-notation"><i class="fa fa-check"></i><b>9.1</b> Measurement Notation<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="scaling.html"><a href="scaling.html"><i class="fa fa-check"></i><b>10</b> Scaling<span></span></a>
<ul>
<li class="chapter" data-level="10.1" data-path="scaling.html"><a href="scaling.html#data-entry"><i class="fa fa-check"></i><b>10.1</b> Data entry<span></span></a></li>
<li class="chapter" data-level="10.2" data-path="scaling.html"><a href="scaling.html#loading-data-2"><i class="fa fa-check"></i><b>10.2</b> Loading data<span></span></a></li>
<li class="chapter" data-level="10.3" data-path="scaling.html"><a href="scaling.html#viewing-data"><i class="fa fa-check"></i><b>10.3</b> Viewing data<span></span></a></li>
<li class="chapter" data-level="10.4" data-path="scaling.html"><a href="scaling.html#summary-statistics"><i class="fa fa-check"></i><b>10.4</b> Summary statistics<span></span></a></li>
<li class="chapter" data-level="10.5" data-path="scaling.html"><a href="scaling.html#converting-units"><i class="fa fa-check"></i><b>10.5</b> Converting units<span></span></a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="scaling.html"><a href="scaling.html#inches"><i class="fa fa-check"></i><b>10.5.1</b> Inches<span></span></a></li>
<li class="chapter" data-level="10.5.2" data-path="scaling.html"><a href="scaling.html#z-scores"><i class="fa fa-check"></i><b>10.5.2</b> <em>z</em>-scores<span></span></a></li>
<li class="chapter" data-level="10.5.3" data-path="scaling.html"><a href="scaling.html#t-scores"><i class="fa fa-check"></i><b>10.5.3</b> T-scores<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="scaling.html"><a href="scaling.html#frame-of-references"><i class="fa fa-check"></i><b>10.6</b> Frame of references<span></span></a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="scaling.html"><a href="scaling.html#all-participants"><i class="fa fa-check"></i><b>10.6.1</b> All participants<span></span></a></li>
<li class="chapter" data-level="10.6.2" data-path="scaling.html"><a href="scaling.html#male-reference"><i class="fa fa-check"></i><b>10.6.2</b> Male reference<span></span></a></li>
<li class="chapter" data-level="10.6.3" data-path="scaling.html"><a href="scaling.html#canadian-reference"><i class="fa fa-check"></i><b>10.6.3</b> Canadian reference<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="scaling.html"><a href="scaling.html#summary-4"><i class="fa fa-check"></i><b>10.7</b> Summary<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="percentiles.html"><a href="percentiles.html"><i class="fa fa-check"></i><b>11</b> Percentiles<span></span></a>
<ul>
<li class="chapter" data-level="11.1" data-path="percentiles.html"><a href="percentiles.html#assuming-a-normal-distribution-approach"><i class="fa fa-check"></i><b>11.1</b> Assuming a normal distribution approach<span></span></a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="percentiles.html"><a href="percentiles.html#a-single-case"><i class="fa fa-check"></i><b>11.1.1</b> A single case<span></span></a></li>
<li class="chapter" data-level="11.1.2" data-path="percentiles.html"><a href="percentiles.html#many-cases-using-r"><i class="fa fa-check"></i><b>11.1.2</b> Many cases using R<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="percentiles.html"><a href="percentiles.html#assumption-free-approach"><i class="fa fa-check"></i><b>11.2</b> Assumption free approach<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>12</b> Graphing<span></span></a>
<ul>
<li class="chapter" data-level="12.1" data-path="graphing.html"><a href="graphing.html#required-1"><i class="fa fa-check"></i><b>12.1</b> Required<span></span></a></li>
<li class="chapter" data-level="12.2" data-path="graphing.html"><a href="graphing.html#data"><i class="fa fa-check"></i><b>12.2</b> Data<span></span></a></li>
<li class="chapter" data-level="12.3" data-path="graphing.html"><a href="graphing.html#graph-basics"><i class="fa fa-check"></i><b>12.3</b> Graph basics<span></span></a></li>
<li class="chapter" data-level="12.4" data-path="graphing.html"><a href="graphing.html#graphing-efficiently"><i class="fa fa-check"></i><b>12.4</b> Graphing efficiently<span></span></a></li>
<li class="chapter" data-level="12.5" data-path="graphing.html"><a href="graphing.html#aesthetics"><i class="fa fa-check"></i><b>12.5</b> Aesthetics<span></span></a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="graphing.html"><a href="graphing.html#fill-color"><i class="fa fa-check"></i><b>12.5.1</b> Fill color<span></span></a></li>
<li class="chapter" data-level="12.5.2" data-path="graphing.html"><a href="graphing.html#overriding-aes"><i class="fa fa-check"></i><b>12.5.2</b> Overriding aes()<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="graphing.html"><a href="graphing.html#apa-style"><i class="fa fa-check"></i><b>12.6</b> APA style<span></span></a></li>
<li class="chapter" data-level="12.7" data-path="graphing.html"><a href="graphing.html#axes"><i class="fa fa-check"></i><b>12.7</b> Axes<span></span></a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="graphing.html"><a href="graphing.html#range"><i class="fa fa-check"></i><b>12.7.1</b> Range<span></span></a></li>
<li class="chapter" data-level="12.7.2" data-path="graphing.html"><a href="graphing.html#ticks"><i class="fa fa-check"></i><b>12.7.2</b> Ticks<span></span></a></li>
<li class="chapter" data-level="12.7.3" data-path="graphing.html"><a href="graphing.html#labels"><i class="fa fa-check"></i><b>12.7.3</b> Labels<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="graphing.html"><a href="graphing.html#axis-values"><i class="fa fa-check"></i><b>12.8</b> Axis values<span></span></a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="graphing.html"><a href="graphing.html#text"><i class="fa fa-check"></i><b>12.8.1</b> Text<span></span></a></li>
<li class="chapter" data-level="12.8.2" data-path="graphing.html"><a href="graphing.html#angle"><i class="fa fa-check"></i><b>12.8.2</b> Angle<span></span></a></li>
<li class="chapter" data-level="12.8.3" data-path="graphing.html"><a href="graphing.html#alignment"><i class="fa fa-check"></i><b>12.8.3</b> Alignment<span></span></a></li>
<li class="chapter" data-level="12.8.4" data-path="graphing.html"><a href="graphing.html#order"><i class="fa fa-check"></i><b>12.8.4</b> Order<span></span></a></li>
<li class="chapter" data-level="12.8.5" data-path="graphing.html"><a href="graphing.html#legend-order"><i class="fa fa-check"></i><b>12.8.5</b> Legend order<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="graphing.html"><a href="graphing.html#custom-colours"><i class="fa fa-check"></i><b>12.9</b> Custom colours<span></span></a>
<ul>
<li class="chapter" data-level="12.9.1" data-path="graphing.html"><a href="graphing.html#r-palette"><i class="fa fa-check"></i><b>12.9.1</b> R palette<span></span></a></li>
<li class="chapter" data-level="12.9.2" data-path="graphing.html"><a href="graphing.html#hex-colours"><i class="fa fa-check"></i><b>12.9.2</b> Hex colours<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12.10" data-path="graphing.html"><a href="graphing.html#emoji"><i class="fa fa-check"></i><b>12.10</b> Emoji<span></span></a></li>
<li class="chapter" data-level="12.11" data-path="graphing.html"><a href="graphing.html#accessible-colors"><i class="fa fa-check"></i><b>12.11</b> Accessible Colors<span></span></a>
<ul>
<li class="chapter" data-level="12.11.1" data-path="graphing.html"><a href="graphing.html#rcolorbrewer"><i class="fa fa-check"></i><b>12.11.1</b> RColorBrewer<span></span></a></li>
<li class="chapter" data-level="12.11.2" data-path="graphing.html"><a href="graphing.html#avoid-color"><i class="fa fa-check"></i><b>12.11.2</b> Avoid color<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12.12" data-path="graphing.html"><a href="graphing.html#saving"><i class="fa fa-check"></i><b>12.12</b> Saving<span></span></a>
<ul>
<li class="chapter" data-level="12.12.1" data-path="graphing.html"><a href="graphing.html#mac-1"><i class="fa fa-check"></i><b>12.12.1</b> MAC<span></span></a></li>
<li class="chapter" data-level="12.12.2" data-path="graphing.html"><a href="graphing.html#pc-or-mac"><i class="fa fa-check"></i><b>12.12.2</b> PC or MAC<span></span></a></li>
</ul></li>
</ul></li>
<li><a href="references.html#references">References<span></span></a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Welcome!</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="handling-data-with-the-tidyverse" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Handling Data with the Tidyverse<a href="handling-data-with-the-tidyverse.html#handling-data-with-the-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>A key component of doing statistics in the modern world is managing/wrangling or cleaning data to make it ready for analysis. Indeed, some estimate that those who do data science spend 80% of their time engaged in cleaning data. Although this specific percentage <a href="https://blog.ldodds.com/2020/01/31/do-data-scientists-spend-80-of-their-time-cleaning-data-turns-out-no/">may not be accurate</a> it does accurately reflect the fact that data scientists do spend a substantial portion of their time preparing data for analysis. Many complain about this fact but as <a href="https://blog.ldodds.com/2020/01/31/do-data-scientists-spend-80-of-their-time-cleaning-data-turns-out-no/">Leigh Dodds</a> points out “I would argue that spending time working with data. To transform, explore and understand it better is absolutely what data scientists should be doing. This is the medium they are working in.”</p>
<p>In this chapter we focus on teaching you foundational skills for data preparation. The skills taught in this chapter largely revolve around using the tidyverse packages to manage data that will eventually help with data cleaning in the <a href="https://dstanley4.github.io/psyc6060bookdown/an-emphasis-on-workflow.html">Workflow</a> and <a href="https://dstanley4.github.io/psyc6060bookdown/qualtrics.html">Qualtrics</a> chapters. There are some additional resources you may want to consult as you learn these tidyverse skills:</p>
<ul>
<li><p><a href="https://r4ds.had.co.nz">R for Data Science book</a>. This is an excellent free online book! But it does reflect an exploratory analysis mindset compared to the confirmatory mindset we typically use in Psychological science.</p></li>
<li><p>You may find a <a href="https://www.rstudio.com/resources/cheatsheets/">cheatsheet</a> helpful. Specifically, the <a href="https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf">Data Transformation</a> cheatsheet.</p></li>
<li><p><a href="https://www.tidyverse.org">tidyverse website</a></p></li>
</ul>
<div id="required" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Required<a href="handling-data-with-the-tidyverse.html#required" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The data files below are used in this chapter. Right click to save each file.</p>
<table>
<thead>
<tr class="header">
<th>Required Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="data_okcupid.csv">data_okcupid.csv</a></td>
</tr>
<tr class="even">
<td><a href="data_experiment.csv">data_experiment.csv</a></td>
</tr>
</tbody>
</table>
<p>The following CRAN packages must be installed:</p>
<table>
<thead>
<tr class="header">
<th>Required CRAN Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tidyverse</td>
</tr>
<tr class="even">
<td>remotes</td>
</tr>
</tbody>
</table>
<p>The following GitHub package must be installed:</p>
<table>
<thead>
<tr class="header">
<th>Required GitHub Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>spielmanlab/introverse</td>
</tr>
</tbody>
</table>
<p>After the remotes package is installed, it can be used to install the introverse package from GitHub (an alternative “App Store”). If you get asked if you would like to install more recent versions of packages on your machine press “1” and Return to indicate “All” (if you are asked, you may not be).</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="handling-data-with-the-tidyverse.html#cb57-1" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;spielmanlab/introverse&quot;</span>)</span></code></pre></div>
</div>
<div id="objective" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Objective<a href="handling-data-with-the-tidyverse.html#objective" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The objective of this chapter is to familiarize you with some key commands in the tidyverse. These commands are used in isolation of each other for the most part. In the next chapter we will use these commands in a more coordinated way as we load a data set and move it from raw data to data that is ready for analysis (i.e., analytic data). You can start this project by Starting the class assignment on R Studio Cloud that corresponds to the chapter name.</p>
</div>
<div id="using-the-console" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Using the Console<a href="handling-data-with-the-tidyverse.html#using-the-console" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>All of the commands in this chapter should be typed into the Console within R. If you see a command split over multiple lines, use SHIFT-RETURN (macOS) or SHIFT-ENTER (Windows) to move the next line that is part of the same command.</p>
</div>
<div id="tidyverse-help-with-the-introverse" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Tidyverse help with the Introverse<a href="handling-data-with-the-tidyverse.html#tidyverse-help-with-the-introverse" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <strong>introverse</strong> package is just additional documentation that is helpful for beginners - until you learn to read the standard R documentation. The first command we will use in this chapter is the <strong>read_csv()</strong> command. You get the standard R help for this command using the code below in the R Console:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="handling-data-with-the-tidyverse.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># this actives the tidyverse commands</span></span>
<span id="cb58-2"><a href="handling-data-with-the-tidyverse.html#cb58-2" aria-hidden="true" tabindex="-1"></a>?read_csv</span></code></pre></div>
<p>This gives you help that looks like this:</p>
<p><img src="ch_tidy_intro/images/screenshot_R_help.png" width="70%" /></p>
<p>But you can obtain the better introverse documentation by typing the code below in the R Console:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="handling-data-with-the-tidyverse.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(introverse) <span class="co"># this actives the intoverse help</span></span>
<span id="cb59-2"><a href="handling-data-with-the-tidyverse.html#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_help</span>(<span class="st">&quot;read_csv&quot;</span>)</span></code></pre></div>
<p>This gives you help that looks like this:</p>
<p><img src="ch_tidy_intro/images/screenshot_introverse_help.png" width="70%" /></p>
<p>Most importantly, when you scroll down on the introverse help pages - it gives you code examples that are easy to follow. If at any point during this course you want more information about how a command works use the introverse get_help() command.</p>
<p>The get_help() command is especially valuable because it tells you which package (of the many tidyverse packages) a particular command comes from. For example, you can see the read_csv() command is from the readr package when you inspect the introverse help above.</p>
</div>
<div id="basic-tidyverse-commands" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Basic tidyverse commands<a href="handling-data-with-the-tidyverse.html#basic-tidyverse-commands" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If you inspect the Files tab on the lower-right panel in R Studio you will see the file data_okcupid.csv. The code below loads that file. Recall you should type this code into the R Console.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="handling-data-with-the-tidyverse.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb60-2"><a href="handling-data-with-the-tidyverse.html#cb60-2" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data_okcupid.csv&quot;</span>)</span></code></pre></div>
<p>You can see the first few rows of the data using the print() command. Each row presents a person whereas each column represents a variable. If you have a large number of columns you will only see the first several columns with this approach to viewing your data.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="handling-data-with-the-tidyverse.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(okcupid_profiles)</span></code></pre></div>
<pre><code>## # A tibble: 59,946 × 6
##      age diet              height pets          sex   status
##    &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt; &lt;chr&gt; 
##  1    22 strictly anything     75 likes dogs a… m     single
##  2    35 mostly other          70 likes dogs a… m     single
##  3    38 anything              68 has cats      m     avail…
##  4    23 vegetarian            71 likes cats    m     single
##  5    29 &lt;NA&gt;                  66 likes dogs a… m     single
##  6    29 mostly anything       67 likes cats    m     single
##  7    32 strictly anything     65 likes dogs a… f     single
##  8    31 mostly anything       65 likes dogs a… f     single
##  9    24 strictly anything     67 likes dogs a… f     single
## 10    37 mostly anything       65 likes dogs a… m     single
## # … with 59,936 more rows</code></pre>
<p>But it’s also helpful just to see a list of the columns in the data with the glimpse() command:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="handling-data-with-the-tidyverse.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(okcupid_profiles)</span></code></pre></div>
<pre><code>## Rows: 59,946
## Columns: 6
## $ age    &lt;dbl&gt; 22, 35, 38, 23, 29, 29, 32, 31, 24, 37, 35,…
## $ diet   &lt;chr&gt; &quot;strictly anything&quot;, &quot;mostly other&quot;, &quot;anyth…
## $ height &lt;dbl&gt; 75, 70, 68, 71, 66, 67, 65, 65, 67, 65, 70,…
## $ pets   &lt;chr&gt; &quot;likes dogs and likes cats&quot;, &quot;likes dogs an…
## $ sex    &lt;chr&gt; &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;…
## $ status &lt;chr&gt; &quot;single&quot;, &quot;single&quot;, &quot;available&quot;, &quot;single&quot;, …</code></pre>
<p>The glimpse() command is useful because it quickly allows you to see all of the columns. Moreover, it allows you to see the type for each column. Types were briefly discussed in the last chapter. Notice in the output beside each column name that some columns are labeled “dbl” which is short for double – a type of numeric column. Other columns are labeled “chr” which is short for character - meaning the columns contain characters. These designations will become important in the next chapter as we prepare data for analysis.</p>
<div id="select" class="section level3 hasAnchor" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> select()<a href="handling-data-with-the-tidyverse.html#select" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The select() command allows you to obtain a subset of the columns in your data. The commands below can be used to obtain the age and height columns. You can read the command as: take the okcupid_profiles data and then select the age and height columns. The “%&gt;%” symbol can be read as “and then”. You can see that this code prints out the data with just the age and height columns. Remember, use SHIFT-ENTER or SHIFT-RETURN to move to the next line in the block of code.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="handling-data-with-the-tidyverse.html#cb65-1" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="handling-data-with-the-tidyverse.html#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, height)</span></code></pre></div>
<pre><code>## # A tibble: 59,946 × 2
##      age height
##    &lt;dbl&gt;  &lt;dbl&gt;
##  1    22     75
##  2    35     70
##  3    38     68
##  4    23     71
##  5    29     66
##  6    29     67
##  7    32     65
##  8    31     65
##  9    24     67
## 10    37     65
## # … with 59,936 more rows</code></pre>
<p>Of course, it’s usually of little help to just print the subset of the data. It’s better to store it in a new data. In the command below we store the resulting data in a new data set called new_data.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="handling-data-with-the-tidyverse.html#cb67-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> okcupid_profiles <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="handling-data-with-the-tidyverse.html#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, height)</span></code></pre></div>
<p>The glimpse() command shows us that only the age and height columns are in new_data.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="handling-data-with-the-tidyverse.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(new_data)</span></code></pre></div>
<pre><code>## Rows: 59,946
## Columns: 2
## $ age    &lt;dbl&gt; 22, 35, 38, 23, 29, 29, 32, 31, 24, 37, 35,…
## $ height &lt;dbl&gt; 75, 70, 68, 71, 66, 67, 65, 65, 67, 65, 70,…</code></pre>
<p>In the above example we indicated the columns we wanted to retain from the okcupid_profiles data using the select() command. However, we can also indicate the columns we want to drop from okcupid_profiles using a minus sign (-) in front of the columns we specify in the select() command.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="handling-data-with-the-tidyverse.html#cb70-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> okcupid_profiles <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>age, <span class="sc">-</span>height)</span></code></pre></div>
<p>The glimpse() command shows us that we kept all the columns except the age and height columns when we created new_data.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="handling-data-with-the-tidyverse.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(new_data)</span></code></pre></div>
<pre><code>## Rows: 59,946
## Columns: 4
## $ diet   &lt;chr&gt; &quot;strictly anything&quot;, &quot;mostly other&quot;, &quot;anyth…
## $ pets   &lt;chr&gt; &quot;likes dogs and likes cats&quot;, &quot;likes dogs an…
## $ sex    &lt;chr&gt; &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;…
## $ status &lt;chr&gt; &quot;single&quot;, &quot;single&quot;, &quot;available&quot;, &quot;single&quot;, …</code></pre>
</div>
<div id="summarise" class="section level3 hasAnchor" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> summarise()<a href="handling-data-with-the-tidyverse.html#summarise" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The summarise() command can be used to generate descriptive statistics for a specified column. You can easily calculate column descriptive statistics using the corresponding commands for mean(), sd(), min(), max(), among others. In the example below we calculate the mean for the age column.</p>
<p>In the code below, mean(age, na.rm = TRUE), indicates to R that it should calculate the mean of the age column. The na.rm indicates how missing values should be handled. The na stands for not available; in R missing values are classified as Not Available or NA. The rm stands for remove. Consequently, na.rm is asking: “Should we remove missing values when calculating the mean?” The TRUE indicates that yes, missing values should be removed when calculating the mean. The result of this calculation is placed into a variable labelled age_mean, though we could have used any label we wanted instead of age_mean. We see that the mean of the age column is, with rounding, 32.3.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="handling-data-with-the-tidyverse.html#cb73-1" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="sc">%&gt;%</span> </span>
<span id="cb73-2"><a href="handling-data-with-the-tidyverse.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">age_mean =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   age_mean
##      &lt;dbl&gt;
## 1     32.3</code></pre>
<p>More than one calculation can occur in the same summarise() command. You can easily add the calculation for the standared deviation with the sd() command.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="handling-data-with-the-tidyverse.html#cb75-1" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="sc">%&gt;%</span> </span>
<span id="cb75-2"><a href="handling-data-with-the-tidyverse.html#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">age_mean =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb75-3"><a href="handling-data-with-the-tidyverse.html#cb75-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">age_sd =</span> <span class="fu">sd</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   age_mean age_sd
##      &lt;dbl&gt;  &lt;dbl&gt;
## 1     32.3   9.45</code></pre>
<p>Often this process does too much rounding. We can get more exact results by adding an as.data.frame() to the end of the commands.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="handling-data-with-the-tidyverse.html#cb77-1" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="sc">%&gt;%</span> </span>
<span id="cb77-2"><a href="handling-data-with-the-tidyverse.html#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">age_mean =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb77-3"><a href="handling-data-with-the-tidyverse.html#cb77-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">age_sd =</span> <span class="fu">sd</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb77-4"><a href="handling-data-with-the-tidyverse.html#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   age_mean age_sd
## 1    32.34  9.453</code></pre>
</div>
<div id="filter" class="section level3 hasAnchor" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> filter()<a href="handling-data-with-the-tidyverse.html#filter" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The filter() command allows you to obtain a subset of the rows in your data. In the example below we create a new data set with just the males from the original data.</p>
<p>Notice the structure of the original data below in the glimpse() output. There is a column called sex that uses m and f to indicate male and female, respectively. Also notice that there are 59946 rows in the okcupid_profiles data.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="handling-data-with-the-tidyverse.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(okcupid_profiles)</span></code></pre></div>
<pre><code>## Rows: 59,946
## Columns: 6
## $ age    &lt;dbl&gt; 22, 35, 38, 23, 29, 29, 32, 31, 24, 37, 35,…
## $ diet   &lt;chr&gt; &quot;strictly anything&quot;, &quot;mostly other&quot;, &quot;anyth…
## $ height &lt;dbl&gt; 75, 70, 68, 71, 66, 67, 65, 65, 67, 65, 70,…
## $ pets   &lt;chr&gt; &quot;likes dogs and likes cats&quot;, &quot;likes dogs an…
## $ sex    &lt;chr&gt; &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;f&quot;, &quot;f&quot;, &quot;f&quot;…
## $ status &lt;chr&gt; &quot;single&quot;, &quot;single&quot;, &quot;available&quot;, &quot;single&quot;, …</code></pre>
<p>We use the filter command to select a subset of the rows based on the content of any column. In this case the sex column is used to obtain a subset of the rows; the rows with the value “m” are obtained. Notice the double equals sign is used to indicate “equal to”. The reason a double equals sign is used here (instead of a single equals sign) is to distinguish it from the use of the single equals sign in the summarise command above. In the summarise command above, the single equal sign was used to indicate “assign to”. That is, assign to age_mean the mean of the column age after it is calculated. A single equals sign indicates “assign to” whereas a double equals sign indicates “is equal to”.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="handling-data-with-the-tidyverse.html#cb81-1" aria-hidden="true" tabindex="-1"></a>okcupid_males <span class="ot">&lt;-</span> okcupid_profiles <span class="sc">%&gt;%</span></span>
<span id="cb81-2"><a href="handling-data-with-the-tidyverse.html#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">&quot;m&quot;</span>)</span></code></pre></div>
<p>We use glimpse() to inspect these all male data. Notice that only the letter m is in the sex column - indicating only males are in the data set. Also notice that there are 35829 rows in the okcupid_males data - fewer people because males are a subset of the total number of rows.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="handling-data-with-the-tidyverse.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(okcupid_males)</span></code></pre></div>
<pre><code>## Rows: 35,829
## Columns: 6
## $ age    &lt;dbl&gt; 22, 35, 38, 23, 29, 29, 37, 35, 28, 24, 33,…
## $ diet   &lt;chr&gt; &quot;strictly anything&quot;, &quot;mostly other&quot;, &quot;anyth…
## $ height &lt;dbl&gt; 75, 70, 68, 71, 66, 67, 65, 70, 72, 72, 70,…
## $ pets   &lt;chr&gt; &quot;likes dogs and likes cats&quot;, &quot;likes dogs an…
## $ sex    &lt;chr&gt; &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;…
## $ status &lt;chr&gt; &quot;single&quot;, &quot;single&quot;, &quot;available&quot;, &quot;single&quot;, …</code></pre>
<p>The filter command can be combined with the summarise command to get the descriptive statistics for males without the hassle of creating new data. This is again done using the %&gt;% “and then” operator.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="handling-data-with-the-tidyverse.html#cb84-1" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="handling-data-with-the-tidyverse.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">&quot;m&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb84-3"><a href="handling-data-with-the-tidyverse.html#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">age_mean =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb84-4"><a href="handling-data-with-the-tidyverse.html#cb84-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">age_sd =</span> <span class="fu">sd</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   age_mean age_sd
##      &lt;dbl&gt;  &lt;dbl&gt;
## 1     32.0   9.03</code></pre>
<p>We see that for the 35829 males the mean age is 32.0 and the standard deviation is 9.0.</p>
<p>Likewise, we can obtain the descriptive statistics for females with only a slight modification, changing m to f in the filter command:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="handling-data-with-the-tidyverse.html#cb86-1" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="sc">%&gt;%</span></span>
<span id="cb86-2"><a href="handling-data-with-the-tidyverse.html#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">&quot;f&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-3"><a href="handling-data-with-the-tidyverse.html#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">age_mean =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb86-4"><a href="handling-data-with-the-tidyverse.html#cb86-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">age_sd =</span> <span class="fu">sd</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   age_mean age_sd
##      &lt;dbl&gt;  &lt;dbl&gt;
## 1     32.8   10.0</code></pre>
<p>We see that for the 24117 females the mean age is 32.8 and the standard deviation is 10.0.</p>
</div>
<div id="group_by" class="section level3 hasAnchor" number="2.5.4">
<h3><span class="header-section-number">2.5.4</span> group_by()<a href="handling-data-with-the-tidyverse.html#group_by" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The process we used with the filter command would quickly become onerous if we had many subgroups for a column. Consequently, it’s often better to use the group() command to calculate descriptive statistics for the levels (e.g., male/female) of a variable. By telling the computer to group_by() sex the summarise command is run separately for every level of sex (i.e., m and f).</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="handling-data-with-the-tidyverse.html#cb88-1" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="sc">%&gt;%</span></span>
<span id="cb88-2"><a href="handling-data-with-the-tidyverse.html#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb88-3"><a href="handling-data-with-the-tidyverse.html#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">age_mean =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb88-4"><a href="handling-data-with-the-tidyverse.html#cb88-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">age_sd =</span> <span class="fu">sd</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) </span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   sex   age_mean age_sd
##   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;
## 1 f         32.8  10.0 
## 2 m         32.0   9.03</code></pre>
<p>Fortunately, it’s possible to use more than one grouping variable with the group_by() command. In the code below we group by sex and status (i.e., dating status).</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="handling-data-with-the-tidyverse.html#cb90-1" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="sc">%&gt;%</span></span>
<span id="cb90-2"><a href="handling-data-with-the-tidyverse.html#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, status) <span class="sc">%&gt;%</span></span>
<span id="cb90-3"><a href="handling-data-with-the-tidyverse.html#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">age_mean =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb90-4"><a href="handling-data-with-the-tidyverse.html#cb90-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">age_sd =</span> <span class="fu">sd</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) </span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;sex&#39;. You can override
## using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 10 × 4
## # Groups:   sex [2]
##    sex   status         age_mean age_sd
##    &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;  &lt;dbl&gt;
##  1 f     available          32.2   8.54
##  2 f     married            33.7   8.13
##  3 f     seeing someone     28.1   6.44
##  4 f     single             33.0  10.2 
##  5 f     unknown            27.8   5.91
##  6 m     available          34.8   9.40
##  7 m     married            38.7  10.1 
##  8 m     seeing someone     30.8   7.06
##  9 m     single             31.9   9.04
## 10 m     unknown            40.7   8.87</code></pre>
<p>The resulting output provide for age the mean and standard deviation for every combination of sex and dating status. The first five rows provide output for females at every level of dating status whereas the subsequent five rows provide output for males at every level of dating status.</p>
</div>
<div id="mutate" class="section level3 hasAnchor" number="2.5.5">
<h3><span class="header-section-number">2.5.5</span> mutate()<a href="handling-data-with-the-tidyverse.html#mutate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The mutate() command can be used to calculate a new column in a data. In the example below we calculate a new column called age_centered which is the new version of the age_column where the mean of the column has been removed from every value. This is merely an example of the many different types of calculations we can perform to create a new column using mutate().</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="handling-data-with-the-tidyverse.html#cb93-1" aria-hidden="true" tabindex="-1"></a>okcupid_profiles <span class="ot">&lt;-</span> okcupid_profiles <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="handling-data-with-the-tidyverse.html#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_centered =</span> age <span class="sc">-</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<p>Notice that the glimpse() command reveals that after we use the mutate() command there is a new column called age_centered.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="handling-data-with-the-tidyverse.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(okcupid_profiles)</span></code></pre></div>
<pre><code>## Rows: 59,946
## Columns: 7
## $ age          &lt;dbl&gt; 22, 35, 38, 23, 29, 29, 32, 31, 24, 3…
## $ diet         &lt;chr&gt; &quot;strictly anything&quot;, &quot;mostly other&quot;, …
## $ height       &lt;dbl&gt; 75, 70, 68, 71, 66, 67, 65, 65, 67, 6…
## $ pets         &lt;chr&gt; &quot;likes dogs and likes cats&quot;, &quot;likes d…
## $ sex          &lt;chr&gt; &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;m&quot;, &quot;f&quot;, &quot;f…
## $ status       &lt;chr&gt; &quot;single&quot;, &quot;single&quot;, &quot;available&quot;, &quot;sin…
## $ age_centered &lt;dbl&gt; -10.3403, 2.6597, 5.6597, -9.3403, -3…</code></pre>
</div>
</div>
<div id="advanced-tidyverse-commands" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Advanced tidyverse commands<a href="handling-data-with-the-tidyverse.html#advanced-tidyverse-commands" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this advanced selection we revisit the commands from the basic tidyverse section but use more complicated code to either select or apply an action to more than one column at a time. We will indicate the columns that we want to select or apply an action to using: starts_with(), ends_with(), contains(), matches(), or where(). The first four of these are used to indicate columns based on column names. In contrast, the last command, where(), is used to indicate the columns based on the column type (numeric, character, factor, etc.).</p>
<p>We will review all five commands for indicating the columns we want in the select() selection below. Following that we will, for brevity, typically use only one of the five commands when illustrating how they work with summarise() and mutate().</p>
<p>We begin by loading a new data.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="handling-data-with-the-tidyverse.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb96-2"><a href="handling-data-with-the-tidyverse.html#cb96-2" aria-hidden="true" tabindex="-1"></a>data_exp <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data_experiment.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 6 Columns: 6
## ── Column specification ────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (1): sex
## dbl (5): id, t1_vomit, t1_aggression, t2_vomit, t2_aggre...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>The glimpse() command reveals that this is a small data set where every row represents one rat. The sex of the rat is recorded as well as, for each of two time points, a rating of vomiting and aggression.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="handling-data-with-the-tidyverse.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_exp)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 6
## $ id            &lt;dbl&gt; 1, 2, 3, 4, 5, 6
## $ sex           &lt;chr&gt; &quot;male&quot;, &quot;female&quot;, &quot;male&quot;, &quot;female&quot;, …
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; 5, 6, 4, 7, 3, 8
## $ t2_vomit      &lt;dbl&gt; 2, 1, 1, 2, 1, 2
## $ t2_aggression &lt;dbl&gt; 6, 7, 6, 7, 5, 8</code></pre>
<div id="select-1" class="section level3 hasAnchor" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> select()<a href="handling-data-with-the-tidyverse.html#select-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="select-using-column-name" class="section level4 hasAnchor" number="2.6.1.1">
<h4><span class="header-section-number">2.6.1.1</span> select() using column name<a href="handling-data-with-the-tidyverse.html#select-using-column-name" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="starts_with" class="section level5 hasAnchor" number="2.6.1.1.1">
<h5><span class="header-section-number">2.6.1.1.1</span> starts_with()<a href="handling-data-with-the-tidyverse.html#starts_with" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>starts_with() allows us to select columns based on how the column name begins. Here we put the columns that begin with “t1” into a new data called data_time1.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="handling-data-with-the-tidyverse.html#cb100-1" aria-hidden="true" tabindex="-1"></a>data_time1 <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span> </span>
<span id="cb100-2"><a href="handling-data-with-the-tidyverse.html#cb100-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;t1&quot;</span>))</span></code></pre></div>
<p>The glimpse command shows us the new data only contains the columns that begin with “t1”</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="handling-data-with-the-tidyverse.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_time1)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 2
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; 5, 6, 4, 7, 3, 8</code></pre>
</div>
<div id="ends_with" class="section level5 hasAnchor" number="2.6.1.1.2">
<h5><span class="header-section-number">2.6.1.1.2</span> ends_with()<a href="handling-data-with-the-tidyverse.html#ends_with" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>ends_with() allows us to select columns based on how the column name ends. Here we put the columns that end with “aggression” into a new data set called data_aggression.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="handling-data-with-the-tidyverse.html#cb103-1" aria-hidden="true" tabindex="-1"></a>data_aggression <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span> </span>
<span id="cb103-2"><a href="handling-data-with-the-tidyverse.html#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">ends_with</span>(<span class="st">&quot;aggression&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="handling-data-with-the-tidyverse.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_aggression)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 2
## $ t1_aggression &lt;dbl&gt; 5, 6, 4, 7, 3, 8
## $ t2_aggression &lt;dbl&gt; 6, 7, 6, 7, 5, 8</code></pre>
</div>
<div id="contains" class="section level5 hasAnchor" number="2.6.1.1.3">
<h5><span class="header-section-number">2.6.1.1.3</span> contains()<a href="handling-data-with-the-tidyverse.html#contains" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>contains() allows us to select columns based on the contents of the column name. Here we put the columns that have “_” in the name into a new data set called new_data.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="handling-data-with-the-tidyverse.html#cb106-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span> </span>
<span id="cb106-2"><a href="handling-data-with-the-tidyverse.html#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">&quot;_&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="handling-data-with-the-tidyverse.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(new_data)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 4
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; 5, 6, 4, 7, 3, 8
## $ t2_vomit      &lt;dbl&gt; 2, 1, 1, 2, 1, 2
## $ t2_aggression &lt;dbl&gt; 6, 7, 6, 7, 5, 8</code></pre>
</div>
<div id="matches" class="section level5 hasAnchor" number="2.6.1.1.4">
<h5><span class="header-section-number">2.6.1.1.4</span> matches()<a href="handling-data-with-the-tidyverse.html#matches" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>It’s also possible to use <em>regex</em> (i.e., a <em>regular expression</em>) to select columns. Regex is a powerful way to specify search/matching requirements for text - in this case the text of column names. An explanation of regex is beyond the scope of this chapter. Nonetheless the example below uses regex to select any column with an underscore in the column name followed by any character. The result is the same as the above for the contains() command. However, the matches() command is more flexible than the contains() command and can take into account substantially more complicated situations.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="handling-data-with-the-tidyverse.html#cb109-1" aria-hidden="true" tabindex="-1"></a>data_matched <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span> </span>
<span id="cb109-2"><a href="handling-data-with-the-tidyverse.html#cb109-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">&quot;(_.)&quot;</span>))</span></code></pre></div>
<p>You can see the columns selected using regex:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="handling-data-with-the-tidyverse.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_matched)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 4
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; 5, 6, 4, 7, 3, 8
## $ t2_vomit      &lt;dbl&gt; 2, 1, 1, 2, 1, 2
## $ t2_aggression &lt;dbl&gt; 6, 7, 6, 7, 5, 8</code></pre>
<p>You can learn about regex at <a href="https://regexone.com">RegexOne</a> and test your regex specification at <a href="https://regex101.com">Regex101</a>. Ideally though, as we discuss in the next chapter, you can use naming conventions that are sufficiently thoughtful that you don’t need regex, or only rarely. The reason for this is that regex can be challenging to use. As Twitter user @ThatJenPerson noted “Regex is like tequila: use it to try to solve a problem and now you have two problems.” Nonetheless, at one or two points in the future we will use regex to solve a problem (but not tequila).</p>
</div>
</div>
<div id="select-using-column-type" class="section level4 hasAnchor" number="2.6.1.2">
<h4><span class="header-section-number">2.6.1.2</span> select() using column type<a href="handling-data-with-the-tidyverse.html#select-using-column-type" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In many cases we will want to select or perform an action on a column based on whether the column is a numeric, character, or factor column (indicated in glimpse output as dbl, chr, and fct, respectively). We will learn more about factors later in this chapter. Each of these column types can be selected by using is.numeric, is.character, or is.factor, respectively, in combination with the where() command.</p>
<p>We can select numeric columns using where() and is.numeric:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="handling-data-with-the-tidyverse.html#cb112-1" aria-hidden="true" tabindex="-1"></a>data_numeric_columns <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span> </span>
<span id="cb112-2"><a href="handling-data-with-the-tidyverse.html#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric))</span></code></pre></div>
<p>You can see the new data contains only the numeric columns:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="handling-data-with-the-tidyverse.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_numeric_columns)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 5
## $ id            &lt;dbl&gt; 1, 2, 3, 4, 5, 6
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; 5, 6, 4, 7, 3, 8
## $ t2_vomit      &lt;dbl&gt; 2, 1, 1, 2, 1, 2
## $ t2_aggression &lt;dbl&gt; 6, 7, 6, 7, 5, 8</code></pre>
<p>We can select character (i.e., chr) columns using where() and is.character:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="handling-data-with-the-tidyverse.html#cb115-1" aria-hidden="true" tabindex="-1"></a>data_character_columns <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span> </span>
<span id="cb115-2"><a href="handling-data-with-the-tidyverse.html#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.character))</span></code></pre></div>
<p>You can see the new data contains only the character columns:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="handling-data-with-the-tidyverse.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_character_columns)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 1
## $ sex &lt;chr&gt; &quot;male&quot;, &quot;female&quot;, &quot;male&quot;, &quot;female&quot;, &quot;male&quot;, &quot;f…</code></pre>
<p>In a future chapter you will see how we can select factors using where(is.factor).</p>
</div>
</div>
<div id="summarise-1" class="section level3 hasAnchor" number="2.6.2">
<h3><span class="header-section-number">2.6.2</span> summarise()<a href="handling-data-with-the-tidyverse.html#summarise-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The summarise() command can summarise multiple columns when combined with starts_with(), ends_with(), contains(), matches(), and where(). However, to use these powerful tools for indicating columns with the summarise command we need the help of the across() command (i.e., across multiple columns).</p>
<p>If we want to obtain the mean of all the columns that start with “t1” we use the commands below. The across command requires that we indicate the columns we want via the .cols argument and the command/function we want to run on those columns via the .fns argument. In the example below, we also add na.rm = TRUE at the end; this is something we send to the mean command to let it know how we want to handle missing data. We add as.data.frame() to get a larger number of decimals.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="handling-data-with-the-tidyverse.html#cb118-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="sc">%&gt;%</span></span>
<span id="cb118-2"><a href="handling-data-with-the-tidyverse.html#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;t1&quot;</span>), </span>
<span id="cb118-3"><a href="handling-data-with-the-tidyverse.html#cb118-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.fns =</span> mean,</span>
<span id="cb118-4"><a href="handling-data-with-the-tidyverse.html#cb118-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb118-5"><a href="handling-data-with-the-tidyverse.html#cb118-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   t1_vomit t1_aggression
## 1    1.833           5.5</code></pre>
<p>If you want to get more sophisticated, you can also add this .names argument below which tells R to call label each output mean by the column name followed by “_mean”.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="handling-data-with-the-tidyverse.html#cb120-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="sc">%&gt;%</span></span>
<span id="cb120-2"><a href="handling-data-with-the-tidyverse.html#cb120-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;t1&quot;</span>), </span>
<span id="cb120-3"><a href="handling-data-with-the-tidyverse.html#cb120-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.fns =</span> mean,</span>
<span id="cb120-4"><a href="handling-data-with-the-tidyverse.html#cb120-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">na.rm =</span> <span class="cn">TRUE</span>,</span>
<span id="cb120-5"><a href="handling-data-with-the-tidyverse.html#cb120-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">&quot;{col}_mean&quot;</span>))  <span class="sc">%&gt;%</span></span>
<span id="cb120-6"><a href="handling-data-with-the-tidyverse.html#cb120-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   t1_vomit_mean t1_aggression_mean
## 1         1.833                5.5</code></pre>
<p>Often you want to calculate more than one statistic for each column. For example, you might want the mean, standard deviation, min, and max. These statistics can be calculated via the mean, sd, min, and max commands, respectively. However, you need to create a list with the statistics you desire.</p>
<p>Below we create a list of the descriptive statistics we desire called desired_statistics, but you can use any name you want. This list only needs to be specified once, but we will repeat it in the examples below for clarity.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="handling-data-with-the-tidyverse.html#cb122-1" aria-hidden="true" tabindex="-1"></a>desired_descriptives <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb122-2"><a href="handling-data-with-the-tidyverse.html#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="sc">~</span><span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb122-3"><a href="handling-data-with-the-tidyverse.html#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="sc">~</span><span class="fu">sd</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb122-4"><a href="handling-data-with-the-tidyverse.html#cb122-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Once you have created the list of descriptive statistics you want you can run the command below to obtain those statistics. However, as you will see the output is too wide to be helpful.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="handling-data-with-the-tidyverse.html#cb123-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="sc">%&gt;%</span></span>
<span id="cb123-2"><a href="handling-data-with-the-tidyverse.html#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;t1&quot;</span>), </span>
<span id="cb123-3"><a href="handling-data-with-the-tidyverse.html#cb123-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.fns =</span> desired_descriptives)) <span class="sc">%&gt;%</span></span>
<span id="cb123-4"><a href="handling-data-with-the-tidyverse.html#cb123-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   t1_vomit_mean t1_vomit_sd t1_aggression_mean
## 1         1.833       1.169                5.5
##   t1_aggression_sd
## 1            1.871</code></pre>
<p>Consequently, we add the t() command (i.e., transpose command) to the end of the summarise request to get a more readable list of statistics:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="handling-data-with-the-tidyverse.html#cb125-1" aria-hidden="true" tabindex="-1"></a>desired_descriptives <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb125-2"><a href="handling-data-with-the-tidyverse.html#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="sc">~</span><span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb125-3"><a href="handling-data-with-the-tidyverse.html#cb125-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="sc">~</span><span class="fu">sd</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb125-4"><a href="handling-data-with-the-tidyverse.html#cb125-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb125-5"><a href="handling-data-with-the-tidyverse.html#cb125-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-6"><a href="handling-data-with-the-tidyverse.html#cb125-6" aria-hidden="true" tabindex="-1"></a>data_exp <span class="sc">%&gt;%</span></span>
<span id="cb125-7"><a href="handling-data-with-the-tidyverse.html#cb125-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;t1&quot;</span>), </span>
<span id="cb125-8"><a href="handling-data-with-the-tidyverse.html#cb125-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.fns =</span> desired_descriptives)) <span class="sc">%&gt;%</span></span>
<span id="cb125-9"><a href="handling-data-with-the-tidyverse.html#cb125-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb125-10"><a href="handling-data-with-the-tidyverse.html#cb125-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>() </span></code></pre></div>
<pre><code>##                     [,1]
## t1_vomit_mean      1.833
## t1_vomit_sd        1.169
## t1_aggression_mean 5.500
## t1_aggression_sd   1.871</code></pre>
<p>Note that in the across command above we could also have used: ends_with(), contains(), matches(), or where().</p>
</div>
<div id="mutate-1" class="section level3 hasAnchor" number="2.6.3">
<h3><span class="header-section-number">2.6.3</span> mutate()<a href="handling-data-with-the-tidyverse.html#mutate-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The mutate() command can also be applied to multiple columns using the across() command. However, sometimes we need to embed our calculation in a custom function. Below is a custom function called make_centered. This custom function takes the values in a column and subtracts the column mean from each value in the column. This is the same task we did previous using the mutate() command in the basic tidyverse section.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="handling-data-with-the-tidyverse.html#cb127-1" aria-hidden="true" tabindex="-1"></a>make_centered <span class="ot">&lt;-</span> <span class="cf">function</span>(values) {</span>
<span id="cb127-2"><a href="handling-data-with-the-tidyverse.html#cb127-2" aria-hidden="true" tabindex="-1"></a>  values_out <span class="ot">&lt;-</span> values <span class="sc">-</span> <span class="fu">mean</span>(values, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb127-3"><a href="handling-data-with-the-tidyverse.html#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(values_out)</span>
<span id="cb127-4"><a href="handling-data-with-the-tidyverse.html#cb127-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>The glimpse() command shows us all the column names. Also notice the values in the agresssion columns are integers.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="handling-data-with-the-tidyverse.html#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_exp)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 6
## $ id            &lt;dbl&gt; 1, 2, 3, 4, 5, 6
## $ sex           &lt;chr&gt; &quot;male&quot;, &quot;female&quot;, &quot;male&quot;, &quot;female&quot;, …
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; 5, 6, 4, 7, 3, 8
## $ t2_vomit      &lt;dbl&gt; 2, 1, 1, 2, 1, 2
## $ t2_aggression &lt;dbl&gt; 6, 7, 6, 7, 5, 8</code></pre>
<p>We combine the mutate() command, with the across() command, and our custom make_centered() command below. The command “centers” or subtracts the mean from any column that ends with “aggression”.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="handling-data-with-the-tidyverse.html#cb130-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span> </span>
<span id="cb130-2"><a href="handling-data-with-the-tidyverse.html#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">ends_with</span>(<span class="st">&quot;aggression&quot;</span>), </span>
<span id="cb130-3"><a href="handling-data-with-the-tidyverse.html#cb130-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">.fns =</span> make_centered))</span></code></pre></div>
<p>You can see via the glimpse() output that the contents of all the columns that end with “aggression” have changed. Every value in each of these columns has had the column mean subtracted from it.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="handling-data-with-the-tidyverse.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_exp)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 6
## $ id            &lt;dbl&gt; 1, 2, 3, 4, 5, 6
## $ sex           &lt;chr&gt; &quot;male&quot;, &quot;female&quot;, &quot;male&quot;, &quot;female&quot;, …
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; -0.5, 0.5, -1.5, 1.5, -2.5, 2.5
## $ t2_vomit      &lt;dbl&gt; 2, 1, 1, 2, 1, 2
## $ t2_aggression &lt;dbl&gt; -0.5, 0.5, -0.5, 0.5, -1.5, 1.5</code></pre>
<p>Note that in the across() command above, we could also have used: starts_with(), contains(), matches(), or where().</p>
<div id="mutate-within-rows" class="section level4 hasAnchor" number="2.6.3.1">
<h4><span class="header-section-number">2.6.3.1</span> mutate() within rows<a href="handling-data-with-the-tidyverse.html#mutate-within-rows" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Researchers often want to average within rows and across columns to create a new column. That is, for each participant (i.e., rat in the current data) we might want to calculate a vomit score that is the average of the two time points (that we will call vomit_avg).</p>
<p>To average within rows (and across columns) we use the rowwise() command to inform R of our intent. However, after we do the necessary calculations we have to shut off the rowwise() calculation state by using the ungroup() command. As well, when we are averaging within rows we have to use c_across() instead of across(). The commands below create a new column called vomit_avg which is the average of the vomit ratings across both times. As before, we also include na.rm = TRUE so the computer drops missing values (if present) when calculating the mean.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="handling-data-with-the-tidyverse.html#cb133-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span> </span>
<span id="cb133-2"><a href="handling-data-with-the-tidyverse.html#cb133-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb133-3"><a href="handling-data-with-the-tidyverse.html#cb133-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vomit_avg =</span> <span class="fu">mean</span>( <span class="fu">c_across</span>(<span class="at">cols =</span> <span class="fu">ends_with</span>(<span class="st">&quot;vomit&quot;</span>)),</span>
<span id="cb133-4"><a href="handling-data-with-the-tidyverse.html#cb133-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb133-5"><a href="handling-data-with-the-tidyverse.html#cb133-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<p>You can see the new column we created with the glimpse() command:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="handling-data-with-the-tidyverse.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_exp)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 7
## $ id            &lt;dbl&gt; 1, 2, 3, 4, 5, 6
## $ sex           &lt;chr&gt; &quot;male&quot;, &quot;female&quot;, &quot;male&quot;, &quot;female&quot;, …
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; -0.5, 0.5, -1.5, 1.5, -2.5, 2.5
## $ t2_vomit      &lt;dbl&gt; 2, 1, 1, 2, 1, 2
## $ t2_aggression &lt;dbl&gt; -0.5, 0.5, -0.5, 0.5, -1.5, 1.5
## $ vomit_avg     &lt;dbl&gt; 2.5, 1.5, 0.5, 2.5, 1.5, 1.5</code></pre>
<p>The print() command could make it easier to see that the new column is the average of the other two, but if we use the print() command below it wouldn’t work. Why? There are too many columns in the data set, so only the first few columns are shown.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="handling-data-with-the-tidyverse.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data_exp)</span></code></pre></div>
<p>To see that the new column, vomit_avg, is the average of the other vomit columns we use the select command before print(). This prints only the relvant columns. When this is done, it’s easy to see how the values in the vomit_avg column are the mean of the other two columns.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="handling-data-with-the-tidyverse.html#cb137-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="sc">%&gt;%</span></span>
<span id="cb137-2"><a href="handling-data-with-the-tidyverse.html#cb137-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">&quot;vomit&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb137-3"><a href="handling-data-with-the-tidyverse.html#cb137-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   t1_vomit t2_vomit vomit_avg
##      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1        3        2       2.5
## 2        2        1       1.5
## 3        0        1       0.5
## 4        3        2       2.5
## 5        2        1       1.5
## 6        1        2       1.5</code></pre>
</div>
<div id="mutate-within-rows-using-column-names" class="section level4 hasAnchor" number="2.6.3.2">
<h4><span class="header-section-number">2.6.3.2</span> mutate() within rows using column names<a href="handling-data-with-the-tidyverse.html#mutate-within-rows-using-column-names" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Sometimes it can be difficult to use one of the advanced select commands to obtain the columns you need to average across. The advanced commands like ends_with() and starts_with() can sometimes include columns you don’t want. The command below is equivalent to the one above, however, we explicitly name the variables we want to average across.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="handling-data-with-the-tidyverse.html#cb139-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span> </span>
<span id="cb139-2"><a href="handling-data-with-the-tidyverse.html#cb139-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb139-3"><a href="handling-data-with-the-tidyverse.html#cb139-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vomit_avg =</span> <span class="fu">mean</span>( <span class="fu">c_across</span>(<span class="at">cols =</span> <span class="fu">c</span>(t1_vomit, t2_vomit)),</span>
<span id="cb139-4"><a href="handling-data-with-the-tidyverse.html#cb139-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb139-5"><a href="handling-data-with-the-tidyverse.html#cb139-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<p>You can use print() to confirm we get the same result:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="handling-data-with-the-tidyverse.html#cb140-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="sc">%&gt;%</span></span>
<span id="cb140-2"><a href="handling-data-with-the-tidyverse.html#cb140-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">&quot;vomit&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb140-3"><a href="handling-data-with-the-tidyverse.html#cb140-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   t1_vomit t2_vomit vomit_avg
##      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1        3        2       2.5
## 2        2        1       1.5
## 3        0        1       0.5
## 4        3        2       2.5
## 5        2        1       1.5
## 6        1        2       1.5</code></pre>
</div>
<div id="mutate-for-factors" class="section level4 hasAnchor" number="2.6.3.3">
<h4><span class="header-section-number">2.6.3.3</span> mutate() for factors<a href="handling-data-with-the-tidyverse.html#mutate-for-factors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>It is critical that you indicate to R that categorical variables are in fact categorical variables. In R, categorical variables are referred to as factors. For humans, a factor like sex has three possible levels: female, male, intersex.</p>
<p>An inspection of the glimpse() command output reveals that the sex column has the type character - as indicated by “chr”. Also notice, as you inspect this output, that we use words (e.g., female) to indicate the sex in the column rather than a number to represent a female participant (e.g., 2). This is the preferred, but less common, approach to entering data.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="handling-data-with-the-tidyverse.html#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_exp)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 7
## $ id            &lt;dbl&gt; 1, 2, 3, 4, 5, 6
## $ sex           &lt;chr&gt; &quot;male&quot;, &quot;female&quot;, &quot;male&quot;, &quot;female&quot;, …
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; -0.5, 0.5, -1.5, 1.5, -2.5, 2.5
## $ t2_vomit      &lt;dbl&gt; 2, 1, 1, 2, 1, 2
## $ t2_aggression &lt;dbl&gt; -0.5, 0.5, -0.5, 0.5, -1.5, 1.5
## $ vomit_avg     &lt;dbl&gt; 2.5, 1.5, 0.5, 2.5, 1.5, 1.5</code></pre>
<p>We need to convert the sex column to a factor in order for R to handle it appropriately in analyses. Failure to indicate the column is a factor column could result in R conducting all the analyses and presenting incorrect results. Consequently, it is critical that we covert the column to a factor. Fortunately, that is easily done using the as_factor() command (there is also an as.factor command if as_factor won’t work for some reason).</p>
<p>We convert the sex column to a factor with this code:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="handling-data-with-the-tidyverse.html#cb144-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span></span>
<span id="cb144-2"><a href="handling-data-with-the-tidyverse.html#cb144-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as_factor</span>(sex))</span></code></pre></div>
<p>You can confirm this worked with the glimpse() command:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="handling-data-with-the-tidyverse.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_exp)</span></code></pre></div>
<pre><code>## Rows: 6
## Columns: 7
## $ id            &lt;dbl&gt; 1, 2, 3, 4, 5, 6
## $ sex           &lt;fct&gt; male, female, male, female, male, fe…
## $ t1_vomit      &lt;dbl&gt; 3, 2, 0, 3, 2, 1
## $ t1_aggression &lt;dbl&gt; -0.5, 0.5, -1.5, 1.5, -2.5, 2.5
## $ t2_vomit      &lt;dbl&gt; 2, 1, 1, 2, 1, 2
## $ t2_aggression &lt;dbl&gt; -0.5, 0.5, -0.5, 0.5, -1.5, 1.5
## $ vomit_avg     &lt;dbl&gt; 2.5, 1.5, 0.5, 2.5, 1.5, 1.5</code></pre>
<p>If you entered your data using words for each level of sex (e.g., male, female) you’re done at this point. However, if you used numbers to represent each level of sex in your data, there is one more step. Imagine your data was entered in a poorly advised manner, such that 1 was used to indicate male, 2 was used to indicate female, and 3 was used to indicate intersex. If this was the case, you need to indicate to R what each of those values represent. We do that with the code below.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="handling-data-with-the-tidyverse.html#cb147-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="ot">&lt;-</span> data_exp <span class="sc">%&gt;%</span></span>
<span id="cb147-2"><a href="handling-data-with-the-tidyverse.html#cb147-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">fct_recode</span>(sex,</span>
<span id="cb147-3"><a href="handling-data-with-the-tidyverse.html#cb147-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">male =</span> <span class="st">&quot;1&quot;</span>,</span>
<span id="cb147-4"><a href="handling-data-with-the-tidyverse.html#cb147-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">female =</span> <span class="st">&quot;2&quot;</span>,</span>
<span id="cb147-5"><a href="handling-data-with-the-tidyverse.html#cb147-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">intersex =</span> <span class="st">&quot;3&quot;</span>))</span></code></pre></div>
</div>
</div>
</div>
<div id="using-help" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Using help<a href="handling-data-with-the-tidyverse.html#using-help" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In order to become efficient at analyzing data using R, you will need to become adapt at reading and understanding the help files associated with each command. After you have activated a package using the library command (e.g., library(tidyverse)) you can access the help page for every command in that package. To access the help page simply type a question mark followed by the command you want to know how to use (no space between them). The code below brings up the help page for the select() command. Notice that we put the library() command first - just a reminder that this needs to be done prior to using help for that package. Try the commands below in the Console:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="handling-data-with-the-tidyverse.html#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb148-2"><a href="handling-data-with-the-tidyverse.html#cb148-2" aria-hidden="true" tabindex="-1"></a>?select</span></code></pre></div>
<p>Examine the page that appears on the Help tab in the panel in the lower right of your screen. Read through the help file comparing what you read there to what we have learned about the select command. Notice how the help file tells you about the argument that you sent into the select() command, and also what the select() command returns when it receives those commands. Pay particular attention to the examples near the bottom of the help page. At the very bottom of the help page you will see [Package dplyr version 1.0.0 Index]. This tells you the select() command is from the dplyr package (part of the tidyverse). Notice that the word “Index” is underlined. Click on the word Index. You will be presented with list of other commands in the dplyr package.</p>
<p>As you become more experienced with R help pages, this is how you will learn to use new commands. Examine the help pages for the commands below by typing a question mark into the Console followed by the command name. Note that for filter and starts_with you will be presented with a menu instead of help page. This typically occurs because the command is in more than one package. If this does occur, read through the options you are presented with to try and figure out which one you wanted. Typically, you want the first option. If you’re not sure, try one. If it’s not what you want, use the back arrow in the Help panel to go back and pick another one.</p>
<ul>
<li>mutate</li>
<li>filter</li>
<li>starts_with</li>
</ul>
</div>
<div id="base-r-vs-tidyverse" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Base R vs tidyverse<a href="handling-data-with-the-tidyverse.html#base-r-vs-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>All of the commands used to this point in the chapter have been the tidyverse approach to using R. That is the approach we will normally use. However, it’s important to note that there is another way of using R, called base R.</p>
<p>Sometimes students have problems with their code when they mix and match these approaches using a bit of both. We will be using the tidyverse approach to using R but on the internet you will often see sample code that uses the older base R approach. A bit of background knowledge is helpful for understanding why we do things one way (e.g., read_csv with the tidyverse) instead of another (e.g., read.csv with base R).</p>
<div id="tibbles-vs.-data-frames" class="section level3 hasAnchor" number="2.8.1">
<h3><span class="header-section-number">2.8.1</span> Tibbles vs. data frames<a href="handling-data-with-the-tidyverse.html#tibbles-vs.-data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When you load data into R, it is typically represented in one of two formats inside the computer - depending on the command you used. The original format for representing a data set in R is the data frame. You will see this term used frequently when you read about R. When you load data using read.csv(), your data is loaded into a data frame in the computer. That is, your data is represented in the memory of the computer in a particular format and structure called a data frame. This contrasts with the newer tidyverse approach to representing data in the computer called a tibble - which is just a newer more advanced version of the data frame.</p>
</div>
<div id="read.csv-and-data-frames" class="section level3 hasAnchor" number="2.8.2">
<h3><span class="header-section-number">2.8.2</span> read.csv() and data frames<a href="handling-data-with-the-tidyverse.html#read.csv-and-data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When you read data into R using the command read.csv() (with a period) you load the data into a data frame (base R).</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="handling-data-with-the-tidyverse.html#cb149-1" aria-hidden="true" tabindex="-1"></a>my_dataframe <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&quot;data_okcupid.csv&quot;</span>)</span></code></pre></div>
<p>Notice that when you print a data frame it does not show you the number of rows or columns above the data like our example did with the okcupid_profiles data. Likewise, it does not show you the type of data in each column (e.g., dbl, fct, chr). It also presents all of your data rather than just the first few rows (as the tibble does). As a result, in the output below, we show only the first 10 rows of the output - because all the rows are printed in your Console with a data frame (too much to show here).</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="handling-data-with-the-tidyverse.html#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(my_dataframe)</span></code></pre></div>
<pre><code>##    age              diet height                      pets
## 1   22 strictly anything     75 likes dogs and likes cats
## 2   35      mostly other     70 likes dogs and likes cats
## 3   38          anything     68                  has cats
## 4   23        vegetarian     71                likes cats
## 5   29              &lt;NA&gt;     66 likes dogs and likes cats
## 6   29   mostly anything     67                likes cats
## 7   32 strictly anything     65 likes dogs and likes cats
## 8   31   mostly anything     65 likes dogs and likes cats
## 9   24 strictly anything     67 likes dogs and likes cats
## 10  37   mostly anything     65 likes dogs and likes cats
##    sex    status
## 1    m    single
## 2    m    single
## 3    m available
## 4    m    single
## 5    m    single
## 6    m    single
## 7    f    single
## 8    f    single
## 9    f    single
## 10   m    single</code></pre>
</div>
<div id="read_csv-and-tibbles" class="section level3 hasAnchor" number="2.8.3">
<h3><span class="header-section-number">2.8.3</span> read_csv() and tibbles<a href="handling-data-with-the-tidyverse.html#read_csv-and-tibbles" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When you read data into R using the command read_csv() (with an underscore) you load the data into a tibble (tidyverse).</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="handling-data-with-the-tidyverse.html#cb152-1" aria-hidden="true" tabindex="-1"></a>my_tibble <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;data_okcupid.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 59946 Columns: 6
## ── Column specification ────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (4): diet, pets, sex, status
## dbl (2): age, height
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>The tibble is modern version of the data frame. Notice that when you print a tibble it DOES show you the number of rows and columns. As well, it shows you the type of data in each column. Importantly, the tibble only provides the first few rows of output so it doesn’t fill your screen.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="handling-data-with-the-tidyverse.html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(my_tibble)</span></code></pre></div>
<pre><code>## # A tibble: 59,946 × 6
##      age diet              height pets          sex   status
##    &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;         &lt;chr&gt; &lt;chr&gt; 
##  1    22 strictly anything     75 likes dogs a… m     single
##  2    35 mostly other          70 likes dogs a… m     single
##  3    38 anything              68 has cats      m     avail…
##  4    23 vegetarian            71 likes cats    m     single
##  5    29 &lt;NA&gt;                  66 likes dogs a… m     single
##  6    29 mostly anything       67 likes cats    m     single
##  7    32 strictly anything     65 likes dogs a… f     single
##  8    31 mostly anything       65 likes dogs a… f     single
##  9    24 strictly anything     67 likes dogs a… f     single
## 10    37 mostly anything       65 likes dogs a… m     single
## # … with 59,936 more rows</code></pre>
<p>In short, you should always use tibbles (i.e., use read_csv() not read.csv()). The differences between data frames and tibbles run deeper than the superficial output provided here. On some rare occasions an old package or command may not work with a tibble so you need to make it a data frame. You can do so with the commands below. We will flag these rare occurances to you when they occur.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="handling-data-with-the-tidyverse.html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame from a tibble</span></span>
<span id="cb156-2"><a href="handling-data-with-the-tidyverse.html#cb156-2" aria-hidden="true" tabindex="-1"></a>new_dataframe <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(my_tibble)</span></code></pre></div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-1-friday-workshop.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-2-friday-workshop.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/02-tidy_intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
