<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Scaling | Welcome!</title>
  <meta name="description" content="Course notes for PSYC 3250" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Scaling | Welcome!" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course notes for PSYC 3250" />
  <meta name="github-repo" content="dstanley4/psyc3250bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Scaling | Welcome!" />
  
  <meta name="twitter:description" content="Course notes for PSYC 3250" />
  

<meta name="author" content="David J. Stanley" />


<meta name="date" content="2022-01-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="notation.html"/>
<link rel="next" href="percentiles.html"/>
<script src="libs/header-attrs/header-attrs.js"></script>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course:</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html"><i class="fa fa-check"></i><b>1</b> Week 1 Friday Workshop</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#a-focus-on-workflow"><i class="fa fa-check"></i><b>1.1</b> A focus on workflow</a></li>
<li class="chapter" data-level="1.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#r-works-with-plug-ins"><i class="fa fa-check"></i><b>1.2</b> R works with plug-ins</a></li>
<li class="chapter" data-level="1.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#software-choice"><i class="fa fa-check"></i><b>1.3</b> Software Choice</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#mac"><i class="fa fa-check"></i><b>1.3.1</b> Mac</a></li>
<li class="chapter" data-level="1.3.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#pc"><i class="fa fa-check"></i><b>1.3.2</b> PC</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-rstudio-not-r"><i class="fa fa-check"></i><b>1.4</b> Run RStudio not R</a></li>
<li class="chapter" data-level="1.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#rstudio-configuration-first-run-only"><i class="fa fa-check"></i><b>1.5</b> RStudio configuration, First run only</a></li>
<li class="chapter" data-level="1.6" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#begin-with-an-rstudio-project"><i class="fa fa-check"></i><b>1.6</b> Begin with an RStudio Project</a></li>
<li class="chapter" data-level="1.7" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#exploring-the-r-studio-interface"><i class="fa fa-check"></i><b>1.7</b> Exploring the R Studio Interface</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#console-panel"><i class="fa fa-check"></i><b>1.7.1</b> Console panel</a></li>
<li class="chapter" data-level="1.7.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#script-panel"><i class="fa fa-check"></i><b>1.7.2</b> Script Panel</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#writing-your-first-script"><i class="fa fa-check"></i><b>1.8</b> Writing your first script</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#create-the-script-file"><i class="fa fa-check"></i><b>1.8.1</b> Create the script file</a></li>
<li class="chapter" data-level="1.8.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#add-a-comment-to-your-script"><i class="fa fa-check"></i><b>1.8.2</b> Add a comment to your script</a></li>
<li class="chapter" data-level="1.8.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#background-about-the-tidyverse"><i class="fa fa-check"></i><b>1.8.3</b> Background about the tidyverse</a></li>
<li class="chapter" data-level="1.8.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#add-librarytidyverse-to-your-script"><i class="fa fa-check"></i><b>1.8.4</b> Add library(tidyverse) to your script</a></li>
<li class="chapter" data-level="1.8.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#activate-tidyverse-auto-complete-for-your-script"><i class="fa fa-check"></i><b>1.8.5</b> Activate tidyverse auto-complete for your script</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#loading-your-data"><i class="fa fa-check"></i><b>1.9</b> Loading your data</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#use-read_csv-not-read.csv-to-open-files."><i class="fa fa-check"></i><b>1.9.1</b> Use read_csv (not read.csv) to open files.</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#checking-out-your-data"><i class="fa fa-check"></i><b>1.10</b> Checking out your data</a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#view-see-a-spreadsheet-view-of-your-data"><i class="fa fa-check"></i><b>1.10.1</b> view(): See a spreadsheet view of your data</a></li>
<li class="chapter" data-level="1.10.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#print-see-you-data-in-the-console"><i class="fa fa-check"></i><b>1.10.2</b> print(): See you data in the Console</a></li>
<li class="chapter" data-level="1.10.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#head-check-out-the-first-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.3</b> head(): Check out the first few rows of data</a></li>
<li class="chapter" data-level="1.10.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#tail-check-out-the-last-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.4</b> tail(): Check out the last few rows of data</a></li>
<li class="chapter" data-level="1.10.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#summary-quick-summaries"><i class="fa fa-check"></i><b>1.10.5</b> summary(): Quick summaries</a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-vs.-source-with-echo-vs.-source"><i class="fa fa-check"></i><b>1.11</b> Run <em>vs.</em> Source with Echo <em>vs.</em> Source</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-select-text"><i class="fa fa-check"></i><b>1.11.1</b> Run select text</a></li>
<li class="chapter" data-level="1.11.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#source-without-echo"><i class="fa fa-check"></i><b>1.11.2</b> Source (without Echo)</a></li>
<li class="chapter" data-level="1.11.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#source-with-echo"><i class="fa fa-check"></i><b>1.11.3</b> Source with Echo</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#trying-source-with-echo"><i class="fa fa-check"></i><b>1.12</b> Trying Source with Echo</a></li>
<li class="chapter" data-level="1.13" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#a-few-key-points-about"><i class="fa fa-check"></i><b>1.13</b> A few key points about</a>
<ul>
<li class="chapter" data-level="1.13.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#lists"><i class="fa fa-check"></i><b>1.13.1</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#revisiting-read_csv"><i class="fa fa-check"></i><b>1.14</b> Revisiting read_csv()</a></li>
<li class="chapter" data-level="1.15" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#thats-it"><i class="fa fa-check"></i><b>1.15</b> That’s it!</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html"><i class="fa fa-check"></i><b>2</b> Handling Data with the Tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>2.1</b> Required</a></li>
<li class="chapter" data-level="2.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>2.2</b> Objective</a></li>
<li class="chapter" data-level="2.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-the-console"><i class="fa fa-check"></i><b>2.3</b> Using the Console</a></li>
<li class="chapter" data-level="2.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tidyverse-help-with-the-introverse"><i class="fa fa-check"></i><b>2.4</b> Tidyverse help with the Introverse</a></li>
<li class="chapter" data-level="2.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#basic-tidyverse-commands"><i class="fa fa-check"></i><b>2.5</b> Basic tidyverse commands</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select"><i class="fa fa-check"></i><b>2.5.1</b> select()</a></li>
<li class="chapter" data-level="2.5.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise"><i class="fa fa-check"></i><b>2.5.2</b> summarise()</a></li>
<li class="chapter" data-level="2.5.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#filter"><i class="fa fa-check"></i><b>2.5.3</b> filter()</a></li>
<li class="chapter" data-level="2.5.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#group_by"><i class="fa fa-check"></i><b>2.5.4</b> group_by()</a></li>
<li class="chapter" data-level="2.5.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate"><i class="fa fa-check"></i><b>2.5.5</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#advanced-tidyverse-commands"><i class="fa fa-check"></i><b>2.6</b> Advanced tidyverse commands</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select-1"><i class="fa fa-check"></i><b>2.6.1</b> select()</a></li>
<li class="chapter" data-level="2.6.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise-1"><i class="fa fa-check"></i><b>2.6.2</b> summarise()</a></li>
<li class="chapter" data-level="2.6.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate-1"><i class="fa fa-check"></i><b>2.6.3</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-help"><i class="fa fa-check"></i><b>2.7</b> Using help</a></li>
<li class="chapter" data-level="2.8" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#base-r-vs-tidyverse"><i class="fa fa-check"></i><b>2.8</b> Base R vs tidyverse</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tibbles-vs.-data-frames"><i class="fa fa-check"></i><b>2.8.1</b> Tibbles vs. data frames</a></li>
<li class="chapter" data-level="2.8.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read.csv-and-data-frames"><i class="fa fa-check"></i><b>2.8.2</b> read.csv() and data frames</a></li>
<li class="chapter" data-level="2.8.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read_csv-and-tibbles"><i class="fa fa-check"></i><b>2.8.3</b> read_csv() and tibbles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html"><i class="fa fa-check"></i><b>3</b> Week 2 Friday Workshop</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#required-packages"><i class="fa fa-check"></i><b>3.1</b> Required Packages</a></li>
<li class="chapter" data-level="3.2" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#goals"><i class="fa fa-check"></i><b>3.2</b> Goals</a></li>
<li class="chapter" data-level="3.3" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#data-and-column-names"><i class="fa fa-check"></i><b>3.3</b> Data and column names</a></li>
<li class="chapter" data-level="3.4" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#install-packages"><i class="fa fa-check"></i><b>3.4</b> Install packages</a></li>
<li class="chapter" data-level="3.5" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#rstudio-project"><i class="fa fa-check"></i><b>3.5</b> RStudio Project</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#make-a-script"><i class="fa fa-check"></i><b>3.5.1</b> Make a script</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#loading-data"><i class="fa fa-check"></i><b>3.6</b> Loading data</a></li>
<li class="chapter" data-level="3.7" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#clean-and-screen-the-data"><i class="fa fa-check"></i><b>3.7</b> Clean and screen the data</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#numeric-screening"><i class="fa fa-check"></i><b>3.7.1</b> Numeric screening</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#flipping-responses-to-reverse-key-items"><i class="fa fa-check"></i><b>3.8</b> Flipping responses to reverse-key items</a></li>
<li class="chapter" data-level="3.9" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#making-scale-scores"><i class="fa fa-check"></i><b>3.9</b> Making scale scores</a></li>
<li class="chapter" data-level="3.10" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#descriptive-statistics-for-scale-scores"><i class="fa fa-check"></i><b>3.10</b> Descriptive statistics for scale scores</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html"><i class="fa fa-check"></i><b>4</b> Week 3 Friday Workshop</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#required-packages-1"><i class="fa fa-check"></i><b>4.1</b> Required Packages</a></li>
<li class="chapter" data-level="4.2" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#goals-1"><i class="fa fa-check"></i><b>4.2</b> Goals</a></li>
<li class="chapter" data-level="4.3" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#data-and-column-names-1"><i class="fa fa-check"></i><b>4.3</b> Data and column names</a></li>
<li class="chapter" data-level="4.4" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#install-packages-1"><i class="fa fa-check"></i><b>4.4</b> Install packages</a></li>
<li class="chapter" data-level="4.5" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#rstudio-project-1"><i class="fa fa-check"></i><b>4.5</b> RStudio Project</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#make-a-script-1"><i class="fa fa-check"></i><b>4.5.1</b> Make a script</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#week-2-catchup"><i class="fa fa-check"></i><b>4.6</b> Week 2 Catchup</a></li>
<li class="chapter" data-level="4.7" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#creating-compositescale-scores"><i class="fa fa-check"></i><b>4.7</b> Creating composite/scale scores</a></li>
<li class="chapter" data-level="4.8" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-scale-scores"><i class="fa fa-check"></i><b>4.8</b> Variance of scale scores</a></li>
<li class="chapter" data-level="4.9" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-items"><i class="fa fa-check"></i><b>4.9</b> Variance of items</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#approach-1"><i class="fa fa-check"></i><b>4.9.1</b> Approach 1</a></li>
<li class="chapter" data-level="4.9.2" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#approach-2"><i class="fa fa-check"></i><b>4.9.2</b> Approach 2</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-affect_sum-column"><i class="fa fa-check"></i><b>4.10</b> Variance of affect_sum column</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="notation.html"><a href="notation.html"><i class="fa fa-check"></i><b>5</b> Notation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="notation.html"><a href="notation.html#measurement-notation"><i class="fa fa-check"></i><b>5.1</b> Measurement Notation</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="scaling.html"><a href="scaling.html"><i class="fa fa-check"></i><b>6</b> Scaling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="scaling.html"><a href="scaling.html#data-entry"><i class="fa fa-check"></i><b>6.1</b> Data entry</a></li>
<li class="chapter" data-level="6.2" data-path="scaling.html"><a href="scaling.html#loading-data-1"><i class="fa fa-check"></i><b>6.2</b> Loading data</a></li>
<li class="chapter" data-level="6.3" data-path="scaling.html"><a href="scaling.html#viewing-data"><i class="fa fa-check"></i><b>6.3</b> Viewing data</a></li>
<li class="chapter" data-level="6.4" data-path="scaling.html"><a href="scaling.html#summary-statistics"><i class="fa fa-check"></i><b>6.4</b> Summary statistics</a></li>
<li class="chapter" data-level="6.5" data-path="scaling.html"><a href="scaling.html#converting-units"><i class="fa fa-check"></i><b>6.5</b> Converting units</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="scaling.html"><a href="scaling.html#inches"><i class="fa fa-check"></i><b>6.5.1</b> Inches</a></li>
<li class="chapter" data-level="6.5.2" data-path="scaling.html"><a href="scaling.html#z-scores"><i class="fa fa-check"></i><b>6.5.2</b> <em>z</em>-scores</a></li>
<li class="chapter" data-level="6.5.3" data-path="scaling.html"><a href="scaling.html#t-scores"><i class="fa fa-check"></i><b>6.5.3</b> T-scores</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="scaling.html"><a href="scaling.html#frame-of-references"><i class="fa fa-check"></i><b>6.6</b> Frame of references</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="scaling.html"><a href="scaling.html#all-participants"><i class="fa fa-check"></i><b>6.6.1</b> All participants</a></li>
<li class="chapter" data-level="6.6.2" data-path="scaling.html"><a href="scaling.html#male-reference"><i class="fa fa-check"></i><b>6.6.2</b> Male reference</a></li>
<li class="chapter" data-level="6.6.3" data-path="scaling.html"><a href="scaling.html#canadian-reference"><i class="fa fa-check"></i><b>6.6.3</b> Canadian reference</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="scaling.html"><a href="scaling.html#summary-4"><i class="fa fa-check"></i><b>6.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="percentiles.html"><a href="percentiles.html"><i class="fa fa-check"></i><b>7</b> Percentiles</a>
<ul>
<li class="chapter" data-level="7.1" data-path="percentiles.html"><a href="percentiles.html#assuming-a-normal-distribution-approach"><i class="fa fa-check"></i><b>7.1</b> Assuming a normal distribution approach</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="percentiles.html"><a href="percentiles.html#a-single-case"><i class="fa fa-check"></i><b>7.1.1</b> A single case</a></li>
<li class="chapter" data-level="7.1.2" data-path="percentiles.html"><a href="percentiles.html#many-cases-using-r"><i class="fa fa-check"></i><b>7.1.2</b> Many cases using R</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="percentiles.html"><a href="percentiles.html#assumption-free-approach"><i class="fa fa-check"></i><b>7.2</b> Assumption free approach</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>8</b> Graphing</a>
<ul>
<li class="chapter" data-level="8.1" data-path="graphing.html"><a href="graphing.html#required-1"><i class="fa fa-check"></i><b>8.1</b> Required</a></li>
<li class="chapter" data-level="8.2" data-path="graphing.html"><a href="graphing.html#data"><i class="fa fa-check"></i><b>8.2</b> Data</a></li>
<li class="chapter" data-level="8.3" data-path="graphing.html"><a href="graphing.html#graph-basics"><i class="fa fa-check"></i><b>8.3</b> Graph basics</a></li>
<li class="chapter" data-level="8.4" data-path="graphing.html"><a href="graphing.html#graphing-efficiently"><i class="fa fa-check"></i><b>8.4</b> Graphing efficiently</a></li>
<li class="chapter" data-level="8.5" data-path="graphing.html"><a href="graphing.html#aesthetics"><i class="fa fa-check"></i><b>8.5</b> Aesthetics</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="graphing.html"><a href="graphing.html#fill-color"><i class="fa fa-check"></i><b>8.5.1</b> Fill color</a></li>
<li class="chapter" data-level="8.5.2" data-path="graphing.html"><a href="graphing.html#overriding-aes"><i class="fa fa-check"></i><b>8.5.2</b> Overriding aes()</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="graphing.html"><a href="graphing.html#apa-style"><i class="fa fa-check"></i><b>8.6</b> APA style</a></li>
<li class="chapter" data-level="8.7" data-path="graphing.html"><a href="graphing.html#axes"><i class="fa fa-check"></i><b>8.7</b> Axes</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="graphing.html"><a href="graphing.html#range"><i class="fa fa-check"></i><b>8.7.1</b> Range</a></li>
<li class="chapter" data-level="8.7.2" data-path="graphing.html"><a href="graphing.html#ticks"><i class="fa fa-check"></i><b>8.7.2</b> Ticks</a></li>
<li class="chapter" data-level="8.7.3" data-path="graphing.html"><a href="graphing.html#labels"><i class="fa fa-check"></i><b>8.7.3</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="graphing.html"><a href="graphing.html#axis-values"><i class="fa fa-check"></i><b>8.8</b> Axis values</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="graphing.html"><a href="graphing.html#text"><i class="fa fa-check"></i><b>8.8.1</b> Text</a></li>
<li class="chapter" data-level="8.8.2" data-path="graphing.html"><a href="graphing.html#angle"><i class="fa fa-check"></i><b>8.8.2</b> Angle</a></li>
<li class="chapter" data-level="8.8.3" data-path="graphing.html"><a href="graphing.html#alignment"><i class="fa fa-check"></i><b>8.8.3</b> Alignment</a></li>
<li class="chapter" data-level="8.8.4" data-path="graphing.html"><a href="graphing.html#order"><i class="fa fa-check"></i><b>8.8.4</b> Order</a></li>
<li class="chapter" data-level="8.8.5" data-path="graphing.html"><a href="graphing.html#legend-order"><i class="fa fa-check"></i><b>8.8.5</b> Legend order</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="graphing.html"><a href="graphing.html#custom-colours"><i class="fa fa-check"></i><b>8.9</b> Custom colours</a>
<ul>
<li class="chapter" data-level="8.9.1" data-path="graphing.html"><a href="graphing.html#r-palette"><i class="fa fa-check"></i><b>8.9.1</b> R palette</a></li>
<li class="chapter" data-level="8.9.2" data-path="graphing.html"><a href="graphing.html#hex-colours"><i class="fa fa-check"></i><b>8.9.2</b> Hex colours</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="graphing.html"><a href="graphing.html#emoji"><i class="fa fa-check"></i><b>8.10</b> Emoji</a></li>
<li class="chapter" data-level="8.11" data-path="graphing.html"><a href="graphing.html#accessible-colors"><i class="fa fa-check"></i><b>8.11</b> Accessible Colors</a>
<ul>
<li class="chapter" data-level="8.11.1" data-path="graphing.html"><a href="graphing.html#rcolorbrewer"><i class="fa fa-check"></i><b>8.11.1</b> RColorBrewer</a></li>
<li class="chapter" data-level="8.11.2" data-path="graphing.html"><a href="graphing.html#avoid-color"><i class="fa fa-check"></i><b>8.11.2</b> Avoid color</a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="graphing.html"><a href="graphing.html#saving"><i class="fa fa-check"></i><b>8.12</b> Saving</a>
<ul>
<li class="chapter" data-level="8.12.1" data-path="graphing.html"><a href="graphing.html#mac-1"><i class="fa fa-check"></i><b>8.12.1</b> MAC</a></li>
<li class="chapter" data-level="8.12.2" data-path="graphing.html"><a href="graphing.html#pc-or-mac"><i class="fa fa-check"></i><b>8.12.2</b> PC or MAC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Welcome!</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="scaling" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Scaling</h1>
<div id="data-entry" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Data entry</h2>
<p>We begin by entering data into Excel (or any other spreadsheet) as per below. Notice how we use the first row as a header for the column names. Once we enter the data this way we need to save it as a .CSV file (comma separated values). You do so using the Save As menu item in Excel. Once the Save window appears - you will notice a File Format pull-down button. Use the button to select the CSV (comma delimited) option. Indicate a file name of “data_heights.csv” and save the file.</p>
<p><img src="ch_scaling/images/scaling_data_excel.png" width="35%" /></p>
<p>What is a .CSV file? It’s just a text file where the columns are separated by commas. If you were to open the file in TextEdit on a Mac (or Notepad on Windows) you would see something like the image below. You don’t need to do this step - but if you did, it would just show you how the file is saved on disk.</p>
<p><img src="ch_scaling/images/scaling_data_text.png" width="25%" /></p>
</div>
<div id="loading-data-1" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Loading data</h2>
<p>Begin by creating a Project in RStudio on your computer (or via RStudio Cloud). Place the “data_heights.csv” in the Project folder. If you are using R Studio Cloud this means uploading the file via the Upload button the File tab (see picture below):</p>
<p><img src="ch_scaling/images/upload_button.png" width="50%" /></p>
<p>Prior to loading the data we have to install the tidyverse and sjstats packages. This only needs to be done once if you are using RStudio your computer. If you are using RStudio in the Cloud you need to do it once for each project/workspace. You install these packages by typing the command below in the CONSOLE. Do NOT put these commands in your script. It will take some time to run. Don’t worry about all the text feedback you see on the screen.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="scaling.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>, <span class="at">dep =</span> <span class="cn">TRUE</span>)</span>
<span id="cb219-2"><a href="scaling.html#cb219-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;sjstats&quot;</span>, <span class="at">dep =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>From this point on place all the R commands into your script. We begin by activating the tidyverse and sjstats packages with the library() command. Then we load the data using read_csv(). Notice how use indicate missing values using the <strong>na</strong> argument of the read_csv() command; if the computer see nothing in the column or -999 it puts in a missing value place holder.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="scaling.html#cb220-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb220-2"><a href="scaling.html#cb220-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjstats)</span>
<span id="cb220-3"><a href="scaling.html#cb220-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb220-4"><a href="scaling.html#cb220-4" aria-hidden="true" tabindex="-1"></a>height_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data_heights.csv&quot;</span>, <span class="at">na =</span> <span class="fu">c</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;-999&quot;</span>))</span></code></pre></div>
<pre><code>## Rows: 20 Columns: 4</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (2): name, sex
## dbl (2): part_id, cm_height</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>We can see the columns in the data we loaded using the glimpse() command:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="scaling.html#cb224-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(height_data)</span></code></pre></div>
<pre><code>## Rows: 20
## Columns: 4
## $ part_id   &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1…
## $ name      &lt;chr&gt; &quot;John&quot;, &quot;Jim&quot;, &quot;Steve&quot;, &quot;Jamal&quot;, &quot;Eli&quot;, …
## $ sex       &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, …
## $ cm_height &lt;dbl&gt; 190, 168, 165, 172, 174, 179, 185, 180, …</code></pre>
<p>The sex and part_id (participant identification number) columns are categorical variables. We need to let the R know this fact. We do so by converting them to “factor” columns with the command below.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="scaling.html#cb226-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="ot">&lt;-</span> height_data <span class="sc">%&gt;%</span></span>
<span id="cb226-2"><a href="scaling.html#cb226-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">part_id =</span> <span class="fu">as_factor</span>(part_id),</span>
<span id="cb226-3"><a href="scaling.html#cb226-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sex =</span> <span class="fu">as_factor</span>(sex))</span></code></pre></div>
<p>Using glimpse() again we see these columns have fct after them indicating that they are factors (i.e., categorical variables):</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="scaling.html#cb227-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(height_data)</span></code></pre></div>
<pre><code>## Rows: 20
## Columns: 4
## $ part_id   &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1…
## $ name      &lt;chr&gt; &quot;John&quot;, &quot;Jim&quot;, &quot;Steve&quot;, &quot;Jamal&quot;, &quot;Eli&quot;, …
## $ sex       &lt;fct&gt; male, male, male, male, male, male, male…
## $ cm_height &lt;dbl&gt; 190, 168, 165, 172, 174, 179, 185, 180, …</code></pre>
</div>
<div id="viewing-data" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Viewing data</h2>
<p>We can view all of the data we entered with the commands below. In these commands, we first specify the data, height_data that we want displayed. Following this we use the “and then” verb represented by “%&gt;%.” Finally, we indicate that before it is displayed the height_data should be converted to a data frame, using as.data.frame() command. Later will will include additional commands in the display script below to obtain particular rows or columns from the data set. You can read the code below as “height_data and then as.data.frame().”</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="scaling.html#cb229-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="sc">%&gt;%</span> </span>
<span id="cb229-2"><a href="scaling.html#cb229-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##    part_id     name    sex cm_height
## 1        1     John   male       190
## 2        2      Jim   male       168
## 3        3    Steve   male       165
## 4        4    Jamal   male       172
## 5        5      Eli   male       174
## 6        6     Sean   male       179
## 7        7  Basheer   male       185
## 8        8     Matt   male       180
## 9        9      Tim   male       173
## 10      10     Rick   male       183
## 11      11     Jane female       174
## 12      12    Nancy female       161
## 13      13      Sue female       174
## 14      14    Maggy female       169
## 15      15    Aisha female       161
## 16      16     Saba female       172
## 17      17     Katy female       173
## 18      18 Jennifer female       169
## 19      19  Natalie female       165
## 20      20    Megan female       161</code></pre>
</div>
<div id="summary-statistics" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Summary statistics</h2>
<p>To obtain the mean and standard deviation (population formula) for each column in the data set we use the commands below. These are explained in the previous “Handling data with the tidyverse” chapter. You can see in the code below that by specifying, in the summarise() command, .cols = where(is.numeric) that we obtain descriptive statistics for any numeric column.</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="scaling.html#cb231-1" aria-hidden="true" tabindex="-1"></a>desired_descriptives <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb231-2"><a href="scaling.html#cb231-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="sc">~</span><span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb231-3"><a href="scaling.html#cb231-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_pop =</span> <span class="sc">~</span><span class="fu">sd_pop</span>(.x)</span>
<span id="cb231-4"><a href="scaling.html#cb231-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb231-5"><a href="scaling.html#cb231-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb231-6"><a href="scaling.html#cb231-6" aria-hidden="true" tabindex="-1"></a>height_data <span class="sc">%&gt;%</span></span>
<span id="cb231-7"><a href="scaling.html#cb231-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">where</span>(is.numeric),</span>
<span id="cb231-8"><a href="scaling.html#cb231-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">.fns =</span> desired_descriptives,</span>
<span id="cb231-9"><a href="scaling.html#cb231-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb231-10"><a href="scaling.html#cb231-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   cm_height_mean cm_height_sd_pop
## 1          172.4            7.851</code></pre>
</div>
<div id="converting-units" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> Converting units</h2>
<div id="inches" class="section level3" number="6.5.1">
<h3><span class="header-section-number">6.5.1</span> Inches</h3>
<p>In the previous section we have examined participant heights using centimeters (cm). We can, however, express participants heights using inches. It’s a simple process to convert cm to inches - we simply divide by 2.54. If you examine the ruler below you can see that 2.54 cm corresponds to 1 inch.</p>
<p><img src="ch_scaling/images/ruler.png" width="50%" /></p>
<div id="hand-calculation" class="section level4" number="6.5.1.1">
<h4><span class="header-section-number">6.5.1.1</span> Hand calculation</h4>
<p>We can express this conversion more formally with equations below. In this Equation we use <span class="math inline">\(X_i\)</span> to indicate the height (in cm) of the <span class="math inline">\(i^{th}\)</span> person in a set of N people.</p>
<p><span class="math display">\[
\begin{aligned}
\text{height in inches for the ith person} = \frac{X_i}{2.54}\\
\end{aligned}
\]</span></p>
<p>In the context of our data we can convert John’s height of 190 cm to inches using this process:</p>
<p><span class="math display">\[
\begin{aligned}
\text{height in inches for the ith person} &amp;= \frac{X_i}{2.54}\\
&amp;= \frac{\text{John&#39;s height in cm}}{2.54}\\
&amp;= \frac{190}{2.54}\\
&amp;= 74.80315
\end{aligned}
\]</span></p>
<p>Thus, John is 190 cm tall or 74.8 inches tall. Of course, John’s height has not changed because we are now expressing it in inches. All that has changed is the units we use to indicate his height.</p>
</div>
<div id="r-calculation" class="section level4" number="6.5.1.2">
<h4><span class="header-section-number">6.5.1.2</span> R calculation</h4>
<p>We can use R to calculate the height in inches for everyone in the data set using the code below. The mutate() command creates a new column, inch_height, that contains each persons height in inches.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="scaling.html#cb233-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="ot">&lt;-</span> height_data <span class="sc">%&gt;%</span></span>
<span id="cb233-2"><a href="scaling.html#cb233-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">inch_height =</span> cm_height <span class="sc">/</span> <span class="fl">2.54</span>)</span></code></pre></div>
<p>We can see the new column (inches) with the code below. The code takes the height_data “and then” (i.e., %&gt;%) converts it to a data frame prior to displaying it on the screen. We convert it to a data frame prior to displaying in on the screen to increase the number of decimals displayed.</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="scaling.html#cb234-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="sc">%&gt;%</span> </span>
<span id="cb234-2"><a href="scaling.html#cb234-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##    part_id     name    sex cm_height inch_height
## 1        1     John   male       190       74.80
## 2        2      Jim   male       168       66.14
## 3        3    Steve   male       165       64.96
## 4        4    Jamal   male       172       67.72
## 5        5      Eli   male       174       68.50
## 6        6     Sean   male       179       70.47
## 7        7  Basheer   male       185       72.83
## 8        8     Matt   male       180       70.87
## 9        9      Tim   male       173       68.11
## 10      10     Rick   male       183       72.05
## 11      11     Jane female       174       68.50
## 12      12    Nancy female       161       63.39
## 13      13      Sue female       174       68.50
## 14      14    Maggy female       169       66.54
## 15      15    Aisha female       161       63.39
## 16      16     Saba female       172       67.72
## 17      17     Katy female       173       68.11
## 18      18 Jennifer female       169       66.54
## 19      19  Natalie female       165       64.96
## 20      20    Megan female       161       63.39</code></pre>
</div>
<div id="summary" class="section level4" number="6.5.1.3">
<h4><span class="header-section-number">6.5.1.3</span> Summary</h4>
<p>We can obtain the mean and standard deviation (population formula) for all numeric columns (i.e, the cm and inches columns) using the summarise() command below. Note that we added “%&gt;% t()” after the as.data.frame() to change the orientation of the output. This extra command simply transposes the output row to a column to make it easier to read. You can read the code in the extra command, “%&gt;% t(),” as “and then transpose.”</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="scaling.html#cb236-1" aria-hidden="true" tabindex="-1"></a>desired_descriptives <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb236-2"><a href="scaling.html#cb236-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="sc">~</span><span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb236-3"><a href="scaling.html#cb236-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_pop =</span> <span class="sc">~</span><span class="fu">sd_pop</span>(.x)</span>
<span id="cb236-4"><a href="scaling.html#cb236-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb236-5"><a href="scaling.html#cb236-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb236-6"><a href="scaling.html#cb236-6" aria-hidden="true" tabindex="-1"></a>height_data <span class="sc">%&gt;%</span></span>
<span id="cb236-7"><a href="scaling.html#cb236-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">where</span>(is.numeric),</span>
<span id="cb236-8"><a href="scaling.html#cb236-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">.fns =</span> desired_descriptives,</span>
<span id="cb236-9"><a href="scaling.html#cb236-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb236-10"><a href="scaling.html#cb236-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> <span class="fu">t</span>()</span></code></pre></div>
<pre><code>##                       [,1]
## cm_height_mean     172.400
## cm_height_sd_pop     7.851
## inch_height_mean    67.874
## inch_height_sd_pop   3.091</code></pre>
<p>By converting heights in centimeters to heights in inches we are simply changed the units used to represent those heights. The conversion did not change anyone’s actual height. Nor did this conversion change the height of one person relative to another person – all we did was change the units used to represent the heights. The summary table below illustrates how the means and standard deviations are different for the different units of measurement - despite representing the same set of people who’s heights where not influenced by the conversion.</p>
<p>Both inches and centimeters are ratio-scale scale heights. The zero point on those measurement scales is meaningful and not arbitrary. In the next section we examine two approaches to representing heights (<em>z</em>-scores and T-scores) for which the zero-point depends on the nature of the data. This initially seems like an odd approach - but you will that there are many benefits to expressing scores/heights in this manner.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
unit
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd_pop
</th>
<th style="text-align:right;">
N
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cm_height
</td>
<td style="text-align:right;">
172.40
</td>
<td style="text-align:right;">
7.851
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
inch_height
</td>
<td style="text-align:right;">
67.87
</td>
<td style="text-align:right;">
3.091
</td>
<td style="text-align:right;">
20
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="z-scores" class="section level3" number="6.5.2">
<h3><span class="header-section-number">6.5.2</span> <em>z</em>-scores</h3>
<p>One alternative approach to representing scores, or more specifically heights, is using <em>z</em>-scores. With <em>z</em>-scores each person’s score (i.e., height) is represented relative to a frame of reference. More specifically, scores are represented relative to a particular mean and standard deviation. Often the frame of reference (i.e., mean and standard deviation) used to calculate <em>z</em>-scores is the mean and standard deviation of all the participants in a data set - though we will see later other frames of reference are possible.</p>
<p>The advantage of <em>z</em>-scores is that by simply looking a person’s <em>z</em>-score we can tell if they are above or below the mean for the frame of reference. Specifically, when a <em>z</em>-score is positive this indicates that a person is above the mean of the frame of reference; likewise, when a <em>z</em>-score is negative this indicates that the person is below the mean of the frame of reference. The magnitude of the <em>z</em>-score indicates how distant a person is from the mean of the frame of reference in standard deviation units.</p>
<p>We examine our data we find that John has a height of 190 cm. We use the heights of the people in our data set as a frame of reference. Using all of the people in our data set we calculate a mean height of 173.3 cm and a standard deviation (population formula) of 8.013114 cm. We use these values as a frame of reference when calculating John’s <em>z</em>-score.</p>
<p>Using our data set as a frame of reference, John’s height of 190 cm can be expressed as a <em>z</em>-score of 2.084084 (calculation below). Because this is a positive value we know John is taller than the average person in the frame of reference (i.e, in our data set). Likewise, the magnitude of the <em>z</em>-score, 2.084084, indicates that John is 2.084084 standard deviations taller than the average person in our frame of reference (i.e., the people in our data set). This means that John is quite tall - <strong>relative</strong> to the other people in our data set. The key word here is <strong>relative</strong> - <em>z</em>-scores provide information about a person’s score relative to some frame of reference. In this example, the frame of reference was all of the people in our data set.</p>
<div id="hand-calculation-1" class="section level4" number="6.5.2.1">
<h4><span class="header-section-number">6.5.2.1</span> Hand calculation</h4>
<p>Let’s walk through converting John’s height from cm to a <em>z</em>-score. The first step is determining the frame of reference we want to use to calculate the <em>z</em>-score. As noted previously, we use the entire data set a frame of reference. That means we need the mean and standard deviation of the entire data to calculate the <em>z</em>-score.</p>
<p>For the entire data set, the mean and standard deviation (population formula) in centimeters are illustrated below (obtained via the R-code in the previous section).</p>
<p><span class="math display">\[
\begin{aligned}
\overline{X} &amp;= 173.3 \\
S_X &amp;= 8.013114 \\
\end{aligned}
\]</span></p>
<p>To convert a person’s original score to a <em>z</em>-score we use the formula below. Notice that the formula contains their original score (i.e., <span class="math inline">\(X_i\)</span>) as well and the mean (i.e., <span class="math inline">\(\overline{X}\)</span>) and standard deviation (i.e., <span class="math inline">\(S_X\)</span>) of the frame of reference.</p>
<p><span class="math display">\[
\begin{aligned}
z_i = \frac{X_i - \overline{X}}{S_X}\\
\end{aligned}
\]</span></p>
<p>Here is the calculation for John:</p>
<p><span class="math display">\[
\begin{aligned}
z_i &amp;= \frac{X_i - \overline{X}}{S_X}\\
&amp;= \frac{\text{(John&#39;s height in cm)} - \overline{X}}{S_X}\\
&amp;= \frac{190 - 173.3}{8.013114}\\
&amp;= \frac{16.7}{8.013114}\\
&amp;= 2.084084\\
\end{aligned}
\]</span></p>
<p>As noted previously: Because this is a positive value we know John is taller than the average person in the frame of reference (i.e, the people in our data set). Likewise, the magnitude of the <em>z</em>-score, 2.084084, indicates that John is 2.084084 standard deviations taller than the average person in our frame of reference (i.e., the people in our data set). This means that John is quite tall - <strong>relative</strong> to the other people in our data set. The key word here is <strong>relative</strong> - <em>z</em>-scores provide information about a person’s score relative to some frame of reference. In this example, the frame of reference was all of the people in the data set.</p>
</div>
<div id="r-calculation-1" class="section level4" number="6.5.2.2">
<h4><span class="header-section-number">6.5.2.2</span> R calculation</h4>
<p>We can use R to calculate the <em>z</em>-score for everyone in our data set. Previously, we found:</p>
<p><span class="math display">\[
\begin{aligned}
\overline{X} &amp;= 173.3 \\
S_X &amp;= 8.013114 \\
\end{aligned}
\]</span></p>
<p>Therefore, we write the code below to create <em>z</em>-scores with the entire data set as the frame of reference. More specifically, we are using the mutate() command to create a new colum called z_data. We use this column name to reflect the fact that the we are using the entire data set as the frame of reference for the <em>z</em>-score. Also notice how the formula in the mutate() command corresponds to the formula used in the hand calculation above.</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="scaling.html#cb238-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="ot">&lt;-</span> height_data <span class="sc">%&gt;%</span></span>
<span id="cb238-2"><a href="scaling.html#cb238-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_data =</span> (  cm_height <span class="sc">-</span> <span class="fl">173.3</span>  )  <span class="sc">/</span>  <span class="fl">8.013114</span>  )</span></code></pre></div>
<p>Note that in the mutate() command above we specified the mean and standard deviation using specific values (i.e., 173.3 and 8.013114). However, because the mean and standard eviation came from the same data set for which we are calculating the <em>z</em>-score we could have used the more advanced code below. The more advanced code is harder to follow - so for the remainder of this chapter will continue to specify the specific values use in <em>z</em>-score calculations rather than used the more advanced code style below.</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="scaling.html#cb239-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="ot">&lt;-</span> height_data <span class="sc">%&gt;%</span></span>
<span id="cb239-2"><a href="scaling.html#cb239-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_data =</span> (  cm_height <span class="sc">-</span> <span class="fu">mean</span>(cm_height)  )  <span class="sc">/</span>  <span class="fu">sd_pop</span>(cm_height)  )</span></code></pre></div>
<p>Once we have obtained the <em>z</em>-score we can inspect them on the screen. We do so with the code below. Notice that each person now has a <em>z</em>-score. Recall, <em>z</em>-scores below zero indicate a height below the mean of the data set (i.e., the frame of reference) whereas <em>z</em>-scores above zero indicate a height above the mean for the data set.</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="scaling.html#cb240-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="sc">%&gt;%</span> </span>
<span id="cb240-2"><a href="scaling.html#cb240-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##    part_id     name    sex cm_height inch_height   z_data
## 1        1     John   male       190       74.80  2.08408
## 2        2      Jim   male       168       66.14 -0.66142
## 3        3    Steve   male       165       64.96 -1.03580
## 4        4    Jamal   male       172       67.72 -0.16223
## 5        5      Eli   male       174       68.50  0.08736
## 6        6     Sean   male       179       70.47  0.71133
## 7        7  Basheer   male       185       72.83  1.46011
## 8        8     Matt   male       180       70.87  0.83613
## 9        9      Tim   male       173       68.11 -0.03744
## 10      10     Rick   male       183       72.05  1.21052
## 11      11     Jane female       174       68.50  0.08736
## 12      12    Nancy female       161       63.39 -1.53498
## 13      13      Sue female       174       68.50  0.08736
## 14      14    Maggy female       169       66.54 -0.53662
## 15      15    Aisha female       161       63.39 -1.53498
## 16      16     Saba female       172       67.72 -0.16223
## 17      17     Katy female       173       68.11 -0.03744
## 18      18 Jennifer female       169       66.54 -0.53662
## 19      19  Natalie female       165       64.96 -1.03580
## 20      20    Megan female       161       63.39 -1.53498</code></pre>
<p>It’s easier to see the value of <em>z</em>-scores if we sort the data prior to displaying it on the screen. We sort the data using the arrange() command. Specifically, by using the arrange(z_data) command we sort the data by the <em>z</em>-score column prior to displaying it. In the output below, it’s easy to see that everyone with a <em>z</em>-score less than zero (i.e., a negative <em>z</em>-score) has a height lower than the mean for the entire data set (i.e., 193.3 cm) - which is our frame of reference.</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="scaling.html#cb242-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="sc">%&gt;%</span> </span>
<span id="cb242-2"><a href="scaling.html#cb242-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(z_data) <span class="sc">%&gt;%</span></span>
<span id="cb242-3"><a href="scaling.html#cb242-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##    part_id     name    sex cm_height inch_height   z_data
## 1       12    Nancy female       161       63.39 -1.53498
## 2       15    Aisha female       161       63.39 -1.53498
## 3       20    Megan female       161       63.39 -1.53498
## 4        3    Steve   male       165       64.96 -1.03580
## 5       19  Natalie female       165       64.96 -1.03580
## 6        2      Jim   male       168       66.14 -0.66142
## 7       14    Maggy female       169       66.54 -0.53662
## 8       18 Jennifer female       169       66.54 -0.53662
## 9        4    Jamal   male       172       67.72 -0.16223
## 10      16     Saba female       172       67.72 -0.16223
## 11       9      Tim   male       173       68.11 -0.03744
## 12      17     Katy female       173       68.11 -0.03744
## 13       5      Eli   male       174       68.50  0.08736
## 14      11     Jane female       174       68.50  0.08736
## 15      13      Sue female       174       68.50  0.08736
## 16       6     Sean   male       179       70.47  0.71133
## 17       8     Matt   male       180       70.87  0.83613
## 18      10     Rick   male       183       72.05  1.21052
## 19       7  Basheer   male       185       72.83  1.46011
## 20       1     John   male       190       74.80  2.08408</code></pre>
</div>
<div id="summary-1" class="section level4" number="6.5.2.3">
<h4><span class="header-section-number">6.5.2.3</span> Summary</h4>
<p>We can obtain the mean and standard deviation (population formula) for all numeric columns (i.e, the cm, inches, and <em>z</em>-score columns) using the summarise() command below.</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="scaling.html#cb244-1" aria-hidden="true" tabindex="-1"></a>desired_descriptives <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb244-2"><a href="scaling.html#cb244-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="sc">~</span><span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb244-3"><a href="scaling.html#cb244-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_pop =</span> <span class="sc">~</span><span class="fu">sd_pop</span>(.x)</span>
<span id="cb244-4"><a href="scaling.html#cb244-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb244-5"><a href="scaling.html#cb244-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb244-6"><a href="scaling.html#cb244-6" aria-hidden="true" tabindex="-1"></a>height_data <span class="sc">%&gt;%</span></span>
<span id="cb244-7"><a href="scaling.html#cb244-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">where</span>(is.numeric),</span>
<span id="cb244-8"><a href="scaling.html#cb244-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">.fns =</span> desired_descriptives,</span>
<span id="cb244-9"><a href="scaling.html#cb244-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb244-10"><a href="scaling.html#cb244-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> <span class="fu">t</span>()</span></code></pre></div>
<pre><code>##                        [,1]
## cm_height_mean     172.4000
## cm_height_sd_pop     7.8511
## inch_height_mean    67.8740
## inch_height_sd_pop   3.0910
## z_data_mean         -0.1123
## z_data_sd_pop        0.9798</code></pre>
<p>This output may be confusing. Consider the cm_height_mean of 1.733e+02 the e+02 means move the decimal two places to the right. Likewise, consider the z_data_mean of -1.414e-15 the e-15 means move the decimal 15 places to the left.</p>
<p>We can see this information presented in table form below (decimals adjusted). You can see that <em>z</em>-scores are simply a way of representing heights with a different type of unit. By converting heights to <em>z</em>-scores we have not changed anyone’s actual height. Nor have we changed the relative heights of any two individuals. We have only changed the units used to express those heights.</p>
<p>A special case: Also notice that when we use the data set itself as the frame of reference something interesting happens with <em>z</em>-scores. Specifically, the <em>z</em>-score column has a mean of zero and a standard deviation of 1.0. This won’t always be the case.</p>
<p>Consider two different situations. In situation 1, imagine we obtained a subset of the people in our the current data set (after the <em>z</em>-scores were calculated). If we were to calculate, for the this subset of people, the mean and standard deviation of the <em>z</em>-score column the values would not be 0 and 1, respectively. In situation 2, imagine we have the full data set, and the we calculated <em>z</em>-scores using a different frame of reference. That is we used a mean and standard deviation as the frame of reference there were not obtained from our data. In this scenario, if we calculated <em>z</em>-scores for everyone, the mean and standard deviation of the <em>z</em>-score column would likely not be 0 and 1, respectively.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
unit
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd_pop
</th>
<th style="text-align:right;">
N
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cm_height
</td>
<td style="text-align:right;">
172.400
</td>
<td style="text-align:right;">
7.851
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
inch_height
</td>
<td style="text-align:right;">
67.874
</td>
<td style="text-align:right;">
3.091
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
z_data
</td>
<td style="text-align:right;">
-0.112
</td>
<td style="text-align:right;">
0.980
</td>
<td style="text-align:right;">
20
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="t-scores" class="section level3" number="6.5.3">
<h3><span class="header-section-number">6.5.3</span> T-scores</h3>
<p>T-scores are simply another unit for representing scores. Do not confuse the T-score with the <em>t</em>-value in inferential statistics (a very different number).</p>
<p>T-scores are very similar to <em>z</em>-scores - the provide scores for each person relative to a frame of reference. With <em>z</em>-scores we use 0 to indicate the mean of the frame of reference and 1 to indicate the standard deviation of the frame of reference. With T-scores we use 50 to indicate the mean of the frame of reference and 10 to indicate the standard deviation of the frame of reference.</p>
<p>When T-scores are greater than 50 this indicates that a person is above the mean of the frame of reference; likewise, when a T-scores is less than 50 this indicates that a person is below the mean of the frame of reference. Every difference of 10 units from 50 represents a standard deviation. Thus, a person with a T-score of 60 is one standard deviation above the mean of the frame of reference.</p>
<p>In we examine our data we find that John has a height of 190 cm. We use the heights of the people in our data set as a frame of reference. To create a T-score for John we first need to convert his height in cm to a <em>z</em>-score. Following this, we convert his <em>z</em>-score to a T-score. Fortunately, we’ve already calculated John’s height in <em>z</em>-score form for this frame of reference as 2.084084. We convert that number (calculation below) to a T-score of 70.84084. Because this T-score if greater than 50 we know John is taller than the average person in the frame of reference (i.e, the people in our data set). Likewise, the magnitude of the T-score is roughly 20 higher (i.e., 2* 10 higher) than 50 we know John is about 2 standard deviations taller than the mean for the frame of reference.</p>
<div id="hand-calculation-2" class="section level4" number="6.5.3.1">
<h4><span class="header-section-number">6.5.3.1</span> Hand calculation</h4>
<p>Let’s walk through converting John’s height as a <em>z</em>-score to a T-score. The <em>z</em>-score used our entire data set as the frame of reference - so that will be the frame of reference for the T-score as well.</p>
<p>The generic formula for converting <em>z</em>-scores to T-scores is below. In this formula <span class="math inline">\(T_i\)</span> represents the new T-score whereas <span class="math inline">\(z_i\)</span> represents the previously calculated <em>z</em>-score for that person. We need to calculate the <em>z</em>-score as a first step in calculating a T-score. You can see that we simply multiply a <em>z</em>-score by 10 and add 50 to get a T-score. The resulting T-score has the same frame of reference as the <em>z</em>-score used to calculate it.</p>
<p><span class="math display">\[
\begin{aligned}
T_i = z_i \times 10 + 50\\
\end{aligned}
\]</span></p>
<p>Here is the calculation for John:</p>
<p><span class="math display">\[
\begin{aligned}
T_i &amp;= z_i \times 10 + 50\\
&amp;= \text{(John&#39;s height as a z-score)} \times 10 + 50\\
&amp;= 2.084084 * 10 + 50\\
&amp;= 70.84084\\
\end{aligned}
\]</span></p>
<p>As noted previously: Because this T-score if greater than 50 we know John is taller than the average person in the frame of reference (i.e, the people in our data set). Likewise, the magnitude of the T-score is roughly 20 higher (i.e., 2* 10 higher) than 50 we know John is about 2 standard deviations taller than the mean for the frame of reference.</p>
</div>
<div id="r-calculation-2" class="section level4" number="6.5.3.2">
<h4><span class="header-section-number">6.5.3.2</span> R calculation</h4>
<p>We can use this same approach in R to convert all of the <em>z</em>-scores to T-scores. We use the mutate() commmand to create a new column called T_data. We use this name to indicate the the frame of reference for the T-score is the data set (i.e., T_data). Notice how the mutate() command below is just the R version of the above formula for converting <em>z</em>-scores to T-scores.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="scaling.html#cb246-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="ot">&lt;-</span> height_data <span class="sc">%&gt;%</span></span>
<span id="cb246-2"><a href="scaling.html#cb246-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">T_data =</span>  z_data <span class="sc">*</span> <span class="dv">10</span> <span class="sc">+</span> <span class="dv">50</span> )</span></code></pre></div>
<p>After running the above command, we have a new column called T_data which contains the T-score for each person. We can use the code below to display the height data. We use the select command() - specifically select(-part_id, -sex) to omit the part_id and sex columns from the output - it’s too wide otherwise. We use the arrange(T_data) command to sort the heights by T-score prior to displaying them. Inspecting the output you see the order of the rows is the same as when we sorted by <em>z</em>-score.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="scaling.html#cb247-1" aria-hidden="true" tabindex="-1"></a>height_data <span class="sc">%&gt;%</span></span>
<span id="cb247-2"><a href="scaling.html#cb247-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>part_id, <span class="sc">-</span>sex) <span class="sc">%&gt;%</span></span>
<span id="cb247-3"><a href="scaling.html#cb247-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(T_data) <span class="sc">%&gt;%</span></span>
<span id="cb247-4"><a href="scaling.html#cb247-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##        name cm_height inch_height   z_data T_data
## 1     Nancy       161       63.39 -1.53498  34.65
## 2     Aisha       161       63.39 -1.53498  34.65
## 3     Megan       161       63.39 -1.53498  34.65
## 4     Steve       165       64.96 -1.03580  39.64
## 5   Natalie       165       64.96 -1.03580  39.64
## 6       Jim       168       66.14 -0.66142  43.39
## 7     Maggy       169       66.54 -0.53662  44.63
## 8  Jennifer       169       66.54 -0.53662  44.63
## 9     Jamal       172       67.72 -0.16223  48.38
## 10     Saba       172       67.72 -0.16223  48.38
## 11      Tim       173       68.11 -0.03744  49.63
## 12     Katy       173       68.11 -0.03744  49.63
## 13      Eli       174       68.50  0.08736  50.87
## 14     Jane       174       68.50  0.08736  50.87
## 15      Sue       174       68.50  0.08736  50.87
## 16     Sean       179       70.47  0.71133  57.11
## 17     Matt       180       70.87  0.83613  58.36
## 18     Rick       183       72.05  1.21052  62.11
## 19  Basheer       185       72.83  1.46011  64.60
## 20     John       190       74.80  2.08408  70.84</code></pre>
<p>When you examined the output above did you notice correspondence between <em>z</em>-scores and T-scores. Whenever a <em>z</em>-score was less than 0 the corresponding T-score for that person was less than 50. Both of these values indicate a person had a height lower than the mean, 193.3 cm, for the reference group (the entire data set).</p>
</div>
<div id="summary-2" class="section level4" number="6.5.3.3">
<h4><span class="header-section-number">6.5.3.3</span> Summary</h4>
<p>We can obtain the mean and standard deviation (population formula) for all numeric columns (i.e, the cm, inches, <em>z</em>-score, and T-score columns) using the summarise() command below.</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="scaling.html#cb249-1" aria-hidden="true" tabindex="-1"></a>desired_descriptives <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb249-2"><a href="scaling.html#cb249-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="sc">~</span><span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb249-3"><a href="scaling.html#cb249-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_pop =</span> <span class="sc">~</span><span class="fu">sd_pop</span>(.x)</span>
<span id="cb249-4"><a href="scaling.html#cb249-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb249-5"><a href="scaling.html#cb249-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb249-6"><a href="scaling.html#cb249-6" aria-hidden="true" tabindex="-1"></a>height_data <span class="sc">%&gt;%</span></span>
<span id="cb249-7"><a href="scaling.html#cb249-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">where</span>(is.numeric),</span>
<span id="cb249-8"><a href="scaling.html#cb249-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">.fns =</span> desired_descriptives,</span>
<span id="cb249-9"><a href="scaling.html#cb249-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb249-10"><a href="scaling.html#cb249-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> <span class="fu">t</span>()</span></code></pre></div>
<pre><code>##                        [,1]
## cm_height_mean     172.4000
## cm_height_sd_pop     7.8511
## inch_height_mean    67.8740
## inch_height_sd_pop   3.0910
## z_data_mean         -0.1123
## z_data_sd_pop        0.9798
## T_data_mean         48.8768
## T_data_sd_pop        9.7978</code></pre>
<p>We can see this information presented in table form below (decimals adjusted). You can see that T-scores are simply a way of representing heights with a different type of unit. By converting heights to T-scores we have not changed anyone’s actual height. Nor have we changed the relative heights of any two individuals. We have only changed the units used to express those heights.</p>
<p>A special case: Also notice that when we use the data set itself as the frame of reference something interesting happens with T-scores. Specifically, the T-score column has a mean of 50 and a standard deviation of 10. This won’t always be the case. If we use a frame of reference other than our data set, the mean and standard deviation of T-scores in our data set will not necessarily be equal to 50 and 10, respectively.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
unit
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd_pop
</th>
<th style="text-align:right;">
N
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cm_height
</td>
<td style="text-align:right;">
172.400
</td>
<td style="text-align:right;">
7.851
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
inch_height
</td>
<td style="text-align:right;">
67.874
</td>
<td style="text-align:right;">
3.091
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
z_data
</td>
<td style="text-align:right;">
-0.112
</td>
<td style="text-align:right;">
0.980
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
T_data
</td>
<td style="text-align:right;">
48.877
</td>
<td style="text-align:right;">
9.798
</td>
<td style="text-align:right;">
20
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="frame-of-references" class="section level2" number="6.6">
<h2><span class="header-section-number">6.6</span> Frame of references</h2>
<div id="all-participants" class="section level3" number="6.6.1">
<h3><span class="header-section-number">6.6.1</span> All participants</h3>
<p>In the above exercises we used the entire data set as our frame of reference. That is, the <em>z</em>-score column, z_data, was calculated using the mean and standard deviation for the data set (i.e., all participants in the data set). These values are presented below:</p>
<p><span class="math display">\[
\begin{aligned}
\overline{X} &amp;= 173.3 \\
S_X &amp;= 8.013114 \\
\end{aligned}
\]</span></p>
<p>Recall, that these mean and standard deviation values were used to calculate John’s <em>z</em>-score (and everyone else’s <em>z</em>-scores too):</p>
<p><span class="math display">\[
\begin{aligned}
z_i &amp;= \frac{X_i - \overline{X}}{S_X}\\
&amp;= \frac{\text{(John&#39;s height in cm)} - \overline{X}}{S_X}\\
&amp;= \frac{190 - 173.3}{8.013114}\\
&amp;= \frac{16.7}{8.013114}\\
&amp;= 2.084084\\
\end{aligned}
\]</span></p>
</div>
<div id="male-reference" class="section level3" number="6.6.2">
<h3><span class="header-section-number">6.6.2</span> Male reference</h3>
<p>The frame of reference doesn’t have to be the entire data set. Image we wanted to examine just the males in the data set. We could calculate a z-score using just the male data so the <em>z</em>-score would indicate how tall a male is <strong>relative</strong> to other other males. Depending on our research question it might be quite helpful to express male heights (i.e. male scores) in this way.</p>
<p>Let’s use only males as our frame of reference. We can do by creating a new data set that contains only the males from our original data set. Below we create a data set called male_height_data. The code uses the filter(sex == “male”) command to obtain only the rows where the sex columns indicates the participant is male (notice the use of the double equals sign, ==, to indicate “is equal to”).</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="scaling.html#cb251-1" aria-hidden="true" tabindex="-1"></a>male_height_data <span class="ot">&lt;-</span> height_data <span class="sc">%&gt;%</span></span>
<span id="cb251-2"><a href="scaling.html#cb251-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">&quot;male&quot;</span>) </span></code></pre></div>
<p>You can confirm we have only males in the new data set by inspecting the data. As before, to make the output easier to read we omit some columns from the output using the select() commmand. Additionaly, use use the arrange() command or sort the output by the cm_height column. The output confirms we only have male in the new data set.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="scaling.html#cb252-1" aria-hidden="true" tabindex="-1"></a>male_height_data <span class="sc">%&gt;%</span></span>
<span id="cb252-2"><a href="scaling.html#cb252-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>part_id, <span class="sc">-</span>T_data) <span class="sc">%&gt;%</span></span>
<span id="cb252-3"><a href="scaling.html#cb252-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cm_height) <span class="sc">%&gt;%</span></span>
<span id="cb252-4"><a href="scaling.html#cb252-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##       name  sex cm_height inch_height   z_data
## 1    Steve male       165       64.96 -1.03580
## 2      Jim male       168       66.14 -0.66142
## 3    Jamal male       172       67.72 -0.16223
## 4      Tim male       173       68.11 -0.03744
## 5      Eli male       174       68.50  0.08736
## 6     Sean male       179       70.47  0.71133
## 7     Matt male       180       70.87  0.83613
## 8     Rick male       183       72.05  1.21052
## 9  Basheer male       185       72.83  1.46011
## 10    John male       190       74.80  2.08408</code></pre>
<p>For this all male data set, we obtain the mean and standard standard deviation (population formula) for the cm_height column using the code below. You can see in the code below that by specifying, in the summarise() command, .cols = starts_with(“cm_”) that we obtain descriptive statistics only for columns that begin with cm_ (which is a single column).</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="scaling.html#cb254-1" aria-hidden="true" tabindex="-1"></a>desired_descriptives <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb254-2"><a href="scaling.html#cb254-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="sc">~</span><span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb254-3"><a href="scaling.html#cb254-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd_pop =</span> <span class="sc">~</span><span class="fu">sd_pop</span>(.x)</span>
<span id="cb254-4"><a href="scaling.html#cb254-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb254-5"><a href="scaling.html#cb254-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb254-6"><a href="scaling.html#cb254-6" aria-hidden="true" tabindex="-1"></a>male_height_data <span class="sc">%&gt;%</span></span>
<span id="cb254-7"><a href="scaling.html#cb254-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;cm_&quot;</span>),</span>
<span id="cb254-8"><a href="scaling.html#cb254-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">.fns =</span> desired_descriptives,</span>
<span id="cb254-9"><a href="scaling.html#cb254-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb254-10"><a href="scaling.html#cb254-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> <span class="fu">t</span>()</span></code></pre></div>
<pre><code>##                     [,1]
## cm_height_mean   176.900
## cm_height_sd_pop   7.463</code></pre>
<p>In table form we see that for males the mean and standard deviation are 178.700 and 6.558, respectively.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
unit
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd_pop
</th>
<th style="text-align:right;">
N
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cm_height
</td>
<td style="text-align:right;">
176.90
</td>
<td style="text-align:right;">
7.463
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
inch_height
</td>
<td style="text-align:right;">
69.65
</td>
<td style="text-align:right;">
2.938
</td>
<td style="text-align:right;">
10
</td>
</tr>
</tbody>
</table>
<div id="hand-calculation-3" class="section level4" number="6.6.2.1">
<h4><span class="header-section-number">6.6.2.1</span> Hand calculation</h4>
<p>To calculate a z-score using a male only frame of reference we need the mean and standard deviation (population formula) for males. These are presented below.</p>
<p><span class="math display">\[
\begin{aligned}
\overline{X_{males}} &amp;= 178.7 \\
S_{males} &amp;= 6.558 \\
\end{aligned}
\]</span></p>
<p>Previously, when we used the whole data set as a frame of reference we found that John’s <em>z</em>-score was 2.084084. But now we want to calculate a <em>z</em>-score for John using only the males as a frame of reference. Therefore, we calculate his <em>z</em>-score using the mean and standard deviation for only males; as illustrated below:</p>
<p><span class="math display">\[
\begin{aligned}
z_i &amp;= \frac{X_i - \overline{X_{males}}}{S_{males}}\\
&amp;= \frac{\text{(John&#39;s height in cm)} - \overline{X_{males}}}{S_{males}}\\
&amp;= \frac{190 - 178.7}{6.558}\\
&amp;= \frac{11.3}{6.558201}\\
&amp;= 1.723033\\
\end{aligned}
\]</span></p>
</div>
<div id="r-calculation-3" class="section level4" number="6.6.2.2">
<h4><span class="header-section-number">6.6.2.2</span> R calculation</h4>
<p>We can use R to calculate the <em>z</em>-score for our male only data set. We are using the mutate() command to create a new colum called z_data_males. We use this column name to reflect the fact that the we are using males from our data set as frame of reference for the new <em>z</em>-score column. Also notice how the formula in the mutate() command corresponds to the formula used in the hand calculation above.</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="scaling.html#cb256-1" aria-hidden="true" tabindex="-1"></a>male_height_data <span class="ot">&lt;-</span> male_height_data <span class="sc">%&gt;%</span></span>
<span id="cb256-2"><a href="scaling.html#cb256-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_data_males =</span> (cm_height <span class="sc">-</span> <span class="fl">178.7</span>)<span class="sc">/</span> <span class="fl">6.558</span>  )</span></code></pre></div>
<p>Once we have obtained the <em>z</em>-scores for males we can inspect them on the screen. We do so with the code below. In this code we use the select() command to omit a number of columns and focus on only the ones we are currently interested in. Likewise, we use arrange(z_data_males) to sort the data the z_data_males column.</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="scaling.html#cb257-1" aria-hidden="true" tabindex="-1"></a>male_height_data <span class="sc">%&gt;%</span></span>
<span id="cb257-2"><a href="scaling.html#cb257-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>part_id, <span class="sc">-</span>T_data, <span class="sc">-</span>inch_height) <span class="sc">%&gt;%</span></span>
<span id="cb257-3"><a href="scaling.html#cb257-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(z_data_males) <span class="sc">%&gt;%</span></span>
<span id="cb257-4"><a href="scaling.html#cb257-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##       name  sex cm_height   z_data z_data_males
## 1    Steve male       165 -1.03580     -2.08905
## 2      Jim male       168 -0.66142     -1.63159
## 3    Jamal male       172 -0.16223     -1.02165
## 4      Tim male       173 -0.03744     -0.86917
## 5      Eli male       174  0.08736     -0.71668
## 6     Sean male       179  0.71133      0.04575
## 7     Matt male       180  0.83613      0.19823
## 8     Rick male       183  1.21052      0.65569
## 9  Basheer male       185  1.46011      0.96066
## 10    John male       190  2.08408      1.72309</code></pre>
<p>Examine the last row of this sorted data set to see the two <em>z</em>-scores for John. When we used the entire data set as the frame of reference (z_data) John’s height was 2.08408. This value indicates that <strong>relative to the entire data set (males and females)</strong> John is 2.08408 standard deviations taller than the mean height for the data set. However, when we calculated a <em>z</em>-score for John <strong>relative to only males</strong>, the z_data_male column, his height is represented by a <em>z</em>-score of 1.72309. This indicates that John is 1.72309 standard deviations taller than the mean height for males. So relative to everyone John’s height is 2.08408 but relative to only males John’s height is 1.72309. John’s height is the same in both cases - only the frame of reference has changed. These two frames of reference allow us to see that relative to everyone (males and females) John is taller than when his height is considered in the context of only males (2.08408 vs 1.72309, respectively). Thus, we might think of John as an extraordinarily tall person in the context of everyone (males/females) in data set but as a somewhat large person in the context of the males in the data set.</p>
<p>Take a moment examine the <em>z</em>-scores for Basheer and Sean. Notice the large difference between z_data and z_data_male for these two individuals.</p>
</div>
<div id="summary-3" class="section level4" number="6.6.2.3">
<h4><span class="header-section-number">6.6.2.3</span> Summary</h4>
<p>For this male only data set, we can see the summary statistics below. Notice how the mean and standard deviation for the z_data column are no longer 0 and 1, respectively. These new values occur because we are examining a subset of the entire data set. In contrast, notice how for the z_data_male column the mean and standard deviation are 0 and 1.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
unit
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd_pop
</th>
<th style="text-align:right;">
N
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cm_height
</td>
<td style="text-align:right;">
176.900
</td>
<td style="text-align:right;">
7.463
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
z_data
</td>
<td style="text-align:right;">
0.449
</td>
<td style="text-align:right;">
0.931
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
z_data_males
</td>
<td style="text-align:right;">
-0.274
</td>
<td style="text-align:right;">
1.138
</td>
<td style="text-align:right;">
10
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="canadian-reference" class="section level3" number="6.6.3">
<h3><span class="header-section-number">6.6.3</span> Canadian reference</h3>
<p>So far we have used two frame of two frames of reference: the entire data and just males from the data set. Now let’s move on and consider a frame of reference that is not based our data.</p>
<p>Imagine that Statistics Canada has a database of the heights of all Canada Canadian males. In psychology, we would refer to this type of database as containing the normative information for height or the height norms. Examining this data from all Canadian males we find the mean and standard deviation below (I made up these values):</p>
<p><span class="math display">\[
\begin{aligned}
\overline{X_{males_canada}} &amp;= 186.1 \\
S_{males_canada} &amp;= 7.20 \\
\end{aligned}
\]</span></p>
<div id="hand-calculation-4" class="section level4" number="6.6.3.1">
<h4><span class="header-section-number">6.6.3.1</span> Hand calculation</h4>
<p>We can use the normative information from all Canadian males to calculate a <em>z</em>-score for John uses <strong>Canadian males as the frame of reference</strong>. We do so with the hand calculation below:</p>
<p><span class="math display">\[
\begin{aligned}
z_i &amp;= \frac{X_i - \overline{X_{males_canada}}}{S_{males_canada}}\\
&amp;= \frac{\text{(John&#39;s height in cm)} - \overline{X_{males_canada}}}{S_{males_canada}}\\
&amp;= \frac{190 - 186.1}{7.20}\\
&amp;= \frac{3.9}{7.20}\\
&amp;= 0.5416667\\
\end{aligned}
\]</span></p>
<p>We see that relative to Canadian males John’s <em>z</em>-score is 0.5416667. That means that relative to Canadian males is 0.54 standard deviations taller than the mean.</p>
</div>
<div id="r-calculation-4" class="section level4" number="6.6.3.2">
<h4><span class="header-section-number">6.6.3.2</span> R calculation</h4>
<p>We can use R to calculate the <em>z</em>-score for each male in our data set <strong>relative to all Canadian males</strong> (i.e., relative to the height norms for males). We are using the mutate() command to create a new colum called z_canada_males We use this column name to reflect the fact that the we are using all Canadian males as the frame of reference for the new <em>z</em>-score column. Also notice how the formula in the mutate() command corresponds to the formula used in the hand calculation above.</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="scaling.html#cb259-1" aria-hidden="true" tabindex="-1"></a>male_height_data <span class="ot">&lt;-</span> male_height_data <span class="sc">%&gt;%</span></span>
<span id="cb259-2"><a href="scaling.html#cb259-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_canada_male =</span> (cm_height <span class="sc">-</span> <span class="fl">186.1</span>)<span class="sc">/</span> <span class="fl">7.20</span>  )</span></code></pre></div>
<p>We see the new z_canada_male column (and the old <em>z</em>-score columns) with the code below.</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="scaling.html#cb260-1" aria-hidden="true" tabindex="-1"></a>male_height_data <span class="sc">%&gt;%</span></span>
<span id="cb260-2"><a href="scaling.html#cb260-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>part_id, <span class="sc">-</span>sex, <span class="sc">-</span>T_data, <span class="sc">-</span>inch_height) <span class="sc">%&gt;%</span></span>
<span id="cb260-3"><a href="scaling.html#cb260-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cm_height) <span class="sc">%&gt;%</span></span>
<span id="cb260-4"><a href="scaling.html#cb260-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##       name cm_height   z_data z_data_males z_canada_male
## 1    Steve       165 -1.03580     -2.08905       -2.9306
## 2      Jim       168 -0.66142     -1.63159       -2.5139
## 3    Jamal       172 -0.16223     -1.02165       -1.9583
## 4      Tim       173 -0.03744     -0.86917       -1.8194
## 5      Eli       174  0.08736     -0.71668       -1.6806
## 6     Sean       179  0.71133      0.04575       -0.9861
## 7     Matt       180  0.83613      0.19823       -0.8472
## 8     Rick       183  1.21052      0.65569       -0.4306
## 9  Basheer       185  1.46011      0.96066       -0.1528
## 10    John       190  2.08408      1.72309        0.5417</code></pre>
<p>Examine the table above table above and contrast the values of the z_data, z_data_male, and z_canada_male columns. Each column index the height of the males in our data set relative to a different frame of reference.</p>
<p>We can can consider the values for a single person, Sean, by using the filter command below:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="scaling.html#cb262-1" aria-hidden="true" tabindex="-1"></a>male_height_data <span class="sc">%&gt;%</span></span>
<span id="cb262-2"><a href="scaling.html#cb262-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(name <span class="sc">==</span> <span class="st">&quot;Sean&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb262-3"><a href="scaling.html#cb262-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>part_id, <span class="sc">-</span>sex, <span class="sc">-</span>T_data, <span class="sc">-</span>inch_height) <span class="sc">%&gt;%</span></span>
<span id="cb262-4"><a href="scaling.html#cb262-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cm_height) <span class="sc">%&gt;%</span></span>
<span id="cb262-5"><a href="scaling.html#cb262-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   name cm_height z_data z_data_males z_canada_male
## 1 Sean       179 0.7113      0.04575       -0.9861</code></pre>
<p>Examine Sean’s <em>z</em>-scores in the output above. When we consider Sean’s height relative to everyone in the data set he is 0.7113 above the mean. That is, relative to everyone in the data set Sean is slightly tall. But when we consider Sean’s height relative to only males in the data set he is 0.04575 standard deviations above the mean. That is when considering only males in the data set Sean is roughly average in height (0.04575 is very close to 0; or roughly 0). In contrast, when we consider Sean’s height relative to all Canadian males we obtain a <em>z</em>-score of -0.9861. This indicates that relative to all Canadian males Sean is almost 1 standard deviation below the mean. That is, relative to all Canadian males Sean is somewhat short. The value of <em>z</em>-score is that they provide you with a number that allows easily consider a person’s score relative to a frame of reference.</p>
</div>
</div>
</div>
<div id="summary-4" class="section level2" number="6.7">
<h2><span class="header-section-number">6.7</span> Summary</h2>
<p>By the end of this activity we represented the heights of male in many different ways - presented in the table below.</p>
<pre><code>##       name cm_height   z_data z_data_males z_canada_male
## 1    Steve       165 -1.03580     -2.08905       -2.9306
## 2      Jim       168 -0.66142     -1.63159       -2.5139
## 3    Jamal       172 -0.16223     -1.02165       -1.9583
## 4      Tim       173 -0.03744     -0.86917       -1.8194
## 5      Eli       174  0.08736     -0.71668       -1.6806
## 6     Sean       179  0.71133      0.04575       -0.9861
## 7     Matt       180  0.83613      0.19823       -0.8472
## 8     Rick       183  1.21052      0.65569       -0.4306
## 9  Basheer       185  1.46011      0.96066       -0.1528
## 10    John       190  2.08408      1.72309        0.5417</code></pre>
<p>Previously we discussed how you can think of height in centimeter vs inches using the analogy of a ruler - as illustrated below.</p>
<p><img src="ch_scaling/images/ruler.png" width="50%" /></p>
<p>The same applies with <em>z</em>-scores. You can think of each <em>z</em>-score calculation as forming a different ruler – as illustrated below.</p>
<p><img src="ch_scaling/images/zruler.png" width="800" /></p>
<p>If you inspect the summary table below you see the z_canada_male column has a mean of -1.028. This indicate that the average height of the males in our data set is 1.028 standard deviations below the mean height for Canadian males. Consequently, relative to all Canadian males, the males in our sample tend to be short.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
unit
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd_pop
</th>
<th style="text-align:right;">
N
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cm_height
</td>
<td style="text-align:right;">
176.900
</td>
<td style="text-align:right;">
7.463
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
z_data
</td>
<td style="text-align:right;">
0.449
</td>
<td style="text-align:right;">
0.931
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
z_data_males
</td>
<td style="text-align:right;">
-0.274
</td>
<td style="text-align:right;">
1.138
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
z_canada_male
</td>
<td style="text-align:right;">
-1.278
</td>
<td style="text-align:right;">
1.036
</td>
<td style="text-align:right;">
10
</td>
</tr>
</tbody>
</table>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="notation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="percentiles.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/06-scaling.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
