<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Week 3 Friday Workshop | Welcome!</title>
  <meta name="description" content="Course notes for PSYC 3250" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Week 3 Friday Workshop | Welcome!" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course notes for PSYC 3250" />
  <meta name="github-repo" content="dstanley4/psyc3250bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Week 3 Friday Workshop | Welcome!" />
  
  <meta name="twitter:description" content="Course notes for PSYC 3250" />
  

<meta name="author" content="David J. Stanley" />


<meta name="date" content="2022-01-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-2-friday-workshop.html"/>
<link rel="next" href="notation.html"/>
<script src="libs/header-attrs/header-attrs.js"></script>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course:</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html"><i class="fa fa-check"></i><b>1</b> Week 1 Friday Workshop</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#a-focus-on-workflow"><i class="fa fa-check"></i><b>1.1</b> A focus on workflow</a></li>
<li class="chapter" data-level="1.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#r-works-with-plug-ins"><i class="fa fa-check"></i><b>1.2</b> R works with plug-ins</a></li>
<li class="chapter" data-level="1.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#software-choice"><i class="fa fa-check"></i><b>1.3</b> Software Choice</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#mac"><i class="fa fa-check"></i><b>1.3.1</b> Mac</a></li>
<li class="chapter" data-level="1.3.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#pc"><i class="fa fa-check"></i><b>1.3.2</b> PC</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-rstudio-not-r"><i class="fa fa-check"></i><b>1.4</b> Run RStudio not R</a></li>
<li class="chapter" data-level="1.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#rstudio-configuration-first-run-only"><i class="fa fa-check"></i><b>1.5</b> RStudio configuration, First run only</a></li>
<li class="chapter" data-level="1.6" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#begin-with-an-rstudio-project"><i class="fa fa-check"></i><b>1.6</b> Begin with an RStudio Project</a></li>
<li class="chapter" data-level="1.7" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#exploring-the-r-studio-interface"><i class="fa fa-check"></i><b>1.7</b> Exploring the R Studio Interface</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#console-panel"><i class="fa fa-check"></i><b>1.7.1</b> Console panel</a></li>
<li class="chapter" data-level="1.7.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#script-panel"><i class="fa fa-check"></i><b>1.7.2</b> Script Panel</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#writing-your-first-script"><i class="fa fa-check"></i><b>1.8</b> Writing your first script</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#create-the-script-file"><i class="fa fa-check"></i><b>1.8.1</b> Create the script file</a></li>
<li class="chapter" data-level="1.8.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#add-a-comment-to-your-script"><i class="fa fa-check"></i><b>1.8.2</b> Add a comment to your script</a></li>
<li class="chapter" data-level="1.8.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#background-about-the-tidyverse"><i class="fa fa-check"></i><b>1.8.3</b> Background about the tidyverse</a></li>
<li class="chapter" data-level="1.8.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#add-librarytidyverse-to-your-script"><i class="fa fa-check"></i><b>1.8.4</b> Add library(tidyverse) to your script</a></li>
<li class="chapter" data-level="1.8.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#activate-tidyverse-auto-complete-for-your-script"><i class="fa fa-check"></i><b>1.8.5</b> Activate tidyverse auto-complete for your script</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#loading-your-data"><i class="fa fa-check"></i><b>1.9</b> Loading your data</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#use-read_csv-not-read.csv-to-open-files."><i class="fa fa-check"></i><b>1.9.1</b> Use read_csv (not read.csv) to open files.</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#checking-out-your-data"><i class="fa fa-check"></i><b>1.10</b> Checking out your data</a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#view-see-a-spreadsheet-view-of-your-data"><i class="fa fa-check"></i><b>1.10.1</b> view(): See a spreadsheet view of your data</a></li>
<li class="chapter" data-level="1.10.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#print-see-you-data-in-the-console"><i class="fa fa-check"></i><b>1.10.2</b> print(): See you data in the Console</a></li>
<li class="chapter" data-level="1.10.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#head-check-out-the-first-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.3</b> head(): Check out the first few rows of data</a></li>
<li class="chapter" data-level="1.10.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#tail-check-out-the-last-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.4</b> tail(): Check out the last few rows of data</a></li>
<li class="chapter" data-level="1.10.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#summary-quick-summaries"><i class="fa fa-check"></i><b>1.10.5</b> summary(): Quick summaries</a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-vs.-source-with-echo-vs.-source"><i class="fa fa-check"></i><b>1.11</b> Run <em>vs.</em> Source with Echo <em>vs.</em> Source</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-select-text"><i class="fa fa-check"></i><b>1.11.1</b> Run select text</a></li>
<li class="chapter" data-level="1.11.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#source-without-echo"><i class="fa fa-check"></i><b>1.11.2</b> Source (without Echo)</a></li>
<li class="chapter" data-level="1.11.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#source-with-echo"><i class="fa fa-check"></i><b>1.11.3</b> Source with Echo</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#trying-source-with-echo"><i class="fa fa-check"></i><b>1.12</b> Trying Source with Echo</a></li>
<li class="chapter" data-level="1.13" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#a-few-key-points-about"><i class="fa fa-check"></i><b>1.13</b> A few key points about</a>
<ul>
<li class="chapter" data-level="1.13.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#lists"><i class="fa fa-check"></i><b>1.13.1</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#revisiting-read_csv"><i class="fa fa-check"></i><b>1.14</b> Revisiting read_csv()</a></li>
<li class="chapter" data-level="1.15" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#thats-it"><i class="fa fa-check"></i><b>1.15</b> That’s it!</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html"><i class="fa fa-check"></i><b>2</b> Handling Data with the Tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>2.1</b> Required</a></li>
<li class="chapter" data-level="2.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>2.2</b> Objective</a></li>
<li class="chapter" data-level="2.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-the-console"><i class="fa fa-check"></i><b>2.3</b> Using the Console</a></li>
<li class="chapter" data-level="2.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tidyverse-help-with-the-introverse"><i class="fa fa-check"></i><b>2.4</b> Tidyverse help with the Introverse</a></li>
<li class="chapter" data-level="2.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#basic-tidyverse-commands"><i class="fa fa-check"></i><b>2.5</b> Basic tidyverse commands</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select"><i class="fa fa-check"></i><b>2.5.1</b> select()</a></li>
<li class="chapter" data-level="2.5.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise"><i class="fa fa-check"></i><b>2.5.2</b> summarise()</a></li>
<li class="chapter" data-level="2.5.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#filter"><i class="fa fa-check"></i><b>2.5.3</b> filter()</a></li>
<li class="chapter" data-level="2.5.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#group_by"><i class="fa fa-check"></i><b>2.5.4</b> group_by()</a></li>
<li class="chapter" data-level="2.5.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate"><i class="fa fa-check"></i><b>2.5.5</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#advanced-tidyverse-commands"><i class="fa fa-check"></i><b>2.6</b> Advanced tidyverse commands</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select-1"><i class="fa fa-check"></i><b>2.6.1</b> select()</a></li>
<li class="chapter" data-level="2.6.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise-1"><i class="fa fa-check"></i><b>2.6.2</b> summarise()</a></li>
<li class="chapter" data-level="2.6.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate-1"><i class="fa fa-check"></i><b>2.6.3</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-help"><i class="fa fa-check"></i><b>2.7</b> Using help</a></li>
<li class="chapter" data-level="2.8" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#base-r-vs-tidyverse"><i class="fa fa-check"></i><b>2.8</b> Base R vs tidyverse</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tibbles-vs.-data-frames"><i class="fa fa-check"></i><b>2.8.1</b> Tibbles vs. data frames</a></li>
<li class="chapter" data-level="2.8.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read.csv-and-data-frames"><i class="fa fa-check"></i><b>2.8.2</b> read.csv() and data frames</a></li>
<li class="chapter" data-level="2.8.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read_csv-and-tibbles"><i class="fa fa-check"></i><b>2.8.3</b> read_csv() and tibbles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html"><i class="fa fa-check"></i><b>3</b> Week 2 Friday Workshop</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#required-packages"><i class="fa fa-check"></i><b>3.1</b> Required Packages</a></li>
<li class="chapter" data-level="3.2" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#goals"><i class="fa fa-check"></i><b>3.2</b> Goals</a></li>
<li class="chapter" data-level="3.3" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#data-and-column-names"><i class="fa fa-check"></i><b>3.3</b> Data and column names</a></li>
<li class="chapter" data-level="3.4" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#install-packages"><i class="fa fa-check"></i><b>3.4</b> Install packages</a></li>
<li class="chapter" data-level="3.5" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#rstudio-project"><i class="fa fa-check"></i><b>3.5</b> RStudio Project</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#make-a-script"><i class="fa fa-check"></i><b>3.5.1</b> Make a script</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#loading-data"><i class="fa fa-check"></i><b>3.6</b> Loading data</a></li>
<li class="chapter" data-level="3.7" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#clean-and-screen-the-data"><i class="fa fa-check"></i><b>3.7</b> Clean and screen the data</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#numeric-screening"><i class="fa fa-check"></i><b>3.7.1</b> Numeric screening</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#flipping-responses-to-reverse-key-items"><i class="fa fa-check"></i><b>3.8</b> Flipping responses to reverse-key items</a></li>
<li class="chapter" data-level="3.9" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#making-scale-scores"><i class="fa fa-check"></i><b>3.9</b> Making scale scores</a></li>
<li class="chapter" data-level="3.10" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#descriptive-statistics-for-scale-scores"><i class="fa fa-check"></i><b>3.10</b> Descriptive statistics for scale scores</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html"><i class="fa fa-check"></i><b>4</b> Week 3 Friday Workshop</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#required-packages-1"><i class="fa fa-check"></i><b>4.1</b> Required Packages</a></li>
<li class="chapter" data-level="4.2" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#goals-1"><i class="fa fa-check"></i><b>4.2</b> Goals</a></li>
<li class="chapter" data-level="4.3" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#data-and-column-names-1"><i class="fa fa-check"></i><b>4.3</b> Data and column names</a></li>
<li class="chapter" data-level="4.4" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#install-packages-1"><i class="fa fa-check"></i><b>4.4</b> Install packages</a></li>
<li class="chapter" data-level="4.5" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#rstudio-project-1"><i class="fa fa-check"></i><b>4.5</b> RStudio Project</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#make-a-script-1"><i class="fa fa-check"></i><b>4.5.1</b> Make a script</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#week-2-catchup"><i class="fa fa-check"></i><b>4.6</b> Week 2 Catchup</a></li>
<li class="chapter" data-level="4.7" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#creating-compositescale-scores"><i class="fa fa-check"></i><b>4.7</b> Creating composite/scale scores</a></li>
<li class="chapter" data-level="4.8" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-scale-scores"><i class="fa fa-check"></i><b>4.8</b> Variance of scale scores</a></li>
<li class="chapter" data-level="4.9" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-items"><i class="fa fa-check"></i><b>4.9</b> Variance of items</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#approach-1"><i class="fa fa-check"></i><b>4.9.1</b> Approach 1</a></li>
<li class="chapter" data-level="4.9.2" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#approach-2"><i class="fa fa-check"></i><b>4.9.2</b> Approach 2</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-affect_sum-column"><i class="fa fa-check"></i><b>4.10</b> Variance of affect_sum column</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="notation.html"><a href="notation.html"><i class="fa fa-check"></i><b>5</b> Notation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="notation.html"><a href="notation.html#measurement-notation"><i class="fa fa-check"></i><b>5.1</b> Measurement Notation</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="scaling.html"><a href="scaling.html"><i class="fa fa-check"></i><b>6</b> Scaling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="scaling.html"><a href="scaling.html#data-entry"><i class="fa fa-check"></i><b>6.1</b> Data entry</a></li>
<li class="chapter" data-level="6.2" data-path="scaling.html"><a href="scaling.html#loading-data-1"><i class="fa fa-check"></i><b>6.2</b> Loading data</a></li>
<li class="chapter" data-level="6.3" data-path="scaling.html"><a href="scaling.html#viewing-data"><i class="fa fa-check"></i><b>6.3</b> Viewing data</a></li>
<li class="chapter" data-level="6.4" data-path="scaling.html"><a href="scaling.html#summary-statistics"><i class="fa fa-check"></i><b>6.4</b> Summary statistics</a></li>
<li class="chapter" data-level="6.5" data-path="scaling.html"><a href="scaling.html#converting-units"><i class="fa fa-check"></i><b>6.5</b> Converting units</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="scaling.html"><a href="scaling.html#inches"><i class="fa fa-check"></i><b>6.5.1</b> Inches</a></li>
<li class="chapter" data-level="6.5.2" data-path="scaling.html"><a href="scaling.html#z-scores"><i class="fa fa-check"></i><b>6.5.2</b> <em>z</em>-scores</a></li>
<li class="chapter" data-level="6.5.3" data-path="scaling.html"><a href="scaling.html#t-scores"><i class="fa fa-check"></i><b>6.5.3</b> T-scores</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="scaling.html"><a href="scaling.html#frame-of-references"><i class="fa fa-check"></i><b>6.6</b> Frame of references</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="scaling.html"><a href="scaling.html#all-participants"><i class="fa fa-check"></i><b>6.6.1</b> All participants</a></li>
<li class="chapter" data-level="6.6.2" data-path="scaling.html"><a href="scaling.html#male-reference"><i class="fa fa-check"></i><b>6.6.2</b> Male reference</a></li>
<li class="chapter" data-level="6.6.3" data-path="scaling.html"><a href="scaling.html#canadian-reference"><i class="fa fa-check"></i><b>6.6.3</b> Canadian reference</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="scaling.html"><a href="scaling.html#summary-4"><i class="fa fa-check"></i><b>6.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="percentiles.html"><a href="percentiles.html"><i class="fa fa-check"></i><b>7</b> Percentiles</a>
<ul>
<li class="chapter" data-level="7.1" data-path="percentiles.html"><a href="percentiles.html#assuming-a-normal-distribution-approach"><i class="fa fa-check"></i><b>7.1</b> Assuming a normal distribution approach</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="percentiles.html"><a href="percentiles.html#a-single-case"><i class="fa fa-check"></i><b>7.1.1</b> A single case</a></li>
<li class="chapter" data-level="7.1.2" data-path="percentiles.html"><a href="percentiles.html#many-cases-using-r"><i class="fa fa-check"></i><b>7.1.2</b> Many cases using R</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="percentiles.html"><a href="percentiles.html#assumption-free-approach"><i class="fa fa-check"></i><b>7.2</b> Assumption free approach</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>8</b> Graphing</a>
<ul>
<li class="chapter" data-level="8.1" data-path="graphing.html"><a href="graphing.html#required-1"><i class="fa fa-check"></i><b>8.1</b> Required</a></li>
<li class="chapter" data-level="8.2" data-path="graphing.html"><a href="graphing.html#data"><i class="fa fa-check"></i><b>8.2</b> Data</a></li>
<li class="chapter" data-level="8.3" data-path="graphing.html"><a href="graphing.html#graph-basics"><i class="fa fa-check"></i><b>8.3</b> Graph basics</a></li>
<li class="chapter" data-level="8.4" data-path="graphing.html"><a href="graphing.html#graphing-efficiently"><i class="fa fa-check"></i><b>8.4</b> Graphing efficiently</a></li>
<li class="chapter" data-level="8.5" data-path="graphing.html"><a href="graphing.html#aesthetics"><i class="fa fa-check"></i><b>8.5</b> Aesthetics</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="graphing.html"><a href="graphing.html#fill-color"><i class="fa fa-check"></i><b>8.5.1</b> Fill color</a></li>
<li class="chapter" data-level="8.5.2" data-path="graphing.html"><a href="graphing.html#overriding-aes"><i class="fa fa-check"></i><b>8.5.2</b> Overriding aes()</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="graphing.html"><a href="graphing.html#apa-style"><i class="fa fa-check"></i><b>8.6</b> APA style</a></li>
<li class="chapter" data-level="8.7" data-path="graphing.html"><a href="graphing.html#axes"><i class="fa fa-check"></i><b>8.7</b> Axes</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="graphing.html"><a href="graphing.html#range"><i class="fa fa-check"></i><b>8.7.1</b> Range</a></li>
<li class="chapter" data-level="8.7.2" data-path="graphing.html"><a href="graphing.html#ticks"><i class="fa fa-check"></i><b>8.7.2</b> Ticks</a></li>
<li class="chapter" data-level="8.7.3" data-path="graphing.html"><a href="graphing.html#labels"><i class="fa fa-check"></i><b>8.7.3</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="graphing.html"><a href="graphing.html#axis-values"><i class="fa fa-check"></i><b>8.8</b> Axis values</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="graphing.html"><a href="graphing.html#text"><i class="fa fa-check"></i><b>8.8.1</b> Text</a></li>
<li class="chapter" data-level="8.8.2" data-path="graphing.html"><a href="graphing.html#angle"><i class="fa fa-check"></i><b>8.8.2</b> Angle</a></li>
<li class="chapter" data-level="8.8.3" data-path="graphing.html"><a href="graphing.html#alignment"><i class="fa fa-check"></i><b>8.8.3</b> Alignment</a></li>
<li class="chapter" data-level="8.8.4" data-path="graphing.html"><a href="graphing.html#order"><i class="fa fa-check"></i><b>8.8.4</b> Order</a></li>
<li class="chapter" data-level="8.8.5" data-path="graphing.html"><a href="graphing.html#legend-order"><i class="fa fa-check"></i><b>8.8.5</b> Legend order</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="graphing.html"><a href="graphing.html#custom-colours"><i class="fa fa-check"></i><b>8.9</b> Custom colours</a>
<ul>
<li class="chapter" data-level="8.9.1" data-path="graphing.html"><a href="graphing.html#r-palette"><i class="fa fa-check"></i><b>8.9.1</b> R palette</a></li>
<li class="chapter" data-level="8.9.2" data-path="graphing.html"><a href="graphing.html#hex-colours"><i class="fa fa-check"></i><b>8.9.2</b> Hex colours</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="graphing.html"><a href="graphing.html#emoji"><i class="fa fa-check"></i><b>8.10</b> Emoji</a></li>
<li class="chapter" data-level="8.11" data-path="graphing.html"><a href="graphing.html#accessible-colors"><i class="fa fa-check"></i><b>8.11</b> Accessible Colors</a>
<ul>
<li class="chapter" data-level="8.11.1" data-path="graphing.html"><a href="graphing.html#rcolorbrewer"><i class="fa fa-check"></i><b>8.11.1</b> RColorBrewer</a></li>
<li class="chapter" data-level="8.11.2" data-path="graphing.html"><a href="graphing.html#avoid-color"><i class="fa fa-check"></i><b>8.11.2</b> Avoid color</a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="graphing.html"><a href="graphing.html#saving"><i class="fa fa-check"></i><b>8.12</b> Saving</a>
<ul>
<li class="chapter" data-level="8.12.1" data-path="graphing.html"><a href="graphing.html#mac-1"><i class="fa fa-check"></i><b>8.12.1</b> MAC</a></li>
<li class="chapter" data-level="8.12.2" data-path="graphing.html"><a href="graphing.html#pc-or-mac"><i class="fa fa-check"></i><b>8.12.2</b> PC or MAC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Welcome!</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-3-friday-workshop" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Week 3 Friday Workshop</h1>
<div id="required-packages-1" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Required Packages</h2>
<p>The data files below are used in this chapter. The files are available at: <a href="https://github.com/dstanley4/psyc3250bookdown" class="uri">https://github.com/dstanley4/psyc3250bookdown</a></p>
<table>
<thead>
<tr class="header">
<th>Required Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="data_aff_survey.csv">data_aff_survey.csv</a></td>
</tr>
</tbody>
</table>
<p>The following CRAN packages must be installed:</p>
<table>
<thead>
<tr class="header">
<th>Required CRAN Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tidyverse</td>
</tr>
<tr class="even">
<td>janitor</td>
</tr>
<tr class="odd">
<td>skimr</td>
</tr>
<tr class="even">
<td>sjstats</td>
</tr>
</tbody>
</table>
<p><strong>Important Note:</strong> You should NOT use library(psych) at any point! There are major conflicts between the psych package and the tidyverse. We will access the psych package commands by preceding each command with psych:: instead of using library(psych).</p>
<p>The complete script for this project can be download here: <a href="script_workshop2.R">script_workshop2.R</a></p>
</div>
<div id="goals-1" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Goals</h2>
<p>For this workshop our goals are to learn how to:</p>
<ul>
<li><p>Consolidate Workshop 2 concepts</p></li>
<li><p>Examine variance and covariance in the context of items</p></li>
<li><p>Illustrate how we can calculate the variance of a column of scale scores</p></li>
</ul>
</div>
<div id="data-and-column-names-1" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Data and column names</h2>
<p>A key component of effect data analysis is the use of naming conventions for column names. In this section we focus on one column naming convention that makes it easy to work with survey data. You will need to use this column naming convention for your major project.</p>
<p>The namning convention we advocate will save you hours of hassles and permit easy application of certain tidyverse commands. However, we must stress that although the naming convention we advocate is based on the tidyverse style guide, it is not “right” or “correct” - there are other naming conventions you can use (once you finish the course). Any naming convention is better than no naming convention. The naming convention we advocate here will solve many problems.</p>
<p>To make your life easier down the road, it is critical you set up your spreadsheet or online survey such that it uses a naming convention prior to data collection. The naming conventions suggested here are adapted from the tidyverse <a href="https://style.tidyverse.org">style guide</a>.</p>
<p>The key components of the column naming convention are the following:</p>
<ul>
<li><p>Lowercase letters only</p></li>
<li><p>If two word column names are necessary, only use the underscore (“_“) character to separate words in the name. Do not use a period (.””) a space (” “) or other symbols.</p></li>
<li><p>Use moderate length (not short0 column prefixes. For example, if you have an Affective Commitment Scale do not preface each items with “acs” instead preface each item with a longer verison like “aff_com.”</p></li>
<li><p>Indicate in the item name if it is a likert-type scale and the number of points in the scale. For example, if your affective commitment scale has a 7-point Likert-type response scale you indicate that in the column name. For example, the name for two commtiment items might be: “aff_com1_likert7’ and”aff_com2_likert7”. This indicates important information for future users of the data set (including you)</p></li>
<li><p>Indicate in the item name if the item is reversed keyed. ** Sometimes with Likert-type items, an item is reverse keyed. For example, on a <strong>positive</strong> job affect scale, participants will typically respond to items that reflect job affect using the scale: 1 - Strongly Disagree, 2 - Moderately Disagree, 3 - Neutral, 4, Moderately Agree, 5 - Strongly Agree. Higher numbers indicate more positive job affect. Sometimes, however, some items will use the same 1 to 5 response scale but be worded in the opposite manner such as “I hate my job.” Responding with a 5 to this item would indicate high <strong>negative</strong> job affect (not positive affect). But the columns for positive job affect scale should have high values to indicate more positive job affect not less positive job affect. Consequently, we flag the names of columns with reversed responses (i.e., reverse-key items) so that we know to treat those column differently later. Columns with reverse-keyed items need to be processed by a script so that the values are flipped and scored in the right direction. A normal positive job affect item might have a name like “job_aff1_likert7” whereas a reverse-key item would have a name like “job_aff2-likert7rev.” The “rev” in the column name indicates the item was a reverse-keyed item.</p></li>
</ul>
</div>
<div id="install-packages-1" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Install packages</h2>
<p>You will need the same packages installed as you did for the Week 2 Friday workshop. If you did not install the packages then - go back to that week and do so now.</p>
</div>
<div id="rstudio-project-1" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> RStudio Project</h2>
<ol style="list-style-type: decimal">
<li><p>Create a folder on your computer for the example</p></li>
<li><p>Download the data file for this example: <a href="data_aff_survey.csv">data_aff_survey.csv</a>. ONLY obtain this file from the Downloads folder. If you open in another program and save it again - the data file will not work.</p></li>
<li><p>Place all the example data file in the folder you created in Step 1.</p></li>
<li><p>Use the menu item File &gt; New Project… to start the project</p></li>
<li><p>On the window that appears select “Existing Directory”</p></li>
<li><p>On the next screen, press the “Browse” button and find/select the folder with your data</p></li>
<li><p>Press the Create Project Button</p></li>
</ol>
<div id="make-a-script-1" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Make a script</h3>
<ol style="list-style-type: decimal">
<li><p>Go the File menu. File &gt; New File &gt; Script</p></li>
<li><p>When you write your code - place into this script.</p></li>
</ol>
</div>
</div>
<div id="week-2-catchup" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Week 2 Catchup</h2>
<p>Place the code below into your script from last week:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="week-3-friday-workshop.html#cb196-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Date: YYYY-MM-DD</span></span>
<span id="cb196-2"><a href="week-3-friday-workshop.html#cb196-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Name: your name here</span></span>
<span id="cb196-3"><a href="week-3-friday-workshop.html#cb196-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Example: Workshop 3 PSYC 3250</span></span>
<span id="cb196-4"><a href="week-3-friday-workshop.html#cb196-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-5"><a href="week-3-friday-workshop.html#cb196-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Activate packages  </span></span>
<span id="cb196-6"><a href="week-3-friday-workshop.html#cb196-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb196-7"><a href="week-3-friday-workshop.html#cb196-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb196-8"><a href="week-3-friday-workshop.html#cb196-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb196-9"><a href="week-3-friday-workshop.html#cb196-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjstats)</span>
<span id="cb196-10"><a href="week-3-friday-workshop.html#cb196-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-11"><a href="week-3-friday-workshop.html#cb196-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Load data </span></span>
<span id="cb196-12"><a href="week-3-friday-workshop.html#cb196-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-13"><a href="week-3-friday-workshop.html#cb196-13" aria-hidden="true" tabindex="-1"></a>my_missing_value_codes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;-999&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="st">&quot;NA&quot;</span>)</span>
<span id="cb196-14"><a href="week-3-friday-workshop.html#cb196-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-15"><a href="week-3-friday-workshop.html#cb196-15" aria-hidden="true" tabindex="-1"></a>raw_data_survey <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;data_aff_survey.csv&quot;</span>,</span>
<span id="cb196-16"><a href="week-3-friday-workshop.html#cb196-16" aria-hidden="true" tabindex="-1"></a>                            <span class="at">na =</span> my_missing_value_codes)</span></code></pre></div>
<pre><code>## Rows: 100 Columns: 3</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): aff_com2_likert7, aff_com3_likert7, aff_com4_li...</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="week-3-friday-workshop.html#cb200-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> raw_data_survey</span>
<span id="cb200-2"><a href="week-3-friday-workshop.html#cb200-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-3"><a href="week-3-friday-workshop.html#cb200-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-4"><a href="week-3-friday-workshop.html#cb200-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Clean and screen </span></span>
<span id="cb200-5"><a href="week-3-friday-workshop.html#cb200-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-6"><a href="week-3-friday-workshop.html#cb200-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial cleaning</span></span>
<span id="cb200-7"><a href="week-3-friday-workshop.html#cb200-7" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb200-8"><a href="week-3-friday-workshop.html#cb200-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">&quot;rows&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb200-9"><a href="week-3-friday-workshop.html#cb200-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">&quot;cols&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb200-10"><a href="week-3-friday-workshop.html#cb200-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb200-11"><a href="week-3-friday-workshop.html#cb200-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-12"><a href="week-3-friday-workshop.html#cb200-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Numeric screening</span></span>
<span id="cb200-13"><a href="week-3-friday-workshop.html#cb200-13" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb200-14"><a href="week-3-friday-workshop.html#cb200-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(aff_com2_likert7, aff_com3_likert7, aff_com4_likert7rev) <span class="sc">%&gt;%</span></span>
<span id="cb200-15"><a href="week-3-friday-workshop.html#cb200-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span>
<span id="cb200-16"><a href="week-3-friday-workshop.html#cb200-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-17"><a href="week-3-friday-workshop.html#cb200-17" aria-hidden="true" tabindex="-1"></a><span class="do">## Flipping responses to reverse-key items </span></span>
<span id="cb200-18"><a href="week-3-friday-workshop.html#cb200-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-19"><a href="week-3-friday-workshop.html#cb200-19" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(analytic_data_survey)</span>
<span id="cb200-20"><a href="week-3-friday-workshop.html#cb200-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-21"><a href="week-3-friday-workshop.html#cb200-21" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb200-22"><a href="week-3-friday-workshop.html#cb200-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="dv">8</span> <span class="sc">-</span> <span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">ends_with</span>(<span class="st">&quot;_likert7rev&quot;</span>)) ) <span class="sc">%&gt;%</span> </span>
<span id="cb200-23"><a href="week-3-friday-workshop.html#cb200-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="at">.fn =</span> str_replace,</span>
<span id="cb200-24"><a href="week-3-friday-workshop.html#cb200-24" aria-hidden="true" tabindex="-1"></a>              <span class="at">.cols =</span> <span class="fu">ends_with</span>(<span class="st">&quot;_likert7rev&quot;</span>),</span>
<span id="cb200-25"><a href="week-3-friday-workshop.html#cb200-25" aria-hidden="true" tabindex="-1"></a>              <span class="at">pattern =</span> <span class="st">&quot;_likert7rev&quot;</span>,</span>
<span id="cb200-26"><a href="week-3-friday-workshop.html#cb200-26" aria-hidden="true" tabindex="-1"></a>              <span class="at">replacement =</span> <span class="st">&quot;_likert7&quot;</span>)</span>
<span id="cb200-27"><a href="week-3-friday-workshop.html#cb200-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-28"><a href="week-3-friday-workshop.html#cb200-28" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(analytic_data_survey)</span></code></pre></div>
<p>Now go to the menu: Session &gt; Restart R</p>
<p>Then press the Source with Echo button to run the entire script.</p>
<p>Following this type the head() command in the Console:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="week-3-friday-workshop.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(analytic_data_survey)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   aff_com2_likert7 aff_com3_likert7 aff_com4_likert7
##              &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1                3                3                3
## 2                5                4                4
## 3                2                3                2
## 4                4                3                3
## 5                2                3                2
## 6                3                3                3</code></pre>
<p>Somtimes there are too many columns. So another option is to use the glimpse() command:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="week-3-friday-workshop.html#cb203-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb203-2"><a href="week-3-friday-workshop.html#cb203-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 100
## Columns: 3
## $ aff_com2_likert7 &lt;dbl&gt; 3, 5, 2, 4, 2, 3, 4, 4, 4, 3, 4, …
## $ aff_com3_likert7 &lt;dbl&gt; 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 4, …
## $ aff_com4_likert7 &lt;dbl&gt; 3, 4, 2, 3, 2, 3, 4, 3, 3, 3, 4, …</code></pre>
<p>In the current scenario all of the columns are coded in the right direction (i.e., there are no reverse-coded items) in the next section we will create the scale scores.</p>
</div>
<div id="creating-compositescale-scores" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Creating composite/scale scores</h2>
<p>When we AVERAGE (i.e., take the mean) of the commitment items for each person we call that a scale score. It represents our best guess of their overall commitment level based on those three items. The advantage of taking the AVERAGE of the three items is that we can interpret the result on the original 1 to 7 scale. We know the lowest score the someone can get is 1.0 (i.e, they obtained an average of 1.0 because that have a score of 1.0 on all three items). Correspondingly, the highest score someone can get is 7.0 (i.e, they obtained an average of 7.0 because that have a score of 7.0 on all three items). This is an interpretation approach the many researchers prefer. If you had more items, the range of possible scores would stay the same.</p>
<p>Other researchers prefer to get the SUM of the three items when calculating a scale score. This approach is use sometimes – but interpretation needs to into account the number of items in this case. For example, if you used the SUM approach the minimum maximum range is 3 to 21. That is, if a person scored 1.0 for all three items their score would be 3.0. Likewise, if a person scored 7.0 for all three items then their score would be 27. If you had more items, the range of possible scores would change.</p>
<p>Both approaches (AVERAGE vs SUM) are acceptable you just need to make sure you know which one you’re dealing with.</p>
<p>Add the code below to your script. Notice we calculate the scale score in two different ways in this script. The affect_mean and affect_sum columns are created. The affect_mean column corresponds to the affective_commitment column we created last week.</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="week-3-friday-workshop.html#cb205-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Creating scale scores </span></span>
<span id="cb205-2"><a href="week-3-friday-workshop.html#cb205-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb205-3"><a href="week-3-friday-workshop.html#cb205-3" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb205-4"><a href="week-3-friday-workshop.html#cb205-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb205-5"><a href="week-3-friday-workshop.html#cb205-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">affect_mean =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;aff_com&quot;</span>)),</span>
<span id="cb205-6"><a href="week-3-friday-workshop.html#cb205-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb205-7"><a href="week-3-friday-workshop.html#cb205-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">affect_sum =</span> <span class="fu">sum</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;aff_com&quot;</span>)),</span>
<span id="cb205-8"><a href="week-3-friday-workshop.html#cb205-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb205-9"><a href="week-3-friday-workshop.html#cb205-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() </span></code></pre></div>
<p>Use the head() command to see the columns you created:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="week-3-friday-workshop.html#cb206-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb206-2"><a href="week-3-friday-workshop.html#cb206-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   aff_com2_likert7 aff_com3_likert7 aff_com4_likert7
##              &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1                3                3                3
## 2                5                4                4
## 3                2                3                2
## 4                4                3                3
## 5                2                3                2
## 6                3                3                3
## # … with 2 more variables: affect_mean &lt;dbl&gt;,
## #   affect_sum &lt;dbl&gt;</code></pre>
<p>Check for yourself that affect_mean column is the average of the three items for each person. As well, check for yourself that the affect_sum column is the sum of the three items for each person.</p>
<p>Sometimes there are too many columns to show across your screen when using the head() command. So you can also use the glimpse() command to see the columns:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="week-3-friday-workshop.html#cb208-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb208-2"><a href="week-3-friday-workshop.html#cb208-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 100
## Columns: 5
## $ aff_com2_likert7 &lt;dbl&gt; 3, 5, 2, 4, 2, 3, 4, 4, 4, 3, 4, …
## $ aff_com3_likert7 &lt;dbl&gt; 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 4, …
## $ aff_com4_likert7 &lt;dbl&gt; 3, 4, 2, 3, 2, 3, 4, 3, 3, 3, 4, …
## $ affect_mean      &lt;dbl&gt; 3.000, 4.333, 2.333, 3.333, 2.333…
## $ affect_sum       &lt;dbl&gt; 9, 13, 7, 10, 7, 9, 12, 10, 10, 9…</code></pre>
</div>
<div id="variance-of-scale-scores" class="section level2" number="4.8">
<h2><span class="header-section-number">4.8</span> Variance of scale scores</h2>
<p>We will now calculate the variance of the two scale score columns:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="week-3-friday-workshop.html#cb210-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb210-2"><a href="week-3-friday-workshop.html#cb210-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">var_affect_mean_column =</span> <span class="fu">var</span>(affect_mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb210-3"><a href="week-3-friday-workshop.html#cb210-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">var_affect_sum_column =</span> <span class="fu">var</span>(affect_sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   var_affect_mean_column var_affect_sum_column
##                    &lt;dbl&gt;                 &lt;dbl&gt;
## 1                  0.340                  3.06</code></pre>
<p>In particular, notice that the variance the affect_sum column is 3.06. In the section below we will obtain this value through a very different calculation approach.</p>
</div>
<div id="variance-of-items" class="section level2" number="4.9">
<h2><span class="header-section-number">4.9</span> Variance of items</h2>
<p>In this section we focus on the item variances.</p>
<div id="approach-1" class="section level3" number="4.9.1">
<h3><span class="header-section-number">4.9.1</span> Approach 1</h3>
<p>Below is the traditionall approach to calculating the variance for columns. Try it out in RStudio.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="week-3-friday-workshop.html#cb212-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb212-2"><a href="week-3-friday-workshop.html#cb212-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">var_aff_com2 =</span> <span class="fu">var</span>(aff_com2_likert7),</span>
<span id="cb212-3"><a href="week-3-friday-workshop.html#cb212-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">var_aff_com3 =</span> <span class="fu">var</span>(aff_com3_likert7),</span>
<span id="cb212-4"><a href="week-3-friday-workshop.html#cb212-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">var_aff_com4 =</span> <span class="fu">var</span>(aff_com4_likert7))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   var_aff_com2 var_aff_com3 var_aff_com4
##          &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;
## 1        0.677        0.353        0.452</code></pre>
<p>If you inspect the output above you see the variances aff_com2, aff_com3, and aff_com4 items are 0.677, 0.353, and 0.452, respectively. Remember these number - we’re going to look for them in the output of the second approach.</p>
</div>
<div id="approach-2" class="section level3" number="4.9.2">
<h3><span class="header-section-number">4.9.2</span> Approach 2</h3>
<p>With the second approach to getting the variance of the items we use the cov() (i.e., covariance command). The commands below produce a covariance matrix.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="week-3-friday-workshop.html#cb214-1" aria-hidden="true" tabindex="-1"></a>cov_matrix <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb214-2"><a href="week-3-friday-workshop.html#cb214-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(aff_com2_likert7, aff_com3_likert7, aff_com4_likert7) <span class="sc">%&gt;%</span></span>
<span id="cb214-3"><a href="week-3-friday-workshop.html#cb214-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cov</span>()</span></code></pre></div>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="week-3-friday-workshop.html#cb215-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cov_matrix)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">aff_com2_likert7</th>
<th align="right">aff_com3_likert7</th>
<th align="right">aff_com4_likert7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">aff_com2_likert7</td>
<td align="right">0.6768</td>
<td align="right">0.2677</td>
<td align="right">0.3283</td>
</tr>
<tr class="even">
<td align="left">aff_com3_likert7</td>
<td align="right">0.2677</td>
<td align="right">0.3534</td>
<td align="right">0.1914</td>
</tr>
<tr class="odd">
<td align="left">aff_com4_likert7</td>
<td align="right">0.3283</td>
<td align="right">0.1914</td>
<td align="right">0.4520</td>
</tr>
</tbody>
</table>
<p>Examine the diagonal values of the covariance matrix. Notice that the (rounded) diagonal values are 0.677, 0.353, and 0.452. These are the same values we observed with Approach 1. We can conclude from this that in a covariance matrix the values along the diagonal represent variance.</p>
<p>In contrast, in matrix above, the values that are off-diagonal values represent covariances.</p>
</div>
</div>
<div id="variance-of-affect_sum-column" class="section level2" number="4.10">
<h2><span class="header-section-number">4.10</span> Variance of affect_sum column</h2>
<p>Previously, we saw that the variance of the affect_sum column was 3.06. In lecture, we learned that you can calculate the variance of this column from the items variance and covariances. In lecture, we saw the formula below.</p>
<p><span class="math display">\[
s_x^2= s_{A1}^2 + s_{A2}^2 + s_{A3}^2 + 2*COV(A1,A2) + 2*COV(A1,A3) + 2*COV(A2,A3)
\]</span></p>
<p>If we contextualize this formula for the current example it looks like the following:</p>
<p><span class="math display">\[
s_x^2 = s_{\text{aff_com2}}^2 + s_{\text{aff_com3}}^2 + s_{\text{aff_com4}}^2 
+ 2*COV(\text{aff_com2},\text{aff_com3}) 
+ 2*COV(\text{aff_com2},\text{aff_com4}) 
+ 2*COV(\text{aff_com3}, \text{aff_com4})
\]</span></p>
<p>However, the fancy formulas are just a way of saying sum up all the values in the covariance matrix.</p>
<p>We see the covariance matrix below:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="week-3-friday-workshop.html#cb216-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cov_matrix)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">aff_com2_likert7</th>
<th align="right">aff_com3_likert7</th>
<th align="right">aff_com4_likert7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">aff_com2_likert7</td>
<td align="right">0.6768</td>
<td align="right">0.2677</td>
<td align="right">0.3283</td>
</tr>
<tr class="even">
<td align="left">aff_com3_likert7</td>
<td align="right">0.2677</td>
<td align="right">0.3534</td>
<td align="right">0.1914</td>
</tr>
<tr class="odd">
<td align="left">aff_com4_likert7</td>
<td align="right">0.3283</td>
<td align="right">0.1914</td>
<td align="right">0.4520</td>
</tr>
</tbody>
</table>
<p>We can sum up all the values in the covariance matrix with the code below:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="week-3-friday-workshop.html#cb217-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(cov_matrix)</span></code></pre></div>
<pre><code>## [1] 3.057</code></pre>
<p>You see we get a value of 3.06 which is the variance of the affect_sum column.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-2-friday-workshop.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="notation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/04-workshop3.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
