<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Week 4 Friday Workshop | Welcome!</title>
  <meta name="description" content="Course notes for PSYC 3250" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Week 4 Friday Workshop | Welcome!" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course notes for PSYC 3250" />
  <meta name="github-repo" content="dstanley4/psyc3250bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Week 4 Friday Workshop | Welcome!" />
  
  <meta name="twitter:description" content="Course notes for PSYC 3250" />
  

<meta name="author" content="David J. Stanley" />


<meta name="date" content="2022-02-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-3-friday-workshop.html"/>
<link rel="next" href="notation.html"/>
<script src="libs/header-attrs/header-attrs.js"></script>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course:</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html"><i class="fa fa-check"></i><b>1</b> Week 1 Friday Workshop</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#a-focus-on-workflow"><i class="fa fa-check"></i><b>1.1</b> A focus on workflow</a></li>
<li class="chapter" data-level="1.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#r-works-with-plug-ins"><i class="fa fa-check"></i><b>1.2</b> R works with plug-ins</a></li>
<li class="chapter" data-level="1.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#software-choice"><i class="fa fa-check"></i><b>1.3</b> Software Choice</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#mac"><i class="fa fa-check"></i><b>1.3.1</b> Mac</a></li>
<li class="chapter" data-level="1.3.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#pc"><i class="fa fa-check"></i><b>1.3.2</b> PC</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-rstudio-not-r"><i class="fa fa-check"></i><b>1.4</b> Run RStudio not R</a></li>
<li class="chapter" data-level="1.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#rstudio-configuration-first-run-only"><i class="fa fa-check"></i><b>1.5</b> RStudio configuration, First run only</a></li>
<li class="chapter" data-level="1.6" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#begin-with-an-rstudio-project"><i class="fa fa-check"></i><b>1.6</b> Begin with an RStudio Project</a></li>
<li class="chapter" data-level="1.7" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#exploring-the-r-studio-interface"><i class="fa fa-check"></i><b>1.7</b> Exploring the R Studio Interface</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#console-panel"><i class="fa fa-check"></i><b>1.7.1</b> Console panel</a></li>
<li class="chapter" data-level="1.7.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#script-panel"><i class="fa fa-check"></i><b>1.7.2</b> Script Panel</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#writing-your-first-script"><i class="fa fa-check"></i><b>1.8</b> Writing your first script</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#create-the-script-file"><i class="fa fa-check"></i><b>1.8.1</b> Create the script file</a></li>
<li class="chapter" data-level="1.8.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#add-a-comment-to-your-script"><i class="fa fa-check"></i><b>1.8.2</b> Add a comment to your script</a></li>
<li class="chapter" data-level="1.8.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#background-about-the-tidyverse"><i class="fa fa-check"></i><b>1.8.3</b> Background about the tidyverse</a></li>
<li class="chapter" data-level="1.8.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#add-librarytidyverse-to-your-script"><i class="fa fa-check"></i><b>1.8.4</b> Add library(tidyverse) to your script</a></li>
<li class="chapter" data-level="1.8.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#activate-tidyverse-auto-complete-for-your-script"><i class="fa fa-check"></i><b>1.8.5</b> Activate tidyverse auto-complete for your script</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#loading-your-data"><i class="fa fa-check"></i><b>1.9</b> Loading your data</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#use-read_csv-not-read.csv-to-open-files."><i class="fa fa-check"></i><b>1.9.1</b> Use read_csv (not read.csv) to open files.</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#checking-out-your-data"><i class="fa fa-check"></i><b>1.10</b> Checking out your data</a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#view-see-a-spreadsheet-view-of-your-data"><i class="fa fa-check"></i><b>1.10.1</b> view(): See a spreadsheet view of your data</a></li>
<li class="chapter" data-level="1.10.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#print-see-you-data-in-the-console"><i class="fa fa-check"></i><b>1.10.2</b> print(): See you data in the Console</a></li>
<li class="chapter" data-level="1.10.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#head-check-out-the-first-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.3</b> head(): Check out the first few rows of data</a></li>
<li class="chapter" data-level="1.10.4" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#tail-check-out-the-last-few-rows-of-data"><i class="fa fa-check"></i><b>1.10.4</b> tail(): Check out the last few rows of data</a></li>
<li class="chapter" data-level="1.10.5" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#summary-quick-summaries"><i class="fa fa-check"></i><b>1.10.5</b> summary(): Quick summaries</a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-vs.-source-with-echo-vs.-source"><i class="fa fa-check"></i><b>1.11</b> Run <em>vs.</em> Source with Echo <em>vs.</em> Source</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#run-select-text"><i class="fa fa-check"></i><b>1.11.1</b> Run select text</a></li>
<li class="chapter" data-level="1.11.2" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#source-without-echo"><i class="fa fa-check"></i><b>1.11.2</b> Source (without Echo)</a></li>
<li class="chapter" data-level="1.11.3" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#source-with-echo"><i class="fa fa-check"></i><b>1.11.3</b> Source with Echo</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#trying-source-with-echo"><i class="fa fa-check"></i><b>1.12</b> Trying Source with Echo</a></li>
<li class="chapter" data-level="1.13" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#a-few-key-points-about"><i class="fa fa-check"></i><b>1.13</b> A few key points about</a>
<ul>
<li class="chapter" data-level="1.13.1" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#lists"><i class="fa fa-check"></i><b>1.13.1</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#revisiting-read_csv"><i class="fa fa-check"></i><b>1.14</b> Revisiting read_csv()</a></li>
<li class="chapter" data-level="1.15" data-path="week-1-friday-workshop.html"><a href="week-1-friday-workshop.html#thats-it"><i class="fa fa-check"></i><b>1.15</b> That’s it!</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html"><i class="fa fa-check"></i><b>2</b> Handling Data with the Tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>2.1</b> Required</a></li>
<li class="chapter" data-level="2.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>2.2</b> Objective</a></li>
<li class="chapter" data-level="2.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-the-console"><i class="fa fa-check"></i><b>2.3</b> Using the Console</a></li>
<li class="chapter" data-level="2.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tidyverse-help-with-the-introverse"><i class="fa fa-check"></i><b>2.4</b> Tidyverse help with the Introverse</a></li>
<li class="chapter" data-level="2.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#basic-tidyverse-commands"><i class="fa fa-check"></i><b>2.5</b> Basic tidyverse commands</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select"><i class="fa fa-check"></i><b>2.5.1</b> select()</a></li>
<li class="chapter" data-level="2.5.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise"><i class="fa fa-check"></i><b>2.5.2</b> summarise()</a></li>
<li class="chapter" data-level="2.5.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#filter"><i class="fa fa-check"></i><b>2.5.3</b> filter()</a></li>
<li class="chapter" data-level="2.5.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#group_by"><i class="fa fa-check"></i><b>2.5.4</b> group_by()</a></li>
<li class="chapter" data-level="2.5.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate"><i class="fa fa-check"></i><b>2.5.5</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#advanced-tidyverse-commands"><i class="fa fa-check"></i><b>2.6</b> Advanced tidyverse commands</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select-1"><i class="fa fa-check"></i><b>2.6.1</b> select()</a></li>
<li class="chapter" data-level="2.6.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise-1"><i class="fa fa-check"></i><b>2.6.2</b> summarise()</a></li>
<li class="chapter" data-level="2.6.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate-1"><i class="fa fa-check"></i><b>2.6.3</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-help"><i class="fa fa-check"></i><b>2.7</b> Using help</a></li>
<li class="chapter" data-level="2.8" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#base-r-vs-tidyverse"><i class="fa fa-check"></i><b>2.8</b> Base R vs tidyverse</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tibbles-vs.-data-frames"><i class="fa fa-check"></i><b>2.8.1</b> Tibbles vs. data frames</a></li>
<li class="chapter" data-level="2.8.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read.csv-and-data-frames"><i class="fa fa-check"></i><b>2.8.2</b> read.csv() and data frames</a></li>
<li class="chapter" data-level="2.8.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read_csv-and-tibbles"><i class="fa fa-check"></i><b>2.8.3</b> read_csv() and tibbles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html"><i class="fa fa-check"></i><b>3</b> Week 2 Friday Workshop</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#required-packages"><i class="fa fa-check"></i><b>3.1</b> Required Packages</a></li>
<li class="chapter" data-level="3.2" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#goals"><i class="fa fa-check"></i><b>3.2</b> Goals</a></li>
<li class="chapter" data-level="3.3" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#data-and-column-names"><i class="fa fa-check"></i><b>3.3</b> Data and column names</a></li>
<li class="chapter" data-level="3.4" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#install-packages"><i class="fa fa-check"></i><b>3.4</b> Install packages</a></li>
<li class="chapter" data-level="3.5" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#rstudio-project"><i class="fa fa-check"></i><b>3.5</b> RStudio Project</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#make-a-script"><i class="fa fa-check"></i><b>3.5.1</b> Make a script</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#loading-data"><i class="fa fa-check"></i><b>3.6</b> Loading data</a></li>
<li class="chapter" data-level="3.7" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#clean-and-screen-the-data"><i class="fa fa-check"></i><b>3.7</b> Clean and screen the data</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#numeric-screening"><i class="fa fa-check"></i><b>3.7.1</b> Numeric screening</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#flipping-responses-to-reverse-key-items"><i class="fa fa-check"></i><b>3.8</b> Flipping responses to reverse-key items</a></li>
<li class="chapter" data-level="3.9" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#making-scale-scores"><i class="fa fa-check"></i><b>3.9</b> Making scale scores</a></li>
<li class="chapter" data-level="3.10" data-path="week-2-friday-workshop.html"><a href="week-2-friday-workshop.html#descriptive-statistics-for-scale-scores"><i class="fa fa-check"></i><b>3.10</b> Descriptive statistics for scale scores</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html"><i class="fa fa-check"></i><b>4</b> Week 3 Friday Workshop</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#required-packages-1"><i class="fa fa-check"></i><b>4.1</b> Required Packages</a></li>
<li class="chapter" data-level="4.2" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#goals-1"><i class="fa fa-check"></i><b>4.2</b> Goals</a></li>
<li class="chapter" data-level="4.3" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#data-and-column-names-1"><i class="fa fa-check"></i><b>4.3</b> Data and column names</a></li>
<li class="chapter" data-level="4.4" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#install-packages-1"><i class="fa fa-check"></i><b>4.4</b> Install packages</a></li>
<li class="chapter" data-level="4.5" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#rstudio-project-1"><i class="fa fa-check"></i><b>4.5</b> RStudio Project</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#make-a-script-1"><i class="fa fa-check"></i><b>4.5.1</b> Make a script</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#week-2-catchup"><i class="fa fa-check"></i><b>4.6</b> Week 2 Catchup</a></li>
<li class="chapter" data-level="4.7" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#creating-compositescale-scores"><i class="fa fa-check"></i><b>4.7</b> Creating composite/scale scores</a></li>
<li class="chapter" data-level="4.8" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-scale-scores"><i class="fa fa-check"></i><b>4.8</b> Variance of scale scores</a></li>
<li class="chapter" data-level="4.9" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-items"><i class="fa fa-check"></i><b>4.9</b> Variance of items</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#approach-1"><i class="fa fa-check"></i><b>4.9.1</b> Approach 1</a></li>
<li class="chapter" data-level="4.9.2" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#approach-2"><i class="fa fa-check"></i><b>4.9.2</b> Approach 2</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="week-3-friday-workshop.html"><a href="week-3-friday-workshop.html#variance-of-affect_sum-column"><i class="fa fa-check"></i><b>4.10</b> Variance of affect_sum column</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html"><i class="fa fa-check"></i><b>5</b> Week 4 Friday Workshop</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#required-packagess"><i class="fa fa-check"></i><b>5.1</b> Required Packagess</a></li>
<li class="chapter" data-level="5.2" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#goals-2"><i class="fa fa-check"></i><b>5.2</b> Goals</a></li>
<li class="chapter" data-level="5.3" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#install-packages-2"><i class="fa fa-check"></i><b>5.3</b> Install packages</a></li>
<li class="chapter" data-level="5.4" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#rstudio-project-2"><i class="fa fa-check"></i><b>5.4</b> RStudio Project</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#make-a-script-2"><i class="fa fa-check"></i><b>5.4.1</b> Make a script</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#code-catchup"><i class="fa fa-check"></i><b>5.5</b> Code Catchup</a></li>
<li class="chapter" data-level="5.6" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#reliability"><i class="fa fa-check"></i><b>5.6</b> Reliability</a></li>
<li class="chapter" data-level="5.7" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#cronbachs-alpha"><i class="fa fa-check"></i><b>5.7</b> Cronbach’s Alpha</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#alpha-via-covariance-matrix"><i class="fa fa-check"></i><b>5.7.1</b> Alpha via covariance matrix</a></li>
<li class="chapter" data-level="5.7.2" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#alpha-via-psych-package"><i class="fa fa-check"></i><b>5.7.2</b> Alpha via psych package</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#standardized-alpha"><i class="fa fa-check"></i><b>5.8</b> Standardized Alpha</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#standardized-alpha-via-correlation-matrix"><i class="fa fa-check"></i><b>5.8.1</b> Standardized Alpha via correlation matrix</a></li>
<li class="chapter" data-level="5.8.2" data-path="week-4-friday-workshop.html"><a href="week-4-friday-workshop.html#standardized-alpha-via-psych-package"><i class="fa fa-check"></i><b>5.8.2</b> Standardized Alpha via psych package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="notation.html"><a href="notation.html"><i class="fa fa-check"></i><b>6</b> Notation</a>
<ul>
<li class="chapter" data-level="6.1" data-path="notation.html"><a href="notation.html#measurement-notation"><i class="fa fa-check"></i><b>6.1</b> Measurement Notation</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="scaling.html"><a href="scaling.html"><i class="fa fa-check"></i><b>7</b> Scaling</a>
<ul>
<li class="chapter" data-level="7.1" data-path="scaling.html"><a href="scaling.html#data-entry"><i class="fa fa-check"></i><b>7.1</b> Data entry</a></li>
<li class="chapter" data-level="7.2" data-path="scaling.html"><a href="scaling.html#loading-data-1"><i class="fa fa-check"></i><b>7.2</b> Loading data</a></li>
<li class="chapter" data-level="7.3" data-path="scaling.html"><a href="scaling.html#viewing-data"><i class="fa fa-check"></i><b>7.3</b> Viewing data</a></li>
<li class="chapter" data-level="7.4" data-path="scaling.html"><a href="scaling.html#summary-statistics"><i class="fa fa-check"></i><b>7.4</b> Summary statistics</a></li>
<li class="chapter" data-level="7.5" data-path="scaling.html"><a href="scaling.html#converting-units"><i class="fa fa-check"></i><b>7.5</b> Converting units</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="scaling.html"><a href="scaling.html#inches"><i class="fa fa-check"></i><b>7.5.1</b> Inches</a></li>
<li class="chapter" data-level="7.5.2" data-path="scaling.html"><a href="scaling.html#z-scores"><i class="fa fa-check"></i><b>7.5.2</b> <em>z</em>-scores</a></li>
<li class="chapter" data-level="7.5.3" data-path="scaling.html"><a href="scaling.html#t-scores"><i class="fa fa-check"></i><b>7.5.3</b> T-scores</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="scaling.html"><a href="scaling.html#frame-of-references"><i class="fa fa-check"></i><b>7.6</b> Frame of references</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="scaling.html"><a href="scaling.html#all-participants"><i class="fa fa-check"></i><b>7.6.1</b> All participants</a></li>
<li class="chapter" data-level="7.6.2" data-path="scaling.html"><a href="scaling.html#male-reference"><i class="fa fa-check"></i><b>7.6.2</b> Male reference</a></li>
<li class="chapter" data-level="7.6.3" data-path="scaling.html"><a href="scaling.html#canadian-reference"><i class="fa fa-check"></i><b>7.6.3</b> Canadian reference</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="scaling.html"><a href="scaling.html#summary-4"><i class="fa fa-check"></i><b>7.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="percentiles.html"><a href="percentiles.html"><i class="fa fa-check"></i><b>8</b> Percentiles</a>
<ul>
<li class="chapter" data-level="8.1" data-path="percentiles.html"><a href="percentiles.html#assuming-a-normal-distribution-approach"><i class="fa fa-check"></i><b>8.1</b> Assuming a normal distribution approach</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="percentiles.html"><a href="percentiles.html#a-single-case"><i class="fa fa-check"></i><b>8.1.1</b> A single case</a></li>
<li class="chapter" data-level="8.1.2" data-path="percentiles.html"><a href="percentiles.html#many-cases-using-r"><i class="fa fa-check"></i><b>8.1.2</b> Many cases using R</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="percentiles.html"><a href="percentiles.html#assumption-free-approach"><i class="fa fa-check"></i><b>8.2</b> Assumption free approach</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>9</b> Graphing</a>
<ul>
<li class="chapter" data-level="9.1" data-path="graphing.html"><a href="graphing.html#required-1"><i class="fa fa-check"></i><b>9.1</b> Required</a></li>
<li class="chapter" data-level="9.2" data-path="graphing.html"><a href="graphing.html#data"><i class="fa fa-check"></i><b>9.2</b> Data</a></li>
<li class="chapter" data-level="9.3" data-path="graphing.html"><a href="graphing.html#graph-basics"><i class="fa fa-check"></i><b>9.3</b> Graph basics</a></li>
<li class="chapter" data-level="9.4" data-path="graphing.html"><a href="graphing.html#graphing-efficiently"><i class="fa fa-check"></i><b>9.4</b> Graphing efficiently</a></li>
<li class="chapter" data-level="9.5" data-path="graphing.html"><a href="graphing.html#aesthetics"><i class="fa fa-check"></i><b>9.5</b> Aesthetics</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="graphing.html"><a href="graphing.html#fill-color"><i class="fa fa-check"></i><b>9.5.1</b> Fill color</a></li>
<li class="chapter" data-level="9.5.2" data-path="graphing.html"><a href="graphing.html#overriding-aes"><i class="fa fa-check"></i><b>9.5.2</b> Overriding aes()</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="graphing.html"><a href="graphing.html#apa-style"><i class="fa fa-check"></i><b>9.6</b> APA style</a></li>
<li class="chapter" data-level="9.7" data-path="graphing.html"><a href="graphing.html#axes"><i class="fa fa-check"></i><b>9.7</b> Axes</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="graphing.html"><a href="graphing.html#range"><i class="fa fa-check"></i><b>9.7.1</b> Range</a></li>
<li class="chapter" data-level="9.7.2" data-path="graphing.html"><a href="graphing.html#ticks"><i class="fa fa-check"></i><b>9.7.2</b> Ticks</a></li>
<li class="chapter" data-level="9.7.3" data-path="graphing.html"><a href="graphing.html#labels"><i class="fa fa-check"></i><b>9.7.3</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="graphing.html"><a href="graphing.html#axis-values"><i class="fa fa-check"></i><b>9.8</b> Axis values</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="graphing.html"><a href="graphing.html#text"><i class="fa fa-check"></i><b>9.8.1</b> Text</a></li>
<li class="chapter" data-level="9.8.2" data-path="graphing.html"><a href="graphing.html#angle"><i class="fa fa-check"></i><b>9.8.2</b> Angle</a></li>
<li class="chapter" data-level="9.8.3" data-path="graphing.html"><a href="graphing.html#alignment"><i class="fa fa-check"></i><b>9.8.3</b> Alignment</a></li>
<li class="chapter" data-level="9.8.4" data-path="graphing.html"><a href="graphing.html#order"><i class="fa fa-check"></i><b>9.8.4</b> Order</a></li>
<li class="chapter" data-level="9.8.5" data-path="graphing.html"><a href="graphing.html#legend-order"><i class="fa fa-check"></i><b>9.8.5</b> Legend order</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="graphing.html"><a href="graphing.html#custom-colours"><i class="fa fa-check"></i><b>9.9</b> Custom colours</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="graphing.html"><a href="graphing.html#r-palette"><i class="fa fa-check"></i><b>9.9.1</b> R palette</a></li>
<li class="chapter" data-level="9.9.2" data-path="graphing.html"><a href="graphing.html#hex-colours"><i class="fa fa-check"></i><b>9.9.2</b> Hex colours</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="graphing.html"><a href="graphing.html#emoji"><i class="fa fa-check"></i><b>9.10</b> Emoji</a></li>
<li class="chapter" data-level="9.11" data-path="graphing.html"><a href="graphing.html#accessible-colors"><i class="fa fa-check"></i><b>9.11</b> Accessible Colors</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="graphing.html"><a href="graphing.html#rcolorbrewer"><i class="fa fa-check"></i><b>9.11.1</b> RColorBrewer</a></li>
<li class="chapter" data-level="9.11.2" data-path="graphing.html"><a href="graphing.html#avoid-color"><i class="fa fa-check"></i><b>9.11.2</b> Avoid color</a></li>
</ul></li>
<li class="chapter" data-level="9.12" data-path="graphing.html"><a href="graphing.html#saving"><i class="fa fa-check"></i><b>9.12</b> Saving</a>
<ul>
<li class="chapter" data-level="9.12.1" data-path="graphing.html"><a href="graphing.html#mac-1"><i class="fa fa-check"></i><b>9.12.1</b> MAC</a></li>
<li class="chapter" data-level="9.12.2" data-path="graphing.html"><a href="graphing.html#pc-or-mac"><i class="fa fa-check"></i><b>9.12.2</b> PC or MAC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Welcome!</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-4-friday-workshop" class="section level1" number="5">
<h1><span class="header-section-number">Chapter 5</span> Week 4 Friday Workshop</h1>
<div id="required-packagess" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Required Packagess</h2>
<p>The data files below are used in this chapter. The files are available at: <a href="https://github.com/dstanley4/psyc3250bookdown" class="uri">https://github.com/dstanley4/psyc3250bookdown</a></p>
<table>
<thead>
<tr class="header">
<th>Required Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="data_aff_survey.csv">data_aff_survey.csv</a></td>
</tr>
</tbody>
</table>
<p>The following CRAN packages must be installed:</p>
<table>
<thead>
<tr class="header">
<th>Required CRAN Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tidyverse</td>
</tr>
<tr class="even">
<td>janitor</td>
</tr>
<tr class="odd">
<td>skimr</td>
</tr>
<tr class="even">
<td>psych</td>
</tr>
</tbody>
</table>
<p><strong>Important Note:</strong> You should NOT use library(psych) at any point! There are major conflicts between the psych package and the tidyverse. We will access the psych package commands by preceding each command with psych:: instead of using library(psych).</p>
<p>The complete script for this project can be download here: <a href="script_workshop2.R">script_workshop2.R</a></p>
</div>
<div id="goals-2" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Goals</h2>
<p>For this workshop our goals are to learn how to:</p>
<ul>
<li><p>Calculate <strong>Cronbach’s alpha</strong> using a covariance matrix</p></li>
<li><p>Calculate <strong>Cronbach’s alpha</strong> using the <strong>psych::alpha() command</strong></p></li>
<li><p>Calculate <strong>standardized</strong> alpha using a covariance matrix</p></li>
<li><p>Calculate <strong>standardized</strong> alpha using the <strong>psych::alpha() command</strong></p></li>
<li><p>All of the above goals assume familiarity with past workshops.</p></li>
<li><p>DON’T WORRY ABOUT THE MATH. WE WILL COVER IT IN A FUTURE LECTURE.</p></li>
</ul>
</div>
<div id="install-packages-2" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Install packages</h2>
<p>You will need the same packages installed as you did for the Week 2 Friday workshop. However, we also need the <strong>psych</strong> package this week. You can install the <strong>psych</strong> package using the command below.</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="week-4-friday-workshop.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;psych&quot;</span>, <span class="at">dep =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><strong>WARNINGS</strong>: 1) Remember never put an install.packages() command in your script. Only ever type install.packages() commands into the Console. 2) NEVER use the library(psych) command, doing so breaks the tidyverse. We will use another approach to access commands in this package.</p>
</div>
<div id="rstudio-project-2" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> RStudio Project</h2>
<ol style="list-style-type: decimal">
<li><p>Create a folder on your computer for the example</p></li>
<li><p>Download the data file for this example: <a href="data_aff_survey.csv">data_aff_survey.csv</a>. ONLY obtain this file from the Downloads folder. If you open in another program and save it again - the data file will not work.</p></li>
<li><p>Place all the example data file in the folder you created in Step 1.</p></li>
<li><p>Use the menu item File &gt; New Project… to start the project</p></li>
<li><p>On the window that appears select “Existing Directory”</p></li>
<li><p>On the next screen, press the “Browse” button and find/select the folder with your data</p></li>
<li><p>Press the Create Project Button</p></li>
</ol>
<div id="make-a-script-2" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Make a script</h3>
<ol style="list-style-type: decimal">
<li><p>Go the File menu. File &gt; New File &gt; Script</p></li>
<li><p>When you write your code - place into this script.</p></li>
</ol>
</div>
</div>
<div id="code-catchup" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Code Catchup</h2>
<p>Place the code below into your script from last week:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="week-4-friday-workshop.html#cb222-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Date: YYYY-MM-DD</span></span>
<span id="cb222-2"><a href="week-4-friday-workshop.html#cb222-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Name: your name here</span></span>
<span id="cb222-3"><a href="week-4-friday-workshop.html#cb222-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Example: Workshop 3 PSYC 3250</span></span>
<span id="cb222-4"><a href="week-4-friday-workshop.html#cb222-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-5"><a href="week-4-friday-workshop.html#cb222-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Activate packages  </span></span>
<span id="cb222-6"><a href="week-4-friday-workshop.html#cb222-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb222-7"><a href="week-4-friday-workshop.html#cb222-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb222-8"><a href="week-4-friday-workshop.html#cb222-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb222-9"><a href="week-4-friday-workshop.html#cb222-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-10"><a href="week-4-friday-workshop.html#cb222-10" aria-hidden="true" tabindex="-1"></a><span class="do">## Load data </span></span>
<span id="cb222-11"><a href="week-4-friday-workshop.html#cb222-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-12"><a href="week-4-friday-workshop.html#cb222-12" aria-hidden="true" tabindex="-1"></a>my_missing_value_codes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;-999&quot;</span>, <span class="st">&quot;&quot;</span>, <span class="st">&quot;NA&quot;</span>)</span>
<span id="cb222-13"><a href="week-4-friday-workshop.html#cb222-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-14"><a href="week-4-friday-workshop.html#cb222-14" aria-hidden="true" tabindex="-1"></a>raw_data_survey <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;data_aff_survey.csv&quot;</span>,</span>
<span id="cb222-15"><a href="week-4-friday-workshop.html#cb222-15" aria-hidden="true" tabindex="-1"></a>                            <span class="at">na =</span> my_missing_value_codes,</span>
<span id="cb222-16"><a href="week-4-friday-workshop.html#cb222-16" aria-hidden="true" tabindex="-1"></a>                            <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb222-17"><a href="week-4-friday-workshop.html#cb222-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-18"><a href="week-4-friday-workshop.html#cb222-18" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> raw_data_survey</span>
<span id="cb222-19"><a href="week-4-friday-workshop.html#cb222-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-20"><a href="week-4-friday-workshop.html#cb222-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-21"><a href="week-4-friday-workshop.html#cb222-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Clean and screen </span></span>
<span id="cb222-22"><a href="week-4-friday-workshop.html#cb222-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-23"><a href="week-4-friday-workshop.html#cb222-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial cleaning</span></span>
<span id="cb222-24"><a href="week-4-friday-workshop.html#cb222-24" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb222-25"><a href="week-4-friday-workshop.html#cb222-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">&quot;rows&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb222-26"><a href="week-4-friday-workshop.html#cb222-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">remove_empty</span>(<span class="st">&quot;cols&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb222-27"><a href="week-4-friday-workshop.html#cb222-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb222-28"><a href="week-4-friday-workshop.html#cb222-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb222-29"><a href="week-4-friday-workshop.html#cb222-29" aria-hidden="true" tabindex="-1"></a><span class="do">## Flipping responses to reverse-key items </span></span>
<span id="cb222-30"><a href="week-4-friday-workshop.html#cb222-30" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb222-31"><a href="week-4-friday-workshop.html#cb222-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="dv">8</span> <span class="sc">-</span> <span class="fu">across</span>(<span class="at">.cols =</span> <span class="fu">ends_with</span>(<span class="st">&quot;_likert7rev&quot;</span>)) ) <span class="sc">%&gt;%</span> </span>
<span id="cb222-32"><a href="week-4-friday-workshop.html#cb222-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="at">.fn =</span> str_replace,</span>
<span id="cb222-33"><a href="week-4-friday-workshop.html#cb222-33" aria-hidden="true" tabindex="-1"></a>              <span class="at">.cols =</span> <span class="fu">ends_with</span>(<span class="st">&quot;_likert7rev&quot;</span>),</span>
<span id="cb222-34"><a href="week-4-friday-workshop.html#cb222-34" aria-hidden="true" tabindex="-1"></a>              <span class="at">pattern =</span> <span class="st">&quot;_likert7rev&quot;</span>,</span>
<span id="cb222-35"><a href="week-4-friday-workshop.html#cb222-35" aria-hidden="true" tabindex="-1"></a>              <span class="at">replacement =</span> <span class="st">&quot;_likert7&quot;</span>)</span></code></pre></div>
<p>Now go to the menu: Session &gt; Restart R</p>
<p>Then press the Source with Echo button to run the entire script.</p>
<p>Following this type the head() command in the Console:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="week-4-friday-workshop.html#cb223-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb223-2"><a href="week-4-friday-workshop.html#cb223-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   aff_com2_likert7 aff_com3_likert7 aff_com4_likert7
##              &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1                3                3                3
## 2                5                4                4
## 3                2                3                2
## 4                4                3                3
## 5                2                3                2
## 6                3                3                3</code></pre>
<p>Sometimes there are too many columns. So another option is to use the glimpse() command:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="week-4-friday-workshop.html#cb225-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb225-2"><a href="week-4-friday-workshop.html#cb225-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 100
## Columns: 3
## $ aff_com2_likert7 &lt;dbl&gt; 3, 5, 2, 4, 2, 3, 4, 4, 4, 3, 4, …
## $ aff_com3_likert7 &lt;dbl&gt; 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 4, …
## $ aff_com4_likert7 &lt;dbl&gt; 3, 4, 2, 3, 2, 3, 4, 3, 3, 3, 4, …</code></pre>
<p>You can see that the data has been loaded and all of the columns are no longer any “reverse key items.” To gain additional insight into this process - revisit previous Friday workshops.</p>
</div>
<div id="reliability" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Reliability</h2>
<p>For the rest of this Friday Workshop we focus on calculating the reliability of composite score. That is, the reliability of a column of numbers created by adding items together. Reliability ranges between 0 and 1. A reliability closer to 1.0 is better than a lower reliability.</p>
<p><strong>We have yet to cover reliability in lecture - so don’t worry if you don’t understand the math below. We will cover the math in a future lecture. For today - just realize that the math is presented just to show what happens inside the black box of the psych:alpha command. We will spend a substantial amount of time understanding the math and conceptual basis for reliability in future lectures. Just focus on the psych::alpha() command today and see how you can calculate reliability using R.</strong></p>
</div>
<div id="cronbachs-alpha" class="section level2" number="5.7">
<h2><span class="header-section-number">5.7</span> Cronbach’s Alpha</h2>
<p>When we discuss Cronbach’s alpha you know we are dealing with the original form of the data. That is, we are dealing with the actual scores there reported by participants - rather than some transformed version of those scores.</p>
<p>We use Cronbach’s alpha to describe a set “scale score.” That is, scores for a set of participants that are made by combining responses to several items.</p>
<p>In the code below, we combine the aff_com2, aff_com3, and aff_com4 items, by adding them together (i.e., summing them together) to create a new column called affect_sum.</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="week-4-friday-workshop.html#cb227-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating scale SUM scores</span></span>
<span id="cb227-2"><a href="week-4-friday-workshop.html#cb227-2" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span> </span>
<span id="cb227-3"><a href="week-4-friday-workshop.html#cb227-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb227-4"><a href="week-4-friday-workshop.html#cb227-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">affect_sum =</span> <span class="fu">sum</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;aff_com&quot;</span>)),</span>
<span id="cb227-5"><a href="week-4-friday-workshop.html#cb227-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb227-6"><a href="week-4-friday-workshop.html#cb227-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() </span></code></pre></div>
<p>The glimpse() command reveals this new column.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="week-4-friday-workshop.html#cb228-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb228-2"><a href="week-4-friday-workshop.html#cb228-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 100
## Columns: 4
## $ aff_com2_likert7 &lt;dbl&gt; 3, 5, 2, 4, 2, 3, 4, 4, 4, 3, 4, …
## $ aff_com3_likert7 &lt;dbl&gt; 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 4, …
## $ aff_com4_likert7 &lt;dbl&gt; 3, 4, 2, 3, 2, 3, 4, 3, 3, 3, 4, …
## $ affect_sum       &lt;dbl&gt; 9, 13, 7, 10, 7, 9, 12, 10, 10, 9…</code></pre>
<p>As does the head() command, although if the output is too wide some columns are not printed with this command:</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="week-4-friday-workshop.html#cb230-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb230-2"><a href="week-4-friday-workshop.html#cb230-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   aff_com2_likert7 aff_com3_likert7 aff_com4_likert7
##              &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1                3                3                3
## 2                5                4                4
## 3                2                3                2
## 4                4                3                3
## 5                2                3                2
## 6                3                3                3
## # … with 1 more variable: affect_sum &lt;dbl&gt;</code></pre>
<p>You can see that there is a new column called affect_sum and the values in this column were created by adding together the aff_com2, aff_com3, and aff_com4 items.</p>
<p>We can obtain the variance of the new affect_sum column with the commands below:</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="week-4-friday-workshop.html#cb232-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb232-2"><a href="week-4-friday-workshop.html#cb232-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">var_affect_sum =</span> <span class="fu">var</span>(affect_sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   var_affect_sum
##            &lt;dbl&gt;
## 1           3.06</code></pre>
<p>We can see the variance of this column is 3.06. That is, the variance of observed scores on affective commitment scale is 3.06. This variability in observed scores is composed of 1) actual variability in commitment levels across participants (i.e., true score variance) and 2) measurement error.</p>
<p>We might wonder, of the observed variance of 3.06, what proportion is due to actual variability in people’s affective commitment levels - and not measurement error. That is, we might wonder, what proportion of the 3.06 variance is due to variability in true scores. We determine that proportion by calculating Cronbach’s alpha.</p>
<div id="alpha-via-covariance-matrix" class="section level3" number="5.7.1">
<h3><span class="header-section-number">5.7.1</span> Alpha via covariance matrix</h3>
<p>In this section we review the logic of calculating Cronbach’s alpha. In practice, you would not use the approach in this section - it is merely to enhance your understanding of Cronbach’s alpha. In practice you would use the approach in the next section that uses the psych::alpha command to calculate standardized alpha.</p>
<p>To calculate alpha we begin by obtaining the just the columns with the item data for the scale.</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="week-4-friday-workshop.html#cb234-1" aria-hidden="true" tabindex="-1"></a>items <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb234-2"><a href="week-4-friday-workshop.html#cb234-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;aff_com&quot;</span>))</span></code></pre></div>
<p>We have a new tibble now, called <strong>items</strong>, that has just the affective commitment item data in it. You can see that tibble via the glimpse() command:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="week-4-friday-workshop.html#cb235-1" aria-hidden="true" tabindex="-1"></a>items <span class="sc">%&gt;%</span></span>
<span id="cb235-2"><a href="week-4-friday-workshop.html#cb235-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 100
## Columns: 3
## $ aff_com2_likert7 &lt;dbl&gt; 3, 5, 2, 4, 2, 3, 4, 4, 4, 3, 4, …
## $ aff_com3_likert7 &lt;dbl&gt; 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 4, …
## $ aff_com4_likert7 &lt;dbl&gt; 3, 4, 2, 3, 2, 3, 4, 3, 3, 3, 4, …</code></pre>
<p>Next, we calculate the covariance matrix based on those items.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="week-4-friday-workshop.html#cb237-1" aria-hidden="true" tabindex="-1"></a>cov_matrix <span class="ot">=</span> <span class="fu">cov</span>(items)</span></code></pre></div>
<p>You can see the values in the covariance matrix below:</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="week-4-friday-workshop.html#cb238-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cov_matrix)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">aff_com2_likert7</th>
<th align="right">aff_com3_likert7</th>
<th align="right">aff_com4_likert7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">aff_com2_likert7</td>
<td align="right">0.6768</td>
<td align="right">0.2677</td>
<td align="right">0.3283</td>
</tr>
<tr class="even">
<td align="left">aff_com3_likert7</td>
<td align="right">0.2677</td>
<td align="right">0.3534</td>
<td align="right">0.1914</td>
</tr>
<tr class="odd">
<td align="left">aff_com4_likert7</td>
<td align="right">0.3283</td>
<td align="right">0.1914</td>
<td align="right">0.4520</td>
</tr>
</tbody>
</table>
<p>Finally, we use the covariance matrix in the Cronbach’s alpha formula below. <strong>AGAIN, DON’T WORRY IF YOU DON’T UNDERSTAND THE MATH BELOW. THE MATH IS PRESENTED JUST TO SHOW YOU WHAT HAPPENS INSIDE THE BLACK BOX OF THE psych:alpha() COMMAND. WE WILL COVER THE MATH IN A FUTURE LECTURE.</strong></p>
<p><img src="ch_workshop_alpha/images/cron_alpha_calc.png" width="80%" /></p>
<p>Thus the value of Cronbach’s alpha is .7727002, or .77. The affect_sum column has variance of 3.06. This is an indication of the differences among people with respect to <strong>observed</strong> scores (i.e., the actual values in affect_sum column). Of course, not all of the variability in observed scores is due to differences among people (i.e., true scores). Some of the variability in observed scores (in the affect_sum column) is due to random measurement error. A Cronbach’s alpha of .77 indicates that we <strong>estimate</strong> 77% of the variability in scores in the affect_sum column is due to actual differences among people (i.e., variability in true scores).</p>
</div>
<div id="alpha-via-psych-package" class="section level3" number="5.7.2">
<h3><span class="header-section-number">5.7.2</span> Alpha via psych package</h3>
<p>You can obtain Cronbach’s alpha using the alpha command from the <strong>psych</strong> package. However, because we didn’t use library(psych), because it breaks the tidyverse, we add psych:: in front of the alpha() command.</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="week-4-friday-workshop.html#cb239-1" aria-hidden="true" tabindex="-1"></a>item_stats <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(items)</span>
<span id="cb239-2"><a href="week-4-friday-workshop.html#cb239-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(item_stats<span class="sc">$</span>total)</span></code></pre></div>
<pre><code>##  raw_alpha std.alpha G6(smc) average_r   S/N     ase mean
##     0.7727    0.7788  0.7058    0.5399 3.521 0.03735 3.48
##      sd median_r
##  0.5828   0.5473</code></pre>
<p>In the output you can see <strong>raw_alpha</strong> is 0.7727002, this is the value for Cronbach’s alpha.</p>
</div>
</div>
<div id="standardized-alpha" class="section level2" number="5.8">
<h2><span class="header-section-number">5.8</span> Standardized Alpha</h2>
<p>Before considering Standardized alpha - let’s think about what we did in the previous section with Cronbach’s alpha. With Cronbach’s alpha we added the items together (in their original form) to create a new column called affect_sum.</p>
<p>Permit me a slight digression into a cooking analogy. When you are cooking, you have a variety of ingredients that you combine, in different amounts, to create your final dish. Think of combining the columns to create affect_sum using this analogy. Each column is a different ingredient. The amount of each ingredient in the recipe is indicated by the variance of the column. Items with a large variance contribute more to the affect_sum column creation than items with a small variance.</p>
<p>When you are creating scale scores, you have a variety of items (i.e., ingredients) that you combine, in different amounts (based on their variance), to create your affect_sum column. We do not “do” anything to make items with greater variance contribute more. It’s just a fact that items with greater variance will contribute more the creation of the affect_sum column than items with smaller variances.</p>
<p>We use the skim() command on the data in its <strong>original form</strong> to assess the extent to which the items have different variances. Recall that variance is simply standard deviation squared - so when we examine standard deviations for items we are learning about the variance of each item. Examine the numeric.sd column in the output to see the standard deviation for each item. This column illustrates that the standard deviation (and variance) is different for the three items. Consequently, the items contributed differently to the creation of the affect_sum column.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="week-4-friday-workshop.html#cb241-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb241-2"><a href="week-4-friday-workshop.html#cb241-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb241-3"><a href="week-4-friday-workshop.html#cb241-3" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb241-4"><a href="week-4-friday-workshop.html#cb241-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;aff_com&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb241-5"><a href="week-4-friday-workshop.html#cb241-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div>
<pre><code>##      skim_variable numeric.mean numeric.sd
## 1 aff_com2_likert7         3.50     0.8227
## 2 aff_com3_likert7         3.49     0.5945
## 3 aff_com4_likert7         3.45     0.6723</code></pre>
<p>Although it is rare, some researchers like to <em>transform</em> the item data prior to creating the affect_sum column. Specifically, they transform the column for each item to have the same mean (i.e., 0) and the same standard deviation (i.e., 1.0) before adding the items together. Each item is transformed via the z-score formula below. This formula indicates that for each value in the an item column we subtract the column mean and then divide by the column standard deviation.</p>
<p><span class="math display">\[
z = \frac{X_i-\overline{X_{item}}}{s_{item}}
\]</span></p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="week-4-friday-workshop.html#cb243-1" aria-hidden="true" tabindex="-1"></a>analytic_data_survey <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb243-2"><a href="week-4-friday-workshop.html#cb243-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_aff_com2 =</span> (aff_com2_likert7 <span class="sc">-</span> <span class="fu">mean</span>(aff_com2_likert7))<span class="sc">/</span><span class="fu">sd</span>(aff_com2_likert7)) <span class="sc">%&gt;%</span></span>
<span id="cb243-3"><a href="week-4-friday-workshop.html#cb243-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_aff_com3 =</span> (aff_com3_likert7 <span class="sc">-</span> <span class="fu">mean</span>(aff_com3_likert7))<span class="sc">/</span><span class="fu">sd</span>(aff_com3_likert7)) <span class="sc">%&gt;%</span></span>
<span id="cb243-4"><a href="week-4-friday-workshop.html#cb243-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_aff_com4 =</span> (aff_com4_likert7 <span class="sc">-</span> <span class="fu">mean</span>(aff_com4_likert7))<span class="sc">/</span><span class="fu">sd</span>(aff_com4_likert7)) </span></code></pre></div>
<p>Now let’s place those items in their own tibble:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="week-4-friday-workshop.html#cb244-1" aria-hidden="true" tabindex="-1"></a>zscore_data <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb244-2"><a href="week-4-friday-workshop.html#cb244-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;z_&quot;</span>))</span></code></pre></div>
<p>We can see the columns in the tibble:</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="week-4-friday-workshop.html#cb245-1" aria-hidden="true" tabindex="-1"></a>zscore_data <span class="sc">%&gt;%</span></span>
<span id="cb245-2"><a href="week-4-friday-workshop.html#cb245-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 100
## Columns: 3
## $ z_aff_com2 &lt;dbl&gt; -0.6078, 1.8234, -1.8234, 0.6078, -1.82…
## $ z_aff_com3 &lt;dbl&gt; -0.8242, 0.8579, -0.8242, -0.8242, -0.8…
## $ z_aff_com4 &lt;dbl&gt; -0.6693, 0.8181, -2.1567, -0.6693, -2.1…</code></pre>
<p>As before use the skim() command on the data in its <strong>transformed (i.e., z-score) form</strong> to assess the extent to which the items now have different/similar variances. Recall that variance is simply standard deviation squared - so when we examine standard deviations for items we are learning about the variance of each item. You see a value of 1.0 for each item. This indicates that is were to add the values in these columns together to create a new column - each column would contribute equally to the creation of that new column. Using our cooking analogy, we now using the same amount of each ingredient when we create a scale score.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="week-4-friday-workshop.html#cb247-1" aria-hidden="true" tabindex="-1"></a>zscore_data <span class="sc">%&gt;%</span></span>
<span id="cb247-2"><a href="week-4-friday-workshop.html#cb247-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div>
<pre><code>##   skim_variable numeric.mean numeric.sd
## 1    z_aff_com2    1.164e-18          1
## 2    z_aff_com3   -3.508e-16          1
## 3    z_aff_com4   -2.298e-16          1</code></pre>
<p>In the code below, we combine the z_aff_com2, z_aff_com3, and z_aff_com4 items, by adding them together (i.e., summing them together) to create a new column called <strong>z_affect_sum</strong>. The <strong>z</strong> at the start of the column name reminds us that we created the column from the z-score versions of the original items.</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="week-4-friday-workshop.html#cb249-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating scale SUM scores</span></span>
<span id="cb249-2"><a href="week-4-friday-workshop.html#cb249-2" aria-hidden="true" tabindex="-1"></a>zscore_data <span class="ot">&lt;-</span> zscore_data <span class="sc">%&gt;%</span> </span>
<span id="cb249-3"><a href="week-4-friday-workshop.html#cb249-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb249-4"><a href="week-4-friday-workshop.html#cb249-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_affect_sum =</span> <span class="fu">sum</span>(<span class="fu">c_across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;z_aff&quot;</span>)),</span>
<span id="cb249-5"><a href="week-4-friday-workshop.html#cb249-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb249-6"><a href="week-4-friday-workshop.html#cb249-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() </span></code></pre></div>
<p>The glimpse() command reveals this new column.</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="week-4-friday-workshop.html#cb250-1" aria-hidden="true" tabindex="-1"></a>zscore_data <span class="sc">%&gt;%</span></span>
<span id="cb250-2"><a href="week-4-friday-workshop.html#cb250-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 100
## Columns: 4
## $ z_aff_com2   &lt;dbl&gt; -0.6078, 1.8234, -1.8234, 0.6078, -1.…
## $ z_aff_com3   &lt;dbl&gt; -0.8242, 0.8579, -0.8242, -0.8242, -0…
## $ z_aff_com4   &lt;dbl&gt; -0.6693, 0.8181, -2.1567, -0.6693, -2…
## $ z_affect_sum &lt;dbl&gt; -2.1013, 3.4993, -4.8043, -0.8858, -4…</code></pre>
<p>As does the head() command, although if the output is too wide some columns are not printed with this command:</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="week-4-friday-workshop.html#cb252-1" aria-hidden="true" tabindex="-1"></a>zscore_data <span class="sc">%&gt;%</span></span>
<span id="cb252-2"><a href="week-4-friday-workshop.html#cb252-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   z_aff_com2 z_aff_com3 z_aff_com4 z_affect_sum
##        &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;
## 1     -0.608     -0.824     -0.669       -2.10 
## 2      1.82       0.858      0.818        3.50 
## 3     -1.82      -0.824     -2.16        -4.80 
## 4      0.608     -0.824     -0.669       -0.886
## 5     -1.82      -0.824     -2.16        -4.80 
## 6     -0.608     -0.824     -0.669       -2.10</code></pre>
<p>You can see that there is a new column called <strong>z_affect_sum</strong> and the values in this column were created by adding together the z_aff_com2, z_aff_com3, and z_aff_com4 items.</p>
<p>We can obtain the variance of the new <strong>z_affect_sum</strong> column with the commands below:</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="week-4-friday-workshop.html#cb254-1" aria-hidden="true" tabindex="-1"></a>zscore_data <span class="sc">%&gt;%</span></span>
<span id="cb254-2"><a href="week-4-friday-workshop.html#cb254-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">var_z_affect_sum =</span> <span class="fu">var</span>(z_affect_sum, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   var_z_affect_sum
##              &lt;dbl&gt;
## 1             6.24</code></pre>
<p>We can see the variance of this column is 6.24. That is, the variance of observed scores on affective commitment scale is 6.24. This variability in observed scores is composed of 1) actual variability in commitment levels across participants (i.e., true score variance) and 2) measurement error.</p>
<p>We might wonder, of the observed variance of 6.24, what proportion is due to actual variability in people’s affective commitment levels - and not measurement error. That is, we might wonder, what proportion of the 6.24 variance is due to variability in true scores. We determine that proportion by calculating Standardized alpha.</p>
<div id="standardized-alpha-via-correlation-matrix" class="section level3" number="5.8.1">
<h3><span class="header-section-number">5.8.1</span> Standardized Alpha via correlation matrix</h3>
<p>In this section we review the logic of calculating Standardized alpha. In practice, you would not use the approach in this section - it is merely to enhance your understanding of Standardized alpha. In practice you would use the approach in the next section that uses the psych::alpha command to calculate Standardized alpha.</p>
<p>To calculate alpha we begin by obtaining the just the columns with the item data for the scale.</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="week-4-friday-workshop.html#cb256-1" aria-hidden="true" tabindex="-1"></a>items <span class="ot">&lt;-</span> analytic_data_survey <span class="sc">%&gt;%</span></span>
<span id="cb256-2"><a href="week-4-friday-workshop.html#cb256-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;aff_com&quot;</span>))</span></code></pre></div>
<p>We have a new tibble now, called <strong>items</strong>, that has just the affective commitment item data in it. You can see that tibble via the glimpse() command:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="week-4-friday-workshop.html#cb257-1" aria-hidden="true" tabindex="-1"></a>items <span class="sc">%&gt;%</span></span>
<span id="cb257-2"><a href="week-4-friday-workshop.html#cb257-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 100
## Columns: 3
## $ aff_com2_likert7 &lt;dbl&gt; 3, 5, 2, 4, 2, 3, 4, 4, 4, 3, 4, …
## $ aff_com3_likert7 &lt;dbl&gt; 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 4, …
## $ aff_com4_likert7 &lt;dbl&gt; 3, 4, 2, 3, 2, 3, 4, 3, 3, 3, 4, …</code></pre>
<p>Next, we calculate the correlation matrix based on the times in their original form. **Note that this different from Cronbach’s alpha where we where interested in determining the reliability of scores in the aff_sum column - created from the aff_com2, aff_com3, and aff_com4 items in their original form. In that case, we used the covariance matrix of the original item. In the current scenario were are interested in determining the reliability of scores in the z_affect_sum column not the affect_sum column. Recall we used the transformed versions of the items to create the z_affect_sum column. That is we added the z_aff_com2, z_aff_com3, and z_aff_com4 column together to create z_affect_sum. Because we used the transformed version of the items, instead of the original form of the items, we need to use the correlation matrix in the calculation.</p>
<p>Optional learning point: If you were to calculate the covariance matrix from the z_aff_com2, z_aff_com3, and z_aff_com4 items you would see it is the same the correlation matrix for the aff_com2, aff_com3, and aff_com4 items.</p>
<p>Check out the correlation matrix below:</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="week-4-friday-workshop.html#cb259-1" aria-hidden="true" tabindex="-1"></a>correl_matrix <span class="ot">=</span> <span class="fu">cor</span>(items)</span></code></pre></div>
<p>You can see the values in the correlation matrix below:</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="week-4-friday-workshop.html#cb260-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(correl_matrix)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">aff_com2_likert7</th>
<th align="right">aff_com3_likert7</th>
<th align="right">aff_com4_likert7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">aff_com2_likert7</td>
<td align="right">1.0000</td>
<td align="right">0.5473</td>
<td align="right">0.5935</td>
</tr>
<tr class="even">
<td align="left">aff_com3_likert7</td>
<td align="right">0.5473</td>
<td align="right">1.0000</td>
<td align="right">0.4789</td>
</tr>
<tr class="odd">
<td align="left">aff_com4_likert7</td>
<td align="right">0.5935</td>
<td align="right">0.4789</td>
<td align="right">1.0000</td>
</tr>
</tbody>
</table>
<p>Finally, we use the correlation matrix in the usual alpha formula below. <strong>AGAIN, DON’T WORRY IF YOU DON’T UNDERSTAND THE MATH BELOW. THE MATH IS PRESENTED JUST TO SHOW YOU WHAT HAPPENS INSIDE THE BLACK BOX OF THE psych:alpha() COMMAND. WE WILL COVER THE MATH IN A FUTURE LECTURE.</strong></p>
<p><img src="ch_workshop_alpha/images/std_alpha_calc.png" width="80%" /></p>
<p>Thus the value of Standardized alpha is 0.778788, or .78, The z_affect_sum column has variance of 6.24 This is an indication of the differences among people with respect to <strong>observed</strong> scores (i.e., the actual values in <strong>z_affect_sum</strong> column). Of course, not all of the variability in observed scores is due to differences among people (i.e., true scores). Some of the variability in observed scores (in the <strong>z_affect_sum</strong> column) is due to random measurement error. A Standardized alpha of .78 indicates that we <strong>estimate</strong> 78% of the variability in scores in the <strong>z_affect_sum</strong> column is due to actual differences among people (i.e., variability in true scores).</p>
<p>Note that in these data, the Standardized alpha value (.78) is very close to the Cronbach’s alpha value (.77). This will not always be the case. In many circumstances, the two values will differ considerably. <strong>The extent to which the two values differ indicates the extent to which the items are contributing unequally to the creation of the affect_sum column compared to the z_affect_sum column.</strong></p>
</div>
<div id="standardized-alpha-via-psych-package" class="section level3" number="5.8.2">
<h3><span class="header-section-number">5.8.2</span> Standardized Alpha via psych package</h3>
<p>You can obtain standardized alpha using the alpha command from the <strong>psych</strong> package. However, because we didn’t use library(psych), because it breaks the tidyverse, we add psych:: in front of the alpha() command.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="week-4-friday-workshop.html#cb261-1" aria-hidden="true" tabindex="-1"></a>item_stats <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(items)</span>
<span id="cb261-2"><a href="week-4-friday-workshop.html#cb261-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(item_stats<span class="sc">$</span>total)</span></code></pre></div>
<pre><code>##  raw_alpha std.alpha G6(smc) average_r   S/N     ase mean
##     0.7727    0.7788  0.7058    0.5399 3.521 0.03735 3.48
##      sd median_r
##  0.5828   0.5473</code></pre>
<p>In the output you can see <strong>std.alpha</strong> is 0.778788, this is the value for standardized alpha.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-3-friday-workshop.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="notation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/05-workshop4.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
